// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _DefaultToastScatterChart from "./examples/default-toast-scatter-chart";
import _FilledToastScatterChart from "./examples/filled-toast-scatter-chart";
import _HeightWeightToast from "./examples/height-weight-toast";
import _LargeToastScatterChart from "./examples/large-toast-scatter-chart";
import _RdInvestmentAnalysisToast from "./examples/rd-investment-analysis-toast";
import _RealEstatePriceToast from "./examples/real-estate-price-toast";
import _SalesVsMarketingToast from "./examples/sales-vs-marketing-toast";

const _DefaultToastScatterChart_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import { Text, TextStyle, Transform, Alignment } from "flitter-ui";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, label: "Morocco" },
          { x: 4200, y: 70.71, label: "Egypt" },
          { x: 5900, y: 56.46, label: "Gabon" },
          { x: 6600, y: 72.74, label: "Algeria" },
          { x: 6700, y: 76.28, label: "Libya" },
          { x: 7100, y: 74.66, label: "Tunisia" },
          { x: 10500, y: 69.28, label: "Trinidad and Tobago" },
          { x: 12800, y: 72.09, label: "Mauritius" },
          { x: 18200, y: 78.68, label: "Malta" },
        ],
      },
      {
        legend: "America",
        data: [
          { x: 4800, y: 74.64, label: "Paraguay" },
          { x: 4900, y: 70.92, label: "El Salvador" },
          { x: 5600, y: 69.22, label: "Peru" },
          { x: 5800, y: 74.06, label: "Venezuela" },
          { x: 6600, y: 71.43, label: "Colombia" },
          { x: 8100, y: 71.41, label: "Brazil" },
          { x: 9600, y: 76.63, label: "Costa Rica" },
          { x: 9600, y: 74.94, label: "Mexico" },
          { x: 12400, y: 75.7, label: "Argentina" },
          { x: 31500, y: 79.96, label: "Canada" },
          { x: 32100, y: 77.43, label: "United States" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, label: "China" },
          { x: 7700, y: 69.66, label: "Iran" },
          { x: 8100, y: 71.41, label: "Thailand" },
          { x: 9700, y: 71.95, label: "Malaysia" },
          { x: 12000, y: 75.23, label: "Saudi Arabia" },
          { x: 19200, y: 75.58, label: "Korea, South" },
          { x: 25300, y: 77.06, label: "Taiwan" },
          { x: 27800, y: 81.53, label: "Singapore" },
          { x: 29400, y: 81.04, label: "Japan" },
          { x: 34200, y: 81.39, label: "Hong Kong" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 9800, y: 66.39, label: "Russia" },
          { x: 12000, y: 74.16, label: "Poland" },
          { x: 17900, y: 77.35, label: "Portugal" },
          { x: 23300, y: 79.37, label: "Spain" },
          { x: 27700, y: 79.54, label: "Italy" },
          { x: 28700, y: 78.54, label: "Germany" },
          { x: 28700, y: 79.44, label: "France" },
          { x: 29600, y: 78.27, label: "United Kingdom" },
          { x: 33800, y: 80.31, label: "Switzerland" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 2200, y: 64.56, label: "Papua New Guinea" },
          { x: 5900, y: 69.2, label: "Fiji" },
          { x: 23200, y: 78.49, label: "New Zealand" },
          { x: 30700, y: 80.26, label: "Australia" },
        ],
      },
    ],
  },
  custom: {
    xAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      return Transform.rotate({
        angle: -Math.PI / 6,
        alignment: Alignment.centerRight,
        child: Text(\`$\${(Number(name) / 1000).toFixed(0)}K\`, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: 10,
            color: "#64748b",
          }),
        }),
      });
    },
  },
  config: {
    title: { text: "GDP vs Life Expectancy", visible: true },
    scatter: { size: 8, strokeWidth: 2 },
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "y" ? \`\${name} yrs\` : name,
      },
    },
  },
});`;
const _FilledToastScatterChart_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Solar",
        data: [
          { x: 120, y: 18.5, label: "US" },
          { x: 85, y: 22.1, label: "Germany" },
          { x: 200, y: 15.3, label: "China" },
          { x: 45, y: 24.8, label: "Japan" },
          { x: 30, y: 20.6, label: "India" },
          { x: 55, y: 21.2, label: "Australia" },
        ],
      },
      {
        legend: "Wind",
        data: [
          { x: 140, y: 35.2, label: "US" },
          { x: 110, y: 42.1, label: "Germany" },
          { x: 280, y: 28.7, label: "China" },
          { x: 25, y: 30.5, label: "Japan" },
          { x: 60, y: 26.4, label: "India" },
          { x: 35, y: 38.9, label: "UK" },
        ],
      },
      {
        legend: "Hydro",
        data: [
          { x: 80, y: 45.0, label: "Brazil" },
          { x: 95, y: 48.3, label: "Canada" },
          { x: 350, y: 38.2, label: "China" },
          { x: 45, y: 52.1, label: "Norway" },
          { x: 20, y: 41.7, label: "Sweden" },
        ],
      },
    ],
  },
  custom: {
    yAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const val = parseFloat(name);
      const isHigh = val >= 40;
      return Text(\`\${name}%\`, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isHigh ? "bold" : "normal",
          color: isHigh ? "#059669" : "#64748b",
        }),
      });
    },
  },
  config: {
    scatter: { fill: true, size: 10, strokeWidth: 0 },
    colors: ["#f59e0b", "#3b82f6", "#06b6d4"],
    title: { text: "Renewable Energy Capacity vs Efficiency", visible: true },
  },
});`;
const _HeightWeightToast_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import {
  Container,
  BoxDecoration,
  EdgeInsets,
  Text,
  TextStyle,
  Row,
  SizedBox,
  MainAxisSize,
  BorderRadius,
} from "flitter-ui";

const legendColors: Record<string, string> = {
  Male: "#3b82f6",
  Female: "#ec4899",
};

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Male",
        data: [
          { x: 170, y: 72, label: "M1" },
          { x: 175, y: 80, label: "M2" },
          { x: 180, y: 85, label: "M3" },
          { x: 168, y: 68, label: "M4" },
          { x: 183, y: 92, label: "M5" },
          { x: 177, y: 78, label: "M6" },
          { x: 185, y: 95, label: "M7" },
          { x: 172, y: 74, label: "M8" },
          { x: 190, y: 100, label: "M9" },
        ],
      },
      {
        legend: "Female",
        data: [
          { x: 155, y: 50, label: "F1" },
          { x: 160, y: 55, label: "F2" },
          { x: 165, y: 60, label: "F3" },
          { x: 158, y: 52, label: "F4" },
          { x: 170, y: 65, label: "F5" },
          { x: 163, y: 58, label: "F6" },
          { x: 168, y: 62, label: "F7" },
          { x: 157, y: 54, label: "F8" },
          { x: 172, y: 68, label: "F9" },
        ],
      },
    ],
  },
  custom: {
    legend: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const color = legendColors[name] ?? "#94a3b8";
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 8, vertical: 3 }),
        decoration: new BoxDecoration({
          color: \`\${color}18\`,
          borderRadius: BorderRadius.circular(12),
        }),
        child: Row({
          mainAxisSize: MainAxisSize.min,
          children: [
            Container({
              width: 8,
              height: 8,
              decoration: new BoxDecoration({
                color: color,
                borderRadius: BorderRadius.circular(4),
              }),
            }),
            SizedBox({ width: 5 }),
            Text(name, {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 11,
                fontWeight: "600",
                color: color,
              }),
            }),
          ],
        }),
      });
    },
  },
  config: {
    title: { text: "Height vs Weight Distribution", visible: true },
    scatter: { size: 8, strokeWidth: 2 },
    colors: ["#3b82f6", "#ec4899"],
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "x" ? \`\${name} cm\` : \`\${name} kg\`,
      },
    },
  },
});`;
const _LargeToastScatterChart_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import {
  Container,
  BoxDecoration,
  EdgeInsets,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  CrossAxisAlignment,
  Border,
  BorderSide,
} from "flitter-ui";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Series A",
        data: [
          { x: 1.2, y: 4.5, label: "Stripe" },
          { x: 0.8, y: 3.2, label: "Figma" },
          { x: 2.1, y: 8.5, label: "SpaceX" },
          { x: 0.5, y: 2.0, label: "Notion" },
          { x: 1.8, y: 6.8, label: "Databricks" },
        ],
      },
      {
        legend: "Series B",
        data: [
          { x: 3.5, y: 12.0, label: "Canva" },
          { x: 5.0, y: 18.5, label: "Discord" },
          { x: 4.2, y: 15.0, label: "Airtable" },
          { x: 2.8, y: 9.5, label: "Notion" },
          { x: 6.0, y: 22.0, label: "Plaid" },
        ],
      },
      {
        legend: "Series C+",
        data: [
          { x: 10.0, y: 35.0, label: "Stripe" },
          { x: 8.5, y: 28.0, label: "Databricks" },
          { x: 15.0, y: 50.0, label: "SpaceX" },
          { x: 7.0, y: 24.0, label: "Canva" },
          { x: 12.0, y: 42.0, label: "Discord" },
        ],
      },
    ],
  },
  custom: {
    title: (
      _args: undefined,
      context: any,
    ) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.only({ bottom: 8 }),
        decoration: new BoxDecoration({
          border: new Border({
            bottom: new BorderSide({ color: "#7c3aed", width: 2 }),
          }),
        }),
        child: Column({
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(title.text, {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 15,
                fontWeight: "bold",
                color: "#1e1b4b",
              }),
            }),
            Text("Investment rounds across top startups", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 10,
                color: "#6b7280",
              }),
            }),
          ],
        }),
      });
    },
  },
  config: {
    title: { text: "Startup Funding Rounds", visible: true },
    scatter: { size: 14, strokeWidth: 2 },
    colors: ["#7c3aed", "#ec4899", "#f59e0b"],
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "x" ? \`$\${name}B\` : \`$\${name}B\`,
      },
    },
  },
});`;
const _RdInvestmentAnalysisToast_code = `import {
  Container,
  BoxDecoration,
  EdgeInsets,
  Text,
  TextStyle,
  BorderRadius,
} from "flitter-ui";
import ToastScatterChart from "./charts/toast-scatter-chart";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Pharmaceuticals",
        data: [
          { x: 4500, y: 128, label: "Pfizer" },
          { x: 6200, y: 195, label: "Roche" },
          { x: 3800, y: 102, label: "Merck" },
          { x: 8100, y: 248, label: "Johnson & Johnson" },
          { x: 5400, y: 167, label: "Novartis" },
          { x: 7300, y: 221, label: "AstraZeneca" },
        ],
      },
      {
        legend: "Tech",
        data: [
          { x: 12000, y: 385, label: "Alphabet" },
          { x: 15000, y: 510, label: "Microsoft" },
          { x: 9500, y: 298, label: "Meta" },
          { x: 18000, y: 620, label: "Amazon" },
          { x: 7800, y: 245, label: "Apple" },
          { x: 6200, y: 178, label: "Intel" },
        ],
      },
      {
        legend: "Automotive",
        data: [
          { x: 5800, y: 88, label: "Toyota" },
          { x: 7200, y: 112, label: "Volkswagen" },
          { x: 3500, y: 64, label: "GM" },
          { x: 4100, y: 75, label: "Ford" },
          { x: 9400, y: 156, label: "Tesla" },
          { x: 6600, y: 98, label: "BMW" },
        ],
      },
    ],
  },
  custom: {
    dataLabel: ({ label }: { label?: string }) =>
      Container({
        padding: EdgeInsets.symmetric({ horizontal: 5, vertical: 2 }),
        decoration: new BoxDecoration({
          color: "rgba(15, 23, 42, 0.75)",
          borderRadius: BorderRadius.circular(4),
        }),
        child: Text(label ?? "", {
          style: new TextStyle({ fontSize: 9, color: "#ffffff" }),
        }),
      }),
  },
  config: {
    title: { text: "R&D vs Patents", visible: true },
    scatter: { fill: true, size: 10, strokeWidth: 1 },
    colors: ["#2563eb", "#dc2626", "#059669"],
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "x" ? \`$\${(Number(name) / 1000).toFixed(0)}M\` : \`\${name}\`,
      },
    },
  },
});`;
const _RealEstatePriceToast_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Downtown",
        data: [
          { x: 850, y: 420000, label: "Apt A" },
          { x: 1100, y: 580000, label: "Apt B" },
          { x: 1400, y: 720000, label: "Condo C" },
          { x: 1800, y: 950000, label: "Loft D" },
          { x: 2200, y: 1150000, label: "Penthouse E" },
          { x: 950, y: 490000, label: "Studio F" },
        ],
      },
      {
        legend: "Suburbs",
        data: [
          { x: 1200, y: 280000, label: "House A" },
          { x: 1600, y: 350000, label: "House B" },
          { x: 2000, y: 420000, label: "House C" },
          { x: 2500, y: 510000, label: "House D" },
          { x: 3000, y: 620000, label: "House E" },
          { x: 1800, y: 380000, label: "House F" },
        ],
      },
      {
        legend: "Waterfront",
        data: [
          { x: 1500, y: 650000, label: "Villa A" },
          { x: 2000, y: 890000, label: "Villa B" },
          { x: 2800, y: 1200000, label: "Estate C" },
          { x: 3500, y: 1500000, label: "Estate D" },
          { x: 1800, y: 750000, label: "Cottage E" },
        ],
      },
    ],
  },
  custom: {
    xAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      return Text(\`\${name} ft\\u00B2\`, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          color: "#64748b",
        }),
      });
    },
    yAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const val = Number(name);
      const formatted = val >= 1000000
        ? \`$\${(val / 1000000).toFixed(1)}M\`
        : \`$\${(val / 1000).toFixed(0)}K\`;
      const isMillionPlus = val >= 1000000;
      return Text(formatted, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isMillionPlus ? "bold" : "normal",
          color: isMillionPlus ? "#7c3aed" : "#64748b",
        }),
      });
    },
  },
  config: {
    scatter: { fill: true, size: 12, strokeWidth: 1 },
    colors: ["#059669", "#d97706", "#7c3aed"],
    title: { text: "Real Estate Pricing", visible: true },
  },
});`;
const _SalesVsMarketingToast_code = `import ToastScatterChart from "./charts/toast-scatter-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  BoxShadow,
} from "flitter-ui";

const seriesColors = ["#3b82f6", "#f97316", "#8b5cf6", "#10b981"];

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Electronics",
        data: [
          { x: 12, y: 85, label: "Q1" },
          { x: 18, y: 120, label: "Q2" },
          { x: 25, y: 155, label: "Q3" },
          { x: 30, y: 190, label: "Q4" },
          { x: 22, y: 140, label: "Q5" },
        ],
      },
      {
        legend: "Apparel",
        data: [
          { x: 8, y: 45, label: "Q1" },
          { x: 15, y: 78, label: "Q2" },
          { x: 20, y: 95, label: "Q3" },
          { x: 28, y: 130, label: "Q4" },
          { x: 35, y: 160, label: "Q5" },
        ],
      },
      {
        legend: "Food & Beverage",
        data: [
          { x: 5, y: 60, label: "Q1" },
          { x: 10, y: 90, label: "Q2" },
          { x: 14, y: 105, label: "Q3" },
          { x: 18, y: 125, label: "Q4" },
          { x: 24, y: 150, label: "Q5" },
          { x: 30, y: 180, label: "Q6" },
        ],
      },
      {
        legend: "Home & Garden",
        data: [
          { x: 6, y: 30, label: "Q1" },
          { x: 11, y: 55, label: "Q2" },
          { x: 16, y: 72, label: "Q3" },
          { x: 21, y: 88, label: "Q4" },
          { x: 27, y: 110, label: "Q5" },
        ],
      },
    ],
  },
  custom: {
    scatter: (
      { legend, index }: { label: string; legend: string; index: number },
      context: any,
    ) => {
      const seriesIdx = context.legends.indexOf(legend);
      const color = seriesColors[seriesIdx] ?? "#94a3b8";
      const dataset = context.data.datasets[seriesIdx];
      const point = dataset?.data[index];
      const isHighRevenue = point && point.y >= 140;
      return Container({
        decoration: new BoxDecoration({
          color: color,
          borderRadius: BorderRadius.circular(isHighRevenue ? 4 : 100),
          boxShadow: isHighRevenue
            ? [new BoxShadow({ color: \`\${color}66\`, blurRadius: 8 })]
            : [],
        }),
      });
    },
  },
  config: {
    scatter: { fill: true, size: 10, strokeWidth: 0 },
    colors: seriesColors,
    title: { text: "Sales vs Marketing Spend", visible: true },
  },
});`;

export const DefaultToastScatterChart = { Component: _DefaultToastScatterChart, code: _DefaultToastScatterChart_code };
export const FilledToastScatterChart = { Component: _FilledToastScatterChart, code: _FilledToastScatterChart_code };
export const LargeToastScatterChart = { Component: _LargeToastScatterChart, code: _LargeToastScatterChart_code };
export const SalesVsMarketingToast = { Component: _SalesVsMarketingToast, code: _SalesVsMarketingToast_code };
export const HeightWeightToast = { Component: _HeightWeightToast, code: _HeightWeightToast_code };
export const RealEstatePriceToast = { Component: _RealEstatePriceToast, code: _RealEstatePriceToast_code };
export const RdInvestmentAnalysisToast = { Component: _RdInvestmentAnalysisToast, code: _RdInvestmentAnalysisToast_code };
