// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BudgetAllocationToast from "./examples/budget-allocation";
import _DepartmentBudgetToast from "./examples/department-budget";
import _EmployeeDistributionToast from "./examples/employee-distribution";
import _EnergySourceToast from "./examples/energy-source";
import _HorizontalCategoryToast from "./examples/horizontal-category";
import _MarketingChannelToast from "./examples/marketing-channel";
import _ProductPLMixToast from "./examples/product-pl-mix";
import _RegionalRevenueToast from "./examples/regional-revenue";

const _BudgetAllocationToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Q1 2024", "Q2 2024", "Q3 2024", "Q4 2024"],
    datasets: [
      { legend: "Engineering", values: [450, 480, 520, 550] },
      { legend: "Marketing", values: [200, 220, 210, 240] },
      { legend: "Sales", values: [180, 190, 200, 210] },
      { legend: "Operations", values: [120, 130, 125, 140] },
    ],
  },
  config: { colors: ["#2563eb", "#dc2626", "#059669", "#d97706"], bar: { gap: 2 } },
});`;
const _DepartmentBudgetToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Product", "Engineering", "Design", "Marketing", "Sales"],
    datasets: [
      { legend: "Salaries", values: [280, 520, 180, 210, 260] },
      { legend: "Tools & Infra", values: [45, 190, 60, 85, 40] },
      { legend: "Training", values: [30, 55, 35, 25, 45] },
      { legend: "Travel", values: [20, 15, 10, 65, 80] },
    ],
  },
  config: {
    colors: ["#6366f1", "#a78bfa", "#c4b5fd", "#ddd6fe"],
    legend: { position: "right-top" },
  },
});`;
const _EmployeeDistributionToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Engineering", "Marketing", "Sales", "Support", "Design", "Product"],
    datasets: [
      { legend: "Junior", values: [45, 20, 25, 30, 12, 8] },
      { legend: "Mid-Level", values: [60, 25, 30, 20, 15, 12] },
      { legend: "Senior", values: [35, 15, 20, 10, 8, 10] },
    ],
  },
  config: { colors: ["#3b82f6", "#f59e0b", "#ef4444"], bar: { gap: 1 } },
});`;
const _EnergySourceToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Solar", values: [120, 140, 180, 220, 280, 320, 340, 310, 260, 200, 150, 110] },
      { legend: "Wind", values: [200, 210, 190, 170, 160, 140, 130, 145, 175, 195, 220, 230] },
      { legend: "Hydro", values: [150, 160, 180, 200, 190, 170, 155, 140, 150, 165, 170, 155] },
      { legend: "Nuclear", values: [300, 300, 295, 305, 300, 310, 305, 300, 298, 302, 300, 305] },
    ],
  },
  config: { colors: ["#eab308", "#22c55e", "#06b6d4", "#a855f7"] },
});`;
const _HorizontalCategoryToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: { colors: ["#6366f1", "#ec4899", "#f59e0b"] },
});`;
const _MarketingChannelToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "SEO", values: [320, 380, 410, 450, 520, 580] },
      { legend: "Paid Ads", values: [210, 250, 230, 270, 290, 310] },
      { legend: "Social", values: [140, 160, 180, 200, 220, 250] },
      { legend: "Email", values: [90, 100, 110, 120, 130, 145] },
    ],
  },
  config: { colors: ["#0ea5e9", "#8b5cf6", "#f97316", "#10b981"] },
});`;
const _ProductPLMixToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25", "Q3 '25"],
    datasets: [
      { legend: "Product A", values: [-20, 15, -5, 30, -10, 25, 8] },
      { legend: "Product B", values: [10, -12, 22, -8, 18, -15, 30] },
      { legend: "Product C", values: [5, -25, 12, 20, -18, 10, -7] },
    ],
  },
  config: { colors: ["#10b981", "#ef4444", "#3b82f6"] },
});`;
const _RegionalRevenueToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: {},
});`;

export const RegionalRevenueToast = { Component: _RegionalRevenueToast, code: _RegionalRevenueToast_code };
export const HorizontalCategoryToast = { Component: _HorizontalCategoryToast, code: _HorizontalCategoryToast_code };
export const ProductPLMixToast = { Component: _ProductPLMixToast, code: _ProductPLMixToast_code };
export const MarketingChannelToast = { Component: _MarketingChannelToast, code: _MarketingChannelToast_code };
export const BudgetAllocationToast = { Component: _BudgetAllocationToast, code: _BudgetAllocationToast_code };
export const EnergySourceToast = { Component: _EnergySourceToast, code: _EnergySourceToast_code };
export const EmployeeDistributionToast = { Component: _EmployeeDistributionToast, code: _EmployeeDistributionToast_code };
export const DepartmentBudgetToast = { Component: _DepartmentBudgetToast, code: _DepartmentBudgetToast_code };
