// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BudgetAllocationToast from "./examples/budget-allocation";
import _DepartmentBudgetToast from "./examples/department-budget";
import _EmployeeDistributionToast from "./examples/employee-distribution";
import _EnergySourceToast from "./examples/energy-source";
import _HorizontalCategoryToast from "./examples/horizontal-category";
import _MarketingChannelToast from "./examples/marketing-channel";
import _ProductPLMixToast from "./examples/product-pl-mix";
import _RegionalRevenueToast from "./examples/regional-revenue";

const _BudgetAllocationToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import {
  Container,
  BoxDecoration,
  EdgeInsets,
  BorderRadius,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  CrossAxisAlignment,
  SizedBox,
} from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Q1 2024", "Q2 2024", "Q3 2024", "Q4 2024"],
    datasets: [
      { legend: "Engineering", values: [450, 480, 520, 550] },
      { legend: "Marketing", values: [200, 220, 210, 240] },
      { legend: "Sales", values: [180, 190, 200, 210] },
      { legend: "Operations", values: [120, 130, 125, 140] },
    ],
  },
  config: {
    colors: ["#2563eb", "#dc2626", "#059669", "#d97706"],
    bar: { gap: 2 },
    title: { text: "Budget Allocation", visible: true },
  },
  custom: {
    title: (
      _args: undefined,
      context: any,
    ) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 12, vertical: 6 }),
        decoration: new BoxDecoration({
          color: "#eff6ff",
          borderRadius: BorderRadius.circular(6),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text("Budget Allocation ($K)", {
              style: new TextStyle({
                fontFamily: title.fontFamily ?? font.family,
                fontSize: title.fontSize,
                fontWeight: "700",
                color: "#1e40af",
              }),
            }),
            SizedBox({ height: 2 }),
            Text("Quarterly department spend breakdown", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 11,
                color: "#3b82f6",
              }),
            }),
          ],
        }),
      });
    },
  },
});`;
const _DepartmentBudgetToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Transform, Text, TextStyle, Alignment } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Product", "Engineering", "Design", "Marketing", "Sales"],
    datasets: [
      { legend: "Salaries", values: [280, 520, 180, 210, 260] },
      { legend: "Tools & Infra", values: [45, 190, 60, 85, 40] },
      { legend: "Training", values: [30, 55, 35, 25, 45] },
      { legend: "Travel", values: [20, 15, 10, 65, 80] },
    ],
  },
  config: {
    colors: ["#6366f1", "#a78bfa", "#c4b5fd", "#ddd6fe"],
    title: { text: "Department Budget ($K)", visible: true },
  },
  custom: {
    xAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      return Transform.rotate({
        angle: -Math.PI / 6,
        alignment: Alignment.centerRight,
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: 10,
            fontWeight: "600",
            color: "#4338ca",
          }),
        }),
      });
    },
  },
});`;
const _EmployeeDistributionToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Container, BoxDecoration, EdgeInsets, BorderRadius } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: { labels, datasets },
  config: {
    colors: ["#3b82f6", "#f59e0b", "#ef4444"],
    bar: { gap: 1 },
    title: { text: "Employee Distribution", visible: true },
  },
  custom: {
    bar: (
      { value, legend, label }: { value: number; legend: string; label: string },
      context: any,
    ) => {
      const labelIdx = labels.indexOf(label);
      const total = datasets.reduce((sum, ds) => sum + ds.values[labelIdx], 0);
      const colorMap: Record<string, string> = {
        Junior: "#3b82f6",
        "Mid-Level": "#f59e0b",
        Senior: "#ef4444",
      };
      const baseColor = colorMap[legend] ?? "#3b82f6";
      const isLargeDept = total >= 100;
      return Container({
        margin: EdgeInsets.symmetric({ horizontal: 1 }),
        decoration: new BoxDecoration({
          color: isLargeDept ? baseColor : \`\${baseColor}88\`,
          borderRadius: BorderRadius.circular(2),
        }),
      });
    },
  },
});`;
const _EnergySourceToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Solar", values: [120, 140, 180, 220, 280, 320, 340, 310, 260, 200, 150, 110] },
      { legend: "Wind", values: [200, 210, 190, 170, 160, 140, 130, 145, 175, 195, 220, 230] },
      { legend: "Hydro", values: [150, 160, 180, 200, 190, 170, 155, 140, 150, 165, 170, 155] },
      { legend: "Nuclear", values: [300, 300, 295, 305, 300, 310, 305, 300, 298, 302, 300, 305] },
    ],
  },
  config: {
    colors: ["#f59e0b", "#34d399", "#06b6d4", "#a78bfa"],
    bar: { gap: 4 },
    title: { text: "Energy Generation (GWh)", visible: true },
    grid: { color: "rgba(0,0,0,0.04)" },
  },
});`;
const _HorizontalCategoryToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Text, TextStyle, Row, SizedBox, MainAxisSize } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Tokyo", "London", "New York", "Berlin", "Sydney", "Toronto", "Singapore"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: {
    colors: ["#6366f1", "#ec4899", "#f59e0b"],
    title: { text: "Office Revenue by Region", visible: true },
  },
  custom: {
    yAxisLabel: (
      { name, index }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const medals = ["#c9a227", "#8a8a8a", "#b87333"];
      const isMedal = index < 3;
      return Row({
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(\`\${index + 1}\`, {
            style: new TextStyle({
              fontFamily: font.family,
              fontSize: 10,
              fontWeight: "bold",
              color: isMedal ? medals[index] : "#94a3b8",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(name, {
            style: new TextStyle({
              fontFamily: font.family,
              fontSize: font.size,
              fontWeight: isMedal ? "bold" : "normal",
              color: isMedal ? "#1e293b" : "#64748b",
            }),
          }),
        ],
      });
    },
  },
});`;
const _MarketingChannelToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets,
  },
  config: {
    colors: ["#0ea5e9", "#8b5cf6", "#f97316", "#10b981"],
    title: { text: "Marketing Conversions", visible: true },
    bar: { gap: 3 },
  },
  custom: {
    dataLabel: (
      { value, legend, label }: { value: number; label: string; legend: string },
      context: any,
    ) => {
      const { font } = context.config;
      const labelIdx = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"].indexOf(label);
      const total = datasets.reduce((sum, ds) => sum + ds.values[labelIdx], 0);
      if (legend !== "Email") return Text("", { style: new TextStyle({}) });
      return Text(\`\${(total / 1000).toFixed(1)}K\`, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: 9,
          fontWeight: "bold",
          color: "#334155",
        }),
      });
    },
  },
});`;
const _ProductPLMixToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25", "Q3 '25"],
    datasets: [
      { legend: "Product A", values: [-20, 15, -5, 30, -10, 25, 8] },
      { legend: "Product B", values: [10, -12, 22, -8, 18, -15, 30] },
      { legend: "Product C", values: [5, -25, 12, 20, -18, 10, -7] },
    ],
  },
  config: {
    colors: ["#10b981", "#ef4444", "#3b82f6"],
    title: { text: "Quarterly P&L Mix", visible: true },
    grid: { color: "rgba(0,0,0,0.06)" },
  },
  custom: {
    yAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const val = parseFloat(name);
      const isZero = val === 0;
      return Text(isZero ? "--- 0 ---" : name, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isZero ? "bold" : "normal",
          color: isZero ? "#ef4444" : val < 0 ? "#94a3b8" : "#334155",
        }),
      });
    },
  },
});`;
const _RegionalRevenueToast_code = `import ToastStackedBarChart from "./charts/toast-stacked-bar-chart";
import { Container, BoxDecoration, BorderRadius, EdgeInsets, Radius } from "flitter-ui";

const chart = ToastStackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: {
    colors: ["#6366f1", "#a78bfa", "#c4b5fd"],
    bar: { gap: 2 },
    title: { text: "Regional Revenue", visible: true },
  },
  custom: {
    bar: (
      { value, legend }: { value: number; legend: string },
      context: any,
    ) => {
      const colorMap: Record<string, string> = {
        "North America": "#6366f1",
        "Europe": "#a78bfa",
        "Asia Pacific": "#c4b5fd",
      };
      const isTopSegment = legend === "Asia Pacific";
      return Container({
        margin: EdgeInsets.symmetric({ horizontal: 1 }),
        decoration: new BoxDecoration({
          color: colorMap[legend] ?? "#6366f1",
          borderRadius: isTopSegment
            ? BorderRadius.only({
                topLeft: Radius.circular(6),
                topRight: Radius.circular(6),
              })
            : BorderRadius.zero,
        }),
      });
    },
  },
});`;

export const RegionalRevenueToast = { Component: _RegionalRevenueToast, code: _RegionalRevenueToast_code };
export const HorizontalCategoryToast = { Component: _HorizontalCategoryToast, code: _HorizontalCategoryToast_code };
export const ProductPLMixToast = { Component: _ProductPLMixToast, code: _ProductPLMixToast_code };
export const MarketingChannelToast = { Component: _MarketingChannelToast, code: _MarketingChannelToast_code };
export const BudgetAllocationToast = { Component: _BudgetAllocationToast, code: _BudgetAllocationToast_code };
export const EnergySourceToast = { Component: _EnergySourceToast, code: _EnergySourceToast_code };
export const EmployeeDistributionToast = { Component: _EmployeeDistributionToast, code: _EmployeeDistributionToast_code };
export const DepartmentBudgetToast = { Component: _DepartmentBudgetToast, code: _DepartmentBudgetToast_code };
