// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _AcquisitionChannelsToast from "./examples/acquisition-channels";
import _AppUsageToastStackedArea from "./examples/app-usage";
import _DefaultToastStackedAreaChart from "./examples/default-toast-stacked-area";
import _EnergyMixToastStackedArea from "./examples/energy-mix";
import _RevenueStreamStackedArea from "./examples/revenue-stream";
import _SupportTicketsToastStackedArea from "./examples/support-tickets";
import _TrafficSourceStackedArea from "./examples/traffic-source";

const _AcquisitionChannelsToast_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  BorderRadius,
} from "flitter-ui";

const colors = ["#2563eb", "#f97316", "#10b981"];
const latestValues = ["3.2K", "2.0K", "1.2K"];

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    datasets: [
      { legend: "Organic", values: [1800, 2100, 2400, 2700, 3000, 3200] },
      { legend: "Paid", values: [1200, 1400, 1100, 1600, 1800, 2000] },
      { legend: "Referral", values: [600, 750, 900, 850, 1000, 1150] },
    ],
  },
  config: {
    title: { text: "Acquisition Channels", visible: true },
    colors: ["#2563eb", "#f97316", "#10b981"],
    area: { opacity: 0.45 },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 8,
            height: 8,
            decoration: new BoxDecoration({
              color: colors[index],
              borderRadius: BorderRadius.circular(4),
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "#475569",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(latestValues[index] ?? "", {
            style: new TextStyle({
              fontSize: 11,
              color: colors[index],
              fontWeight: "600",
            }),
          }),
        ],
      }),
  },
});`;
const _AppUsageToastStackedArea_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import {
  Container,
  BoxDecoration,
  Border,
  BorderSide,
  Text,
  TextStyle,
} from "flitter-ui";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "iOS", values: [4500, 4700, 4900, 5200, 5500, 5800, 6100, 6000, 5900, 6200, 6500, 6800] },
      { legend: "Android", values: [5200, 5400, 5700, 6000, 6400, 6700, 7000, 6900, 6800, 7100, 7400, 7800] },
      { legend: "Web", values: [2800, 2900, 3000, 3100, 3200, 3100, 2900, 2800, 3100, 3300, 3500, 3600] },
    ],
  },
  config: {
    colors: ["#3b82f6", "#10b981", "#f59e0b"],
    area: { opacity: 0.45, strokeWidth: 2.5 },
    title: { text: "App Sessions by Platform", visible: true, alignment: "center" },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const isQuarterStart = index % 3 === 0;
      return Container({
        decoration: isQuarterStart
          ? new BoxDecoration({
              border: new Border({
                bottom: new BorderSide({ color: "#3b82f6", width: 2 }),
              }),
            })
          : undefined,
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: font.size,
            fontWeight: isQuarterStart ? "bold" : "normal",
            color: isQuarterStart ? "#1e40af" : "#94a3b8",
          }),
        }),
      });
    },
  },
});`;
const _DefaultToastStackedAreaChart_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  CrossAxisAlignment,
  SizedBox,
} from "flitter-ui";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Organic", values: [400, 450, 420, 480, 520, 510, 550, 530, 560, 600, 620, 650] },
      { legend: "Direct", values: [200, 220, 210, 230, 250, 240, 260, 255, 270, 290, 300, 310] },
      { legend: "Social", values: [100, 120, 130, 140, 160, 155, 170, 165, 180, 200, 210, 220] },
      { legend: "Referral", values: [50, 60, 55, 65, 70, 75, 80, 78, 85, 90, 95, 100] },
    ],
  },
  config: {
    colors: ["#6366f1", "#22c55e", "#f59e0b", "#ec4899"],
    title: { text: "Traffic Source Breakdown", visible: true, alignment: "center" },
    area: { opacity: 0.5 },
  },
  custom: {
    title: (_args: undefined, context: any) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 20, vertical: 8 }),
        decoration: new BoxDecoration({
          color: "#eef2ff",
          borderRadius: BorderRadius.circular(8),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text("Traffic Source Breakdown", {
              style: new TextStyle({
                fontFamily: title.fontFamily ?? font.family,
                fontSize: title.fontSize,
                fontWeight: "700",
                color: "#4338ca",
              }),
            }),
            SizedBox({ height: 2 }),
            Text("12-month overview across all channels", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 11,
                color: "#6366f1",
              }),
            }),
          ],
        }),
      });
    },
  },
});`;
const _EnergyMixToastStackedArea_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  BorderRadius,
} from "flitter-ui";

const colors = ["#eab308", "#22c55e", "#64748b", "#a855f7"];
const icons = ["Solar", "Wind", "Gas", "Nuclear"];
const peakMonths = ["Jul", "Jan", "Jan", "Jun"];

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Solar", values: [120, 140, 180, 240, 310, 380, 400, 370, 290, 210, 150, 110] },
      { legend: "Wind", values: [280, 260, 240, 220, 200, 180, 170, 190, 230, 270, 290, 300] },
      { legend: "Gas", values: [350, 340, 310, 280, 250, 230, 220, 225, 260, 300, 330, 360] },
      { legend: "Nuclear", values: [400, 400, 395, 405, 400, 410, 405, 400, 398, 402, 400, 405] },
    ],
  },
  config: {
    colors,
    area: { opacity: 0.55, spline: true },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 10,
            height: 10,
            decoration: new BoxDecoration({
              color: colors[index],
              borderRadius: BorderRadius.circular(2),
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "#334155",
              fontWeight: "600",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(\`peak: \${peakMonths[index]}\`, {
            style: new TextStyle({
              fontSize: 9,
              color: "#94a3b8",
            }),
          }),
        ],
      }),
  },
});`;
const _RevenueStreamStackedArea_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Q1 '23", "Q2 '23", "Q3 '23", "Q4 '23", "Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24"],
    datasets: [
      { legend: "Subscriptions", values: [4200, 4500, 4800, 5100, 5500, 5900, 6300, 6800] },
      { legend: "Licensing", values: [1800, 1900, 2000, 2200, 2100, 2300, 2500, 2700] },
      { legend: "Services", values: [900, 1000, 1100, 1200, 1300, 1400, 1500, 1600] },
      { legend: "Hardware", values: [600, 550, 500, 700, 650, 600, 750, 800] },
    ],
  },
  config: {
    colors: ["#0d9488", "#d97706", "#ec4899", "#64748b"],
    area: { opacity: 0.4, strokeWidth: 1.5 },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const value = parseFloat(name);
      const formatted = value >= 1000 ? \`$\${(value / 1000).toFixed(0)}K\` : \`$\${value}\`;
      const isHigh = value >= 10000;
      return Text(formatted, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isHigh ? "bold" : "normal",
          color: isHigh ? "#0d9488" : "#64748b",
        }),
      });
    },
  },
});`;
const _SupportTicketsToastStackedArea_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
  Text,
  TextStyle,
} from "flitter-ui";

const summerMonths = ["Jun", "Jul", "Aug"];

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Bug Reports", values: [85, 78, 92, 88, 75, 70, 65, 72, 80, 68, 62, 58] },
      { legend: "Feature Requests", values: [45, 52, 48, 55, 60, 65, 70, 68, 72, 78, 82, 88] },
      { legend: "Questions", values: [120, 115, 108, 100, 95, 90, 88, 85, 82, 78, 75, 70] },
      { legend: "Billing", values: [30, 28, 32, 35, 30, 28, 25, 27, 30, 32, 28, 25] },
    ],
  },
  config: {
    colors: ["#ef4444", "#6366f1", "#06b6d4", "#f59e0b"],
    area: { opacity: 0.35 },
    title: { text: "Support Ticket Trends", visible: true },
  },
  custom: {
    xAxisLabel: ({ name }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const isSummer = summerMonths.includes(name);
      return Container({
        padding: isSummer ? EdgeInsets.symmetric({ horizontal: 4, vertical: 2 }) : undefined,
        decoration: isSummer
          ? new BoxDecoration({
              color: "#fef3c7",
              borderRadius: BorderRadius.circular(4),
            })
          : undefined,
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: 10,
            fontWeight: isSummer ? "bold" : "normal",
            color: isSummer ? "#b45309" : "#64748b",
          }),
        }),
      });
    },
  },
});`;
const _TrafficSourceStackedArea_code = `import ToastStackedAreaChart from "./charts/toast-stacked-area-chart";
import { Transform, Text, TextStyle, Alignment } from "flitter-ui";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    datasets: [
      { legend: "Search", values: [3200, 3400, 3600, 3900, 4100, 4300, 4500, 4200, 4600, 4800, 5000, 5200] },
      { legend: "Social Media", values: [800, 950, 1100, 1300, 1500, 1800, 2000, 2200, 1900, 1700, 1600, 1400] },
      { legend: "Email", values: [600, 580, 620, 650, 700, 680, 720, 710, 750, 780, 800, 820] },
      { legend: "Direct", values: [1200, 1250, 1300, 1280, 1350, 1400, 1380, 1420, 1450, 1500, 1520, 1550] },
    ],
  },
  config: {
    colors: ["#3b82f6", "#f97316", "#10b981", "#8b5cf6"],
    area: { opacity: 0.5 },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      return Transform.rotate({
        angle: -Math.PI / 6,
        alignment: Alignment.centerRight,
        child: Text(name.slice(0, 3), {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: 10,
            fontWeight: index % 3 === 0 ? "bold" : "normal",
            color: index % 3 === 0 ? "#1e40af" : "#94a3b8",
          }),
        }),
      });
    },
  },
});`;

export const DefaultToastStackedAreaChart = { Component: _DefaultToastStackedAreaChart, code: _DefaultToastStackedAreaChart_code };
export const TrafficSourceStackedArea = { Component: _TrafficSourceStackedArea, code: _TrafficSourceStackedArea_code };
export const RevenueStreamStackedArea = { Component: _RevenueStreamStackedArea, code: _RevenueStreamStackedArea_code };
export const EnergyMixToastStackedArea = { Component: _EnergyMixToastStackedArea, code: _EnergyMixToastStackedArea_code };
export const AppUsageToastStackedArea = { Component: _AppUsageToastStackedArea, code: _AppUsageToastStackedArea_code };
export const SupportTicketsToastStackedArea = { Component: _SupportTicketsToastStackedArea, code: _SupportTicketsToastStackedArea_code };
export const AcquisitionChannelsToast = { Component: _AcquisitionChannelsToast, code: _AcquisitionChannelsToast_code };
