// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _CustomerSegmentsAg from "./examples/customer-segments";
import _ExecutiveRevenueAg from "./examples/executive-revenue";
import _NegativePLAg from "./examples/negative-pl";
import _ProductComparisonAg from "./examples/product-comparison";
import _QuarterlyEarningsAg from "./examples/quarterly-earnings";
import _TopCountriesAg from "./examples/top-countries";
import _YearOverYearAg from "./examples/year-over-year";

const _CustomerSegmentsAg_code = `import BarChart from "./charts/bar-chart";
import { Container, BoxDecoration, EdgeInsets, BorderRadius, BoxShadow } from "flitter-ui";

const datasetColors = ["#10b981", "#3b82f6", "#ef4444"];

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Enterprise", "Mid-Market", "SMB", "Startup"],
    datasets: [
      { legend: "New ARR ($K)", values: [480, 320, 190, 85] },
      { legend: "Expansion ($K)", values: [210, 145, 70, 32] },
      { legend: "Churn ($K)", values: [-95, -68, -42, -28] },
    ],
  },
  config: {
    colors: { fills: datasetColors },
    bar: { cornerRadius: 4 },
    title: { text: "Customer Segments", visible: true },
  },
  custom: {
    bar: (
      { value, legend }: { value: number; label: string; legend: string; index: number },
      context: any,
    ) => {
      const idx = context.legends.indexOf(legend);
      const color = datasetColors[idx] ?? "#94a3b8";
      const isChurn = value < 0;
      return Container({
        margin: EdgeInsets.symmetric({ horizontal: 1 }),
        decoration: new BoxDecoration({
          color: color,
          borderRadius: BorderRadius.circular(4),
          boxShadow: isChurn
            ? [new BoxShadow({ color: "rgba(239,68,68,0.3)", blurRadius: 6 })]
            : [],
        }),
      });
    },
  },
});`;
const _ExecutiveRevenueAg_code = `import {
  Container,
  BoxDecoration,
  Border,
  BorderSide,
  EdgeInsets,
  Text,
  TextStyle,
  Column,
  Row,
  SizedBox,
  MainAxisSize,
  CrossAxisAlignment,
} from "flitter-ui";
import BarChart from "./charts/bar-chart";

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Product", values: [4.8, 5.2, 6.1] },
      { legend: "Services", values: [2.1, 2.4, 2.9] },
      { legend: "Licensing", values: [1.3, 1.1, 1.5] },
    ],
  },
  custom: {
    title: (
      _args: undefined,
      context: any,
    ) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.only({ bottom: 8 }),
        decoration: new BoxDecoration({
          border: new Border({
            bottom: new BorderSide({ color: "#2563eb", width: 2 }),
          }),
        }),
        child: Column({
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Row({
              mainAxisSize: MainAxisSize.min,
              children: [
                Text("Q4 ", {
                  style: new TextStyle({
                    fontFamily: title.fontFamily ?? font.family,
                    fontSize: title.fontSize,
                    fontWeight: "700",
                    color: title.color,
                  }),
                }),
                Text("Revenue", {
                  style: new TextStyle({
                    fontFamily: title.fontFamily ?? font.family,
                    fontSize: title.fontSize,
                    fontWeight: "700",
                    color: "#2563eb",
                  }),
                }),
              ],
            }),
            SizedBox({ height: 2 }),
            Text("Breakdown by stream ($M)", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 12,
                color: "#94a3b8",
              }),
            }),
          ],
        }),
      });
    },
  },
  config: {
    colors: { fills: ["#2563eb", "#7c3aed", "#e879f9"] },
    title: { text: "Q4 Revenue", visible: true },
    legend: { position: "right-top" },
    bar: { cornerRadius: 4 },
  },
});`;
const _NegativePLAg_code = `import BarChart from "./charts/bar-chart";

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    datasets: [
      {
        legend: "Monthly P&L ($K)",
        values: [120, -45, 85, -20, 150, -80, 65, 110],
      },
    ],
  },
  config: {
    colors: { fills: ["#6366f1"] },
    bar: { cornerRadius: 3 },
  },
});`;
const _ProductComparisonAg_code = `import {
  Transform,
  Text,
  TextStyle,
  Alignment,
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
} from "flitter-ui";
import BarChart from "./charts/bar-chart";

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Design", "Speed", "Support"],
    datasets: [
      { legend: "Ours", values: [92, 76, 88] },
      { legend: "Competitor A", values: [68, 91, 72] },
      { legend: "Competitor B", values: [79, 84, 65] },
    ],
  },
  custom: {
    xAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font, axis } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 8, vertical: 3 }),
        decoration: new BoxDecoration({
          color: "#f0f9ff",
          borderRadius: BorderRadius.circular(4),
        }),
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: axis.label.fontSize,
            color: "#0369a1",
          }),
        }),
      });
    },
  },
  config: {
    colors: { fills: ["#0ea5e9", "#f97316", "#8b5cf6"] },
    title: { text: "Product Comparison", visible: true },
    bar: { cornerRadius: 3 },
  },
});`;
const _QuarterlyEarningsAg_code = `import BarChart from "./charts/bar-chart";

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 2024", "Q2 2024", "Q3 2024", "Q4 2024"],
    datasets: [
      { legend: "Revenue", values: [28.5, 31.2, 29.8, 34.1] },
      { legend: "EBITDA", values: [8.4, 9.7, 8.9, 11.2] },
    ],
  },
  config: {
    colors: { fills: ["#2563eb", "#7c3aed"] },
    bar: { cornerRadius: 32 },
    padding: { top: 24, right: 24, bottom: 24, left: 24 },
  },
});`;
const _TopCountriesAg_code = `import BarChart from "./charts/bar-chart";
import { Text, TextStyle, Row, SizedBox, MainAxisSize } from "flitter-ui";

const flags: Record<string, string> = {
  "United States": "🇺🇸",
  China: "🇨🇳",
  Japan: "🇯🇵",
  Germany: "🇩🇪",
  India: "🇮🇳",
  "United Kingdom": "🇬🇧",
  France: "🇫🇷",
  Brazil: "🇧🇷",
  Canada: "🇨🇦",
  "South Korea": "🇰🇷",
};

const chart = BarChart({
  direction: "horizontal",
  data: {
    labels: [
      "United States",
      "China",
      "Japan",
      "Germany",
      "India",
      "United Kingdom",
      "France",
      "Brazil",
      "Canada",
      "South Korea",
    ],
    datasets: [
      {
        legend: "GDP (T$)",
        values: [25.5, 17.9, 4.2, 4.1, 3.7, 3.1, 2.8, 1.9, 1.8, 1.7],
      },
    ],
  },
  config: {
    colors: { fills: ["#0284c7"] },
    bar: { cornerRadius: 3 },
  },
  custom: {
    yAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const flag = flags[name] ?? "";
      return Row({
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(flag, {
            style: new TextStyle({ fontSize: 14 }),
          }),
          SizedBox({ width: 4 }),
          Text(name, {
            style: new TextStyle({
              fontFamily: font.family,
              fontSize: font.size,
              color: "#334155",
            }),
          }),
        ],
      });
    },
  },
});`;
const _YearOverYearAg_code = `import BarChart from "./charts/bar-chart";

const chart = BarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "2024", values: [340, 380, 420, 395, 450, 470] },
      { legend: "2025", values: [410, 445, 480, 460, 520, 540] },
    ],
  },
  config: {
    colors: { fills: ["#64748b", "#0d9488"] },
    bar: { cornerRadius: 4 },
    title: { text: "Year-over-Year Revenue", visible: true, position: "bottom" },
  },
});`;

export const QuarterlyEarningsAg = { Component: _QuarterlyEarningsAg, code: _QuarterlyEarningsAg_code };
export const ProductComparisonAg = { Component: _ProductComparisonAg, code: _ProductComparisonAg_code };
export const YearOverYearAg = { Component: _YearOverYearAg, code: _YearOverYearAg_code };
export const TopCountriesAg = { Component: _TopCountriesAg, code: _TopCountriesAg_code };
export const CustomerSegmentsAg = { Component: _CustomerSegmentsAg, code: _CustomerSegmentsAg_code };
export const NegativePLAg = { Component: _NegativePLAg, code: _NegativePLAg_code };
export const ExecutiveRevenueAg = { Component: _ExecutiveRevenueAg, code: _ExecutiveRevenueAg_code };
export const VerticalAgBarChart = { Component: _QuarterlyEarningsAg, code: _QuarterlyEarningsAg_code };
export const HorizontalAgBarChart = { Component: _TopCountriesAg, code: _TopCountriesAg_code };
export const NegativeVerticalAgBarChart = { Component: _NegativePLAg, code: _NegativePLAg_code };
export const NegativeHorizontalAgBarChart = { Component: _CustomerSegmentsAg, code: _CustomerSegmentsAg_code };
