// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _DarkAnalysisAgBubble from "./examples/dark-analysis";
import _DefaultAgBubbleChart from "./examples/default";
import _HealthMetricsAgBubble from "./examples/health-metrics";
import _ProjectPortfolioAgBubble from "./examples/project-portfolio";
import _SmallAgBubbleChart from "./examples/small-bubbles";
import _TechStackAgBubble from "./examples/tech-stack";

const _DarkAnalysisAgBubble_code = `import {
  Container,
  BoxDecoration,
  BoxShadow,
} from "flitter-ui";
import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Revenue",
        data: [
          { x: 15, y: 82, value: 920, label: "Q1 North" },
          { x: 28, y: 74, value: 1400, label: "Q2 North" },
          { x: 42, y: 91, value: 1850, label: "Q3 North" },
        ],
      },
      {
        legend: "Expenses",
        data: [
          { x: 12, y: 65, value: 680, label: "Q1 Ops" },
          { x: 25, y: 58, value: 1100, label: "Q2 Ops" },
          { x: 38, y: 70, value: 750, label: "Q3 Ops" },
        ],
      },
      {
        legend: "Profit",
        data: [
          { x: 20, y: 45, value: 240, label: "Q1 Net" },
          { x: 33, y: 52, value: 300, label: "Q2 Net" },
          { x: 45, y: 60, value: 1100, label: "Q3 Net" },
        ],
      },
    ],
  },
  custom: {
    bubble: (
      { value, legend }: any,
      context: any,
    ) => {
      const { colors, bubble: bubbleConfig } = context.config;
      const idx = context.legends.indexOf(legend);
      const fillColor = colors.fills[idx % colors.fills.length];
      const { scale } = context;
      const normValue = scale != null
        ? (value - scale.value.min) / (scale.value.max - scale.value.min || 1)
        : 0.5;
      const radius = bubbleConfig.minRadius + normValue * (bubbleConfig.maxRadius - bubbleConfig.minRadius);
      // Neon glow effect on dark background
      return Container({
        width: radius * 2,
        height: radius * 2,
        decoration: new BoxDecoration({
          color: \`\${fillColor}bb\`,
          shape: "circle",
          boxShadow: [
            new BoxShadow({ color: \`\${fillColor}88\`, blurRadius: 16 }),
            new BoxShadow({ color: \`\${fillColor}44\`, blurRadius: 32 }),
          ],
        }),
      });
    },
  },
  config: {
    title: { text: "Quarterly Analysis", visible: true, color: "#e2e8f0" },
    subtitle: { visible: true, text: "Revenue vs Expenses vs Profit", color: "#64748b" },
    background: "#0f172a",
    bubble: { minRadius: 8, maxRadius: 40, opacity: 0.7 },
    colors: {
      fills: ["#38bdf8", "#f472b6", "#a3e635"],
      strokes: ["#38bdf8", "#f472b6", "#a3e635"],
    },
    axis: {
      color: "#94a3b8",
      label: { color: "#94a3b8" },
    },
    legend: { color: "#94a3b8" },
    grid: { color: "#1e293b", dash: [3, 3] },
  },
});`;
const _DefaultAgBubbleChart_code = `import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, value: 32209101, label: "Morocco" },
          { x: 4200, y: 70.71, value: 76117421, label: "Egypt" },
          { x: 5900, y: 56.46, value: 1355246, label: "Gabon" },
          { x: 6600, y: 72.74, value: 32129324, label: "Algeria" },
          { x: 7100, y: 74.66, value: 9974722, label: "Tunisia" },
          { x: 12800, y: 72.09, value: 1220481, label: "Mauritius" },
          { x: 18200, y: 78.68, value: 396851, label: "Malta" },
        ],
      },
      {
        legend: "America",
        data: [
          { x: 4800, y: 74.64, value: 6191368, label: "Paraguay" },
          { x: 5600, y: 69.22, value: 2754430, label: "Peru" },
          { x: 6600, y: 71.43, value: 4231077, label: "Colombia" },
          { x: 8100, y: 71.41, value: 78410118, label: "Brazil" },
          { x: 9600, y: 74.94, value: 4495959, label: "Mexico" },
          { x: 12400, y: 75.7, value: 6914475, label: "Argentina" },
          { x: 31500, y: 79.96, value: 32507874, label: "Canada" },
          { x: 32100, y: 77.43, value: 89302754, label: "United States" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, value: 92988000, label: "China" },
          { x: 8100, y: 71.41, value: 14865523, label: "Thailand" },
          { x: 9700, y: 71.95, value: 23522482, label: "Malaysia" },
          { x: 12000, y: 75.23, value: 25795938, label: "Saudi Arabia" },
          { x: 19200, y: 75.58, value: 48598170, label: "Korea, South" },
          { x: 25300, y: 77.06, value: 22749838, label: "Taiwan" },
          { x: 27800, y: 81.53, value: 4353893, label: "Singapore" },
          { x: 29400, y: 81.04, value: 52733300, label: "Japan" },
          { x: 34200, y: 81.39, value: 6855125, label: "Hong Kong" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 9800, y: 66.39, value: 54378233, label: "Russia" },
          { x: 12000, y: 74.16, value: 38626349, label: "Poland" },
          { x: 23300, y: 79.37, value: 40280780, label: "Spain" },
          { x: 27700, y: 79.54, value: 58057477, label: "Italy" },
          { x: 28700, y: 78.54, value: 22424609, label: "Germany" },
          { x: 28700, y: 79.44, value: 30424213, label: "France" },
          { x: 29600, y: 78.27, value: 60270708, label: "United Kingdom" },
          { x: 33800, y: 80.31, value: 7450867, label: "Switzerland" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 2200, y: 64.56, value: 5420280, label: "Papua New Guinea" },
          { x: 5900, y: 69.2, value: 880874, label: "Fiji" },
          { x: 23200, y: 78.49, value: 1993817, label: "New Zealand" },
          { x: 30700, y: 80.26, value: 5991314, label: "Australia" },
        ],
      },
    ],
  },
  config: {
    title: { text: "World Development Overview", visible: true },
    subtitle: { visible: true, text: "GDP per capita vs life expectancy, sized by population" },
    axis: {
      label: {
        format: (name: string, _index: number, axis: string) => {
          const n = Number(name);
          if (axis === "x") return n >= 1000 ? \`$\${(n / 1000).toFixed(0)}K\` : \`$\${n}\`;
          return \`\${n} yrs\`;
        },
      },
    },
  },
});`;
const _HealthMetricsAgBubble_code = `import {
  Text,
  TextStyle,
} from "flitter-ui";
import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Age 20-35",
        data: [
          { x: 22, y: 118, value: 15000, label: "Active" },
          { x: 25, y: 125, value: 22000, label: "Moderate" },
          { x: 28, y: 130, value: 8000, label: "Sedentary" },
        ],
      },
      {
        legend: "Age 36-50",
        data: [
          { x: 24, y: 122, value: 12000, label: "Active" },
          { x: 27, y: 132, value: 25000, label: "Moderate" },
          { x: 31, y: 140, value: 18000, label: "Sedentary" },
        ],
      },
      {
        legend: "Age 51-65",
        data: [
          { x: 26, y: 128, value: 8000, label: "Active" },
          { x: 30, y: 138, value: 20000, label: "Moderate" },
          { x: 34, y: 148, value: 15000, label: "Sedentary" },
        ],
      },
    ],
  },
  custom: {
    yAxisLabel: ({ name }: any) => {
      const bp = Number(name);
      // Color-coded blood pressure thresholds
      const color = bp >= 140 ? "#dc2626" : bp >= 130 ? "#f59e0b" : "#059669";
      const label = bp >= 140 ? "High" : bp >= 130 ? "Elevated" : "";
      return Text(label ? \`\${name} \${label}\` : name, {
        style: new TextStyle({
          fontSize: 11,
          color,
          fontWeight: bp >= 140 ? "bold" : "normal",
        }),
      });
    },
  },
  config: {
    title: { text: "Health Metrics by Age Group", visible: true },
    subtitle: { visible: true, text: "BMI vs blood pressure, bubble = group size" },
    bubble: { opacity: 0.5, minRadius: 8, maxRadius: 28 },
    colors: {
      fills: ["#ef4444", "#3b82f6", "#10b981"],
      strokes: ["#ef4444", "#3b82f6", "#10b981"],
    },
  },
});`;
const _ProjectPortfolioAgBubble_code = `import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Conservative",
        data: [
          { x: 2, y: 5, value: 500000, label: "Gov Bonds" },
          { x: 3, y: 6, value: 300000, label: "Blue Chip" },
          { x: 1, y: 4, value: 800000, label: "Treasury" },
          { x: 4, y: 7, value: 200000, label: "Corp Bonds" },
        ],
      },
      {
        legend: "Balanced",
        data: [
          { x: 5, y: 10, value: 400000, label: "Index Fund" },
          { x: 6, y: 12, value: 350000, label: "REITs" },
          { x: 4, y: 8, value: 600000, label: "Growth ETF" },
          { x: 7, y: 14, value: 250000, label: "Dividend" },
        ],
      },
      {
        legend: "Aggressive",
        data: [
          { x: 9, y: 22, value: 150000, label: "Tech Startup" },
          { x: 8, y: 18, value: 280000, label: "Emerging Mkt" },
          { x: 10, y: 25, value: 100000, label: "Crypto Fund" },
          { x: 7, y: 15, value: 320000, label: "Small Cap" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Investment Portfolio", visible: true },
    subtitle: { visible: true, text: "Risk vs return, sized by allocation" },
    bubble: { minRadius: 4, maxRadius: 35, opacity: 0.55 },
    colors: {
      fills: ["#059669", "#dc2626", "#6366f1"],
      strokes: ["#059669", "#dc2626", "#6366f1"],
    },
    background: "#f8fafc",
    axis: {
      label: {
        format: (name: string, _index: number, axis: string) => {
          if (axis === "x") return \`Risk \${name}\`;
          return \`\${name}%\`;
        },
      },
    },
  },
});`;
const _SmallAgBubbleChart_code = `import {
  Container,
  BoxDecoration,
  EdgeInsets,
  BorderRadius,
  Text,
  TextStyle,
  Row,
  SizedBox,
  MainAxisSize,
  CrossAxisAlignment,
} from "flitter-ui";
import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, value: 32209101, label: "Morocco" },
          { x: 6600, y: 72.74, value: 32129324, label: "Algeria" },
          { x: 7100, y: 74.66, value: 9974722, label: "Tunisia" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, value: 92988000, label: "China" },
          { x: 19200, y: 75.58, value: 48598170, label: "Korea, South" },
          { x: 29400, y: 81.04, value: 52733300, label: "Japan" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 27700, y: 79.54, value: 58057477, label: "Italy" },
          { x: 28700, y: 78.54, value: 22424609, label: "Germany" },
          { x: 29600, y: 78.27, value: 60270708, label: "United Kingdom" },
        ],
      },
    ],
  },
  custom: {
    legend: ({ name, index }: any, context: any) => {
      const color = context.config.colors.fills[index % context.config.colors.fills.length];
      // Pill-shaped legend with count badge
      const dataset = context.data.datasets[index];
      const count = dataset?.data?.length ?? 0;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 8, vertical: 3 }),
        decoration: new BoxDecoration({
          color: "white",
          borderRadius: BorderRadius.circular(10),
        }),
        child: Row({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Container({
              width: 8,
              height: 8,
              decoration: new BoxDecoration({ color, shape: "circle" }),
            }),
            SizedBox({ width: 5 }),
            Text(name, {
              style: new TextStyle({ fontSize: 11, color: "#333" }),
            }),
            SizedBox({ width: 4 }),
            Container({
              padding: EdgeInsets.symmetric({ horizontal: 5, vertical: 1 }),
              decoration: new BoxDecoration({
                color: \`\${color}22\`,
                borderRadius: BorderRadius.circular(8),
              }),
              child: Text(\`\${count}\`, {
                style: new TextStyle({ fontSize: 9, color, fontWeight: "bold" }),
              }),
            }),
          ],
        }),
      });
    },
  },
  config: {
    title: { text: "Tight Radius Range", visible: true },
    subtitle: { visible: true, text: "Custom legend with data-point count badges" },
    bubble: { minRadius: 2, maxRadius: 20, opacity: 0.8 },
    colors: {
      fills: ["#7c3aed", "#06b6d4", "#f97316"],
      strokes: ["#7c3aed", "#06b6d4", "#f97316"],
    },
  },
});`;
const _TechStackAgBubble_code = `import {
  Container,
  BoxDecoration,
  EdgeInsets,
  BorderRadius,
  Text,
  TextStyle,
  Row,
  SizedBox,
  MainAxisSize,
  CrossAxisAlignment,
} from "flitter-ui";
import BubbleChart from "./charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Frontend",
        data: [
          { x: 85, y: 4.5, value: 45000, label: "React" },
          { x: 72, y: 4.7, value: 28000, label: "Vue" },
          { x: 60, y: 4.6, value: 22000, label: "Svelte" },
          { x: 40, y: 4.2, value: 15000, label: "Angular" },
          { x: 30, y: 4.8, value: 8000, label: "Solid" },
        ],
      },
      {
        legend: "Backend",
        data: [
          { x: 78, y: 4.3, value: 52000, label: "Node.js" },
          { x: 55, y: 4.4, value: 38000, label: "Go" },
          { x: 65, y: 4.6, value: 42000, label: "Python" },
          { x: 45, y: 4.5, value: 30000, label: "Rust" },
        ],
      },
      {
        legend: "Database",
        data: [
          { x: 90, y: 4.0, value: 60000, label: "PostgreSQL" },
          { x: 70, y: 4.2, value: 35000, label: "MongoDB" },
          { x: 50, y: 4.4, value: 18000, label: "Redis" },
          { x: 35, y: 4.3, value: 12000, label: "Cassandra" },
        ],
      },
    ],
  },
  custom: {
    xAxisLabel: ({ name }: any) => {
      const adoption = Number(name);
      // Mini bar indicator showing adoption level
      return Row({
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Text(\`\${name}%\`, {
            style: new TextStyle({
              fontSize: 11,
              color: "#585858",
            }),
          }),
          SizedBox({ width: 3 }),
          Container({
            width: Math.max(2, adoption / 5),
            height: 4,
            decoration: new BoxDecoration({
              color: adoption >= 70 ? "#10b981" : adoption >= 40 ? "#f59e0b" : "#94a3b8",
              borderRadius: BorderRadius.circular(2),
            }),
          }),
        ],
      });
    },
  },
  config: {
    title: { text: "Tech Stack Landscape 2025", visible: true },
    subtitle: { visible: true, text: "Adoption vs satisfaction, bubble = job openings" },
    bubble: { minRadius: 5, maxRadius: 30, opacity: 0.6 },
    colors: {
      fills: ["#3b82f6", "#10b981", "#f59e0b"],
      strokes: ["#3b82f6", "#10b981", "#f59e0b"],
    },
    grid: { dash: [4, 4] },
  },
});`;

export const DefaultAgBubbleChart = { Component: _DefaultAgBubbleChart, code: _DefaultAgBubbleChart_code };
export const SmallAgBubbleChart = { Component: _SmallAgBubbleChart, code: _SmallAgBubbleChart_code };
export const TechStackAgBubble = { Component: _TechStackAgBubble, code: _TechStackAgBubble_code };
export const ProjectPortfolioAgBubble = { Component: _ProjectPortfolioAgBubble, code: _ProjectPortfolioAgBubble_code };
export const HealthMetricsAgBubble = { Component: _HealthMetricsAgBubble, code: _HealthMetricsAgBubble_code };
export const DarkAnalysisAgBubble = { Component: _DarkAnalysisAgBubble, code: _DarkAnalysisAgBubble_code };
