// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _CloudCostAgStackedArea from "./examples/cloud-cost";
import _DefaultAgStackedAreaChart from "./examples/default-ag-stacked-area";
import _MarketShareAgStackedArea from "./examples/market-share";
import _ResourceAllocationStackedArea from "./examples/resource-allocation";
import _RevenueStreamsMinimalAg from "./examples/revenue-streams-minimal";
import _TeamVelocityAgStackedArea from "./examples/team-velocity";

const _CloudCostAgStackedArea_code = `import StackedAreaChart from "./charts/stacked-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Compute", values: [4200, 4400, 4600, 4800, 5100, 5400, 5700, 5500, 5800, 6000, 6300, 6600] },
      { legend: "Storage", values: [1800, 1900, 2000, 2100, 2200, 2350, 2500, 2600, 2750, 2900, 3050, 3200] },
      { legend: "Network", values: [900, 950, 1000, 1050, 1100, 1200, 1300, 1250, 1350, 1400, 1500, 1600] },
      { legend: "Database", values: [1500, 1550, 1600, 1650, 1700, 1800, 1900, 1950, 2000, 2100, 2200, 2300] },
    ],
  },
  config: {
    colors: { fills: ["#0ea5e9", "#f97316", "#8b5cf6", "#10b981"], strokes: ["#0ea5e9", "#f97316", "#8b5cf6", "#10b981"] },
    area: { opacity: 0.45 },
    grid: { dash: [4, 4] },
    title: { text: "Cloud Infrastructure Costs", visible: true },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const value = parseFloat(name);
      const formatted = value >= 1000 ? \`$\${(value / 1000).toFixed(0)}K\` : \`$\${value}\`;
      const isBudgetAlert = value >= 12000;
      return Text(formatted, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isBudgetAlert ? "bold" : "normal",
          color: isBudgetAlert ? "#dc2626" : "#585858",
        }),
      });
    },
  },
});`;
const _DefaultAgStackedAreaChart_code = `import StackedAreaChart from "./charts/stacked-area-chart";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Organic", values: [400, 450, 420, 480, 520, 510, 550, 530, 560, 600, 620, 650] },
      { legend: "Direct", values: [200, 220, 210, 230, 250, 240, 260, 255, 270, 290, 300, 310] },
      { legend: "Social", values: [100, 120, 130, 140, 160, 155, 170, 165, 180, 200, 210, 220] },
      { legend: "Referral", values: [50, 60, 55, 65, 70, 75, 80, 78, 85, 90, 95, 100] },
    ],
  },
  config: {
    title: { text: "Revenue Stream Composition", visible: true, alignment: "center" },
    subtitle: { visible: true, text: "Monthly breakdown by acquisition channel" },
    area: { opacity: 0.6 },
    background: "#fafafa",
  },
});`;
const _MarketShareAgStackedArea_code = `import StackedAreaChart from "./charts/stacked-area-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
  Text,
  TextStyle,
} from "flitter-ui";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Chrome", values: [64, 63.8, 63.5, 63.2, 63, 62.8, 62.5, 62.3, 62, 61.8, 61.5, 61.2] },
      { legend: "Safari", values: [19, 19.2, 19.5, 19.8, 20, 20.3, 20.5, 20.8, 21, 21.3, 21.5, 21.8] },
      { legend: "Firefox", values: [8, 7.9, 7.8, 7.7, 7.6, 7.5, 7.4, 7.3, 7.2, 7.1, 7, 6.9] },
      { legend: "Edge", values: [5, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6, 6.1] },
    ],
  },
  config: {
    colors: { fills: ["#ef4444", "#3b82f6", "#f59e0b", "#10b981"], strokes: ["#ef4444", "#3b82f6", "#f59e0b", "#10b981"] },
    area: { opacity: 0.6 },
    background: "#fafafa",
    title: { text: "Browser Market Share", visible: true },
    axis: {
      label: {
        format: (name: string, _index: number, axis: string) =>
          axis === "y" ? \`\${name}%\` : name,
      },
    },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const isQuarterStart = index % 3 === 0;
      return Container({
        padding: isQuarterStart ? EdgeInsets.symmetric({ horizontal: 4, vertical: 1 }) : undefined,
        decoration: isQuarterStart
          ? new BoxDecoration({
              color: "#f1f5f9",
              borderRadius: BorderRadius.circular(3),
            })
          : undefined,
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: isQuarterStart ? 12 : 11,
            fontWeight: isQuarterStart ? "bold" : "normal",
            color: isQuarterStart ? "#1e293b" : "#94a3b8",
          }),
        }),
      });
    },
  },
});`;
const _ResourceAllocationStackedArea_code = `import StackedAreaChart from "./charts/stacked-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = StackedAreaChart({
  data: {
    labels: ["Sprint 1", "Sprint 2", "Sprint 3", "Sprint 4", "Sprint 5", "Sprint 6", "Sprint 7", "Sprint 8"],
    datasets: [
      { legend: "Development", values: [45, 50, 48, 52, 55, 50, 53, 56] },
      { legend: "QA", values: [15, 18, 20, 22, 20, 25, 22, 24] },
      { legend: "Design", values: [12, 10, 8, 10, 12, 8, 10, 8] },
      { legend: "DevOps", values: [8, 10, 12, 10, 8, 12, 10, 12] },
    ],
  },
  config: {
    colors: { fills: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"], strokes: ["#3b82f6", "#10b981", "#f59e0b", "#ef4444"] },
    area: { opacity: 0.5 },
    title: { text: "Resource Allocation", visible: true },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const value = parseFloat(name);
      const isOverCapacity = value >= 80;
      return Text(\`\${name} hrs\`, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isOverCapacity ? "bold" : "normal",
          color: isOverCapacity ? "#dc2626" : "#585858",
        }),
      });
    },
  },
});`;
const _RevenueStreamsMinimalAg_code = `import StackedAreaChart from "./charts/stacked-area-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  CrossAxisAlignment,
  SizedBox,
} from "flitter-ui";

const chart = StackedAreaChart({
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25"],
    datasets: [
      { legend: "SaaS", values: [3200, 3600, 4100, 4500, 5000, 5400] },
      { legend: "Services", values: [1400, 1500, 1350, 1600, 1700, 1550] },
      { legend: "Licensing", values: [800, 850, 900, 950, 1000, 1050] },
    ],
  },
  config: {
    colors: { fills: ["#4f46e5", "#0891b2", "#ca8a04"], strokes: ["#4f46e5", "#0891b2", "#ca8a04"] },
    area: { opacity: 0.4 },
    axis: { xLine: { visible: false } },
    background: "#fafafa",
    grid: { dash: [3, 3], color: "#e5e5e5" },
    title: { text: "Revenue Streams", visible: true },
  },
  custom: {
    title: (_args: undefined, context: any) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 14, vertical: 5 }),
        decoration: new BoxDecoration({
          color: "#eef2ff",
          borderRadius: BorderRadius.circular(20),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text("Revenue Streams", {
              style: new TextStyle({
                fontFamily: title.fontFamily ?? font.family,
                fontSize: 14,
                fontWeight: "600",
                color: "#4338ca",
              }),
            }),
            SizedBox({ height: 1 }),
            Text("6 quarters  |  3 segments", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 10,
                color: "#818cf8",
              }),
            }),
          ],
        }),
      });
    },
  },
});`;
const _TeamVelocityAgStackedArea_code = `import StackedAreaChart from "./charts/stacked-area-chart";

const chart = StackedAreaChart({
  data: {
    labels: ["Sprint 1", "Sprint 2", "Sprint 3", "Sprint 4", "Sprint 5", "Sprint 6", "Sprint 7", "Sprint 8", "Sprint 9", "Sprint 10"],
    datasets: [
      { legend: "Frontend", values: [28, 32, 30, 35, 38, 36, 40, 42, 38, 44] },
      { legend: "Backend", values: [35, 38, 40, 42, 45, 43, 48, 46, 50, 52] },
      { legend: "Mobile", values: [18, 20, 22, 24, 26, 25, 28, 30, 32, 34] },
    ],
  },
  config: {
    colors: { fills: ["#6366f1", "#ec4899", "#f59e0b"], strokes: ["#6366f1", "#ec4899", "#f59e0b"] },
    area: { opacity: 0.55, spline: true, strokeWidth: 1.5 },
    title: { text: "Team Velocity", visible: true },
    axis: {
      label: {
        format: (name: string, _index: number, axis: string) =>
          axis === "y" ? \`\${name} pts\` : name.replace("Sprint ", "S"),
      },
    },
  },
});`;

export const DefaultAgStackedAreaChart = { Component: _DefaultAgStackedAreaChart, code: _DefaultAgStackedAreaChart_code };
export const ResourceAllocationStackedArea = { Component: _ResourceAllocationStackedArea, code: _ResourceAllocationStackedArea_code };
export const CloudCostAgStackedArea = { Component: _CloudCostAgStackedArea, code: _CloudCostAgStackedArea_code };
export const TeamVelocityAgStackedArea = { Component: _TeamVelocityAgStackedArea, code: _TeamVelocityAgStackedArea_code };
export const MarketShareAgStackedArea = { Component: _MarketShareAgStackedArea, code: _MarketShareAgStackedArea_code };
export const RevenueStreamsMinimalAg = { Component: _RevenueStreamsMinimalAg, code: _RevenueStreamsMinimalAg_code };
