// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _CityComparisonToastBubble from "./examples/city-comparison";
import _DefaultToastBubbleChart from "./examples/default";
import _HighOpacityToastBubbleChart from "./examples/high-opacity";
import _MarketAnalysisToastBubble from "./examples/market-analysis";
import _MarketOpportunityToastBubble from "./examples/market-opportunity";
import _SmallBubblestoastBubbleChart from "./examples/small-bubbles";
import _StartupFundingToastBubble from "./examples/startup-funding";

const _CityComparisonToastBubble_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "North America",
        data: [
          { x: 82, y: 7.8, value: 8300000, label: "New York" },
          { x: 75, y: 7.5, value: 3900000, label: "Los Angeles" },
          { x: 70, y: 8.1, value: 2700000, label: "Toronto" },
          { x: 78, y: 8.3, value: 680000, label: "San Francisco" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 88, y: 8.5, value: 9000000, label: "London" },
          { x: 76, y: 8.8, value: 2200000, label: "Paris" },
          { x: 72, y: 8.2, value: 3600000, label: "Berlin" },
          { x: 85, y: 8.9, value: 1400000, label: "Zurich" },
        ],
      },
      {
        legend: "Asia Pacific",
        data: [
          { x: 95, y: 7.6, value: 13960000, label: "Tokyo" },
          { x: 55, y: 7.0, value: 7500000, label: "Bangkok" },
          { x: 90, y: 8.0, value: 5450000, label: "Singapore" },
        ],
      },
    ],
  },
  config: {
    bubble: { minRadius: 10, maxRadius: 55, opacity: 0.65 },
    colors: ["#6366f1", "#ec4899", "#06b6d4"],
  },
});`;
const _DefaultToastBubbleChart_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, value: 32209101, label: "Morocco" },
          { x: 4200, y: 70.71, value: 76117421, label: "Egypt" },
          { x: 5900, y: 56.46, value: 1355246, label: "Gabon" },
          { x: 6600, y: 72.74, value: 32129324, label: "Algeria" },
          { x: 7100, y: 74.66, value: 9974722, label: "Tunisia" },
          { x: 12800, y: 72.09, value: 1220481, label: "Mauritius" },
          { x: 18200, y: 78.68, value: 396851, label: "Malta" },
        ],
      },
      {
        legend: "America",
        data: [
          { x: 4800, y: 74.64, value: 6191368, label: "Paraguay" },
          { x: 5600, y: 69.22, value: 2754430, label: "Peru" },
          { x: 6600, y: 71.43, value: 4231077, label: "Colombia" },
          { x: 8100, y: 71.41, value: 78410118, label: "Brazil" },
          { x: 9600, y: 74.94, value: 4495959, label: "Mexico" },
          { x: 12400, y: 75.7, value: 6914475, label: "Argentina" },
          { x: 31500, y: 79.96, value: 32507874, label: "Canada" },
          { x: 32100, y: 77.43, value: 89302754, label: "United States" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, value: 92988000, label: "China" },
          { x: 8100, y: 71.41, value: 14865523, label: "Thailand" },
          { x: 9700, y: 71.95, value: 23522482, label: "Malaysia" },
          { x: 12000, y: 75.23, value: 25795938, label: "Saudi Arabia" },
          { x: 19200, y: 75.58, value: 48598170, label: "Korea, South" },
          { x: 25300, y: 77.06, value: 22749838, label: "Taiwan" },
          { x: 27800, y: 81.53, value: 4353893, label: "Singapore" },
          { x: 29400, y: 81.04, value: 52733300, label: "Japan" },
          { x: 34200, y: 81.39, value: 6855125, label: "Hong Kong" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 9800, y: 66.39, value: 54378233, label: "Russia" },
          { x: 12000, y: 74.16, value: 38626349, label: "Poland" },
          { x: 23300, y: 79.37, value: 40280780, label: "Spain" },
          { x: 27700, y: 79.54, value: 58057477, label: "Italy" },
          { x: 28700, y: 78.54, value: 22424609, label: "Germany" },
          { x: 28700, y: 79.44, value: 30424213, label: "France" },
          { x: 29600, y: 78.27, value: 60270708, label: "United Kingdom" },
          { x: 33800, y: 80.31, value: 7450867, label: "Switzerland" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 2200, y: 64.56, value: 5420280, label: "Papua New Guinea" },
          { x: 5900, y: 69.2, value: 880874, label: "Fiji" },
          { x: 23200, y: 78.49, value: 1993817, label: "New Zealand" },
          { x: 30700, y: 80.26, value: 5991314, label: "Australia" },
        ],
      },
    ],
  },
  config: {},
});`;
const _HighOpacityToastBubbleChart_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Europe",
        data: [
          { x: 23300, y: 79.37, value: 40280780, label: "Spain" },
          { x: 27700, y: 79.54, value: 58057477, label: "Italy" },
          { x: 28700, y: 78.54, value: 22424609, label: "Germany" },
          { x: 28700, y: 79.44, value: 30424213, label: "France" },
          { x: 29600, y: 78.27, value: 60270708, label: "United Kingdom" },
          { x: 33800, y: 80.31, value: 7450867, label: "Switzerland" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 19200, y: 75.58, value: 48598170, label: "Korea, South" },
          { x: 25300, y: 77.06, value: 22749838, label: "Taiwan" },
          { x: 27800, y: 81.53, value: 4353893, label: "Singapore" },
          { x: 29400, y: 81.04, value: 52733300, label: "Japan" },
        ],
      },
    ],
  },
  config: {
    bubble: { opacity: 1.0 },
    colors: ["#dc2626", "#2563eb", "#059669", "#7c3aed", "#d97706"],
  },
});`;
const _MarketAnalysisToastBubble_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Technology",
        data: [
          { x: 120, y: 18, value: 850, label: "Cloud Services" },
          { x: 85, y: 25, value: 620, label: "AI/ML" },
          { x: 200, y: 8, value: 1200, label: "Enterprise Software" },
          { x: 45, y: 35, value: 300, label: "Cybersecurity" },
        ],
      },
      {
        legend: "Healthcare",
        data: [
          { x: 90, y: 12, value: 950, label: "Pharmaceuticals" },
          { x: 60, y: 22, value: 400, label: "Biotech" },
          { x: 150, y: 6, value: 1100, label: "Medical Devices" },
        ],
      },
      {
        legend: "Finance",
        data: [
          { x: 180, y: 5, value: 1500, label: "Banking" },
          { x: 70, y: 28, value: 350, label: "Fintech" },
          { x: 110, y: 10, value: 700, label: "Insurance" },
          { x: 40, y: 40, value: 200, label: "Crypto" },
        ],
      },
      {
        legend: "Energy",
        data: [
          { x: 250, y: 3, value: 2000, label: "Oil & Gas" },
          { x: 30, y: 45, value: 180, label: "Solar" },
          { x: 55, y: 30, value: 280, label: "Wind" },
        ],
      },
    ],
  },
  config: {
    bubble: { minRadius: 8, maxRadius: 45, opacity: 0.5 },
    colors: ["#0ea5e9", "#f97316", "#8b5cf6", "#10b981"],
  },
});`;
const _MarketOpportunityToastBubble_code = `import {
  Container,
  BoxDecoration,
  EdgeInsets,
  Text,
  TextStyle,
  BorderRadius,
} from "flitter-ui";
import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Enterprise",
        data: [
          { x: 520, y: 12, value: 4800, label: "ERP Systems" },
          { x: 340, y: 18, value: 3200, label: "CRM Platforms" },
          { x: 180, y: 25, value: 1500, label: "HR Tech" },
        ],
      },
      {
        legend: "Consumer",
        data: [
          { x: 680, y: 8, value: 6200, label: "E-commerce" },
          { x: 420, y: 22, value: 2800, label: "Streaming" },
          { x: 150, y: 35, value: 900, label: "EdTech" },
        ],
      },
      {
        legend: "Infrastructure",
        data: [
          { x: 290, y: 15, value: 5500, label: "Cloud Infra" },
          { x: 110, y: 40, value: 1200, label: "Edge Computing" },
          { x: 200, y: 20, value: 2100, label: "DevOps Tools" },
        ],
      },
    ],
  },
  custom: {
    dataLabel: ({ label }: { label?: string }) =>
      Container({
        padding: EdgeInsets.symmetric({ horizontal: 4, vertical: 1 }),
        decoration: new BoxDecoration({
          color: "rgba(255, 255, 255, 0.85)",
          borderRadius: BorderRadius.circular(3),
        }),
        child: Text(label ?? "", {
          style: new TextStyle({
            fontSize: 9,
            color: "#334155",
            fontWeight: "600",
          }),
        }),
      }),
  },
  config: {
    title: { text: "Market Sizing", visible: true },
    legend: { position: "right-center" },
    bubble: { minRadius: 10, maxRadius: 50, opacity: 0.55 },
    colors: ["#1e40af", "#9333ea", "#0891b2"],
  },
});`;
const _SmallBubblestoastBubbleChart_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, value: 32209101, label: "Morocco" },
          { x: 6600, y: 72.74, value: 32129324, label: "Algeria" },
          { x: 7100, y: 74.66, value: 9974722, label: "Tunisia" },
        ],
      },
      {
        legend: "America",
        data: [
          { x: 8100, y: 71.41, value: 78410118, label: "Brazil" },
          { x: 31500, y: 79.96, value: 32507874, label: "Canada" },
          { x: 32100, y: 77.43, value: 89302754, label: "United States" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, value: 92988000, label: "China" },
          { x: 19200, y: 75.58, value: 48598170, label: "Korea, South" },
          { x: 29400, y: 81.04, value: 52733300, label: "Japan" },
        ],
      },
    ],
  },
  config: {
    bubble: { minRadius: 3, maxRadius: 25, opacity: 0.8 },
    colors: ["#6366f1", "#ec4899", "#f59e0b", "#10b981", "#3b82f6"],
  },
});`;
const _StartupFundingToastBubble_code = `import ToastBubbleChart from "./charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "SaaS",
        data: [
          { x: 1, y: 8, value: 25, label: "Seed - TaskFlow" },
          { x: 2, y: 45, value: 80, label: "Series A - DataSync" },
          { x: 3, y: 180, value: 250, label: "Series B - CloudPeak" },
          { x: 4, y: 500, value: 600, label: "Series C - MetricHub" },
        ],
      },
      {
        legend: "Biotech",
        data: [
          { x: 1, y: 12, value: 15, label: "Seed - GeneCure" },
          { x: 2, y: 80, value: 45, label: "Series A - BioNova" },
          { x: 3, y: 350, value: 120, label: "Series B - MediGen" },
          { x: 4, y: 900, value: 300, label: "Series C - NeuroPath" },
        ],
      },
      {
        legend: "Clean Energy",
        data: [
          { x: 1, y: 5, value: 10, label: "Seed - SolarFlux" },
          { x: 2, y: 30, value: 55, label: "Series A - WindCore" },
          { x: 3, y: 120, value: 180, label: "Series B - HydroGen" },
          { x: 4, y: 400, value: 450, label: "Series C - FusionTech" },
        ],
      },
    ],
  },
  config: {
    bubble: { minRadius: 6, maxRadius: 40, opacity: 0.45 },
    colors: ["#10b981", "#f59e0b", "#ef4444"],
  },
});`;

export const DefaultToastBubbleChart = { Component: _DefaultToastBubbleChart, code: _DefaultToastBubbleChart_code };
export const SmallBubblestoastBubbleChart = { Component: _SmallBubblestoastBubbleChart, code: _SmallBubblestoastBubbleChart_code };
export const HighOpacityToastBubbleChart = { Component: _HighOpacityToastBubbleChart, code: _HighOpacityToastBubbleChart_code };
export const MarketAnalysisToastBubble = { Component: _MarketAnalysisToastBubble, code: _MarketAnalysisToastBubble_code };
export const CityComparisonToastBubble = { Component: _CityComparisonToastBubble, code: _CityComparisonToastBubble_code };
export const StartupFundingToastBubble = { Component: _StartupFundingToastBubble, code: _StartupFundingToastBubble_code };
export const MarketOpportunityToastBubble = { Component: _MarketOpportunityToastBubble, code: _MarketOpportunityToastBubble_code };
