// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BasicPieChart from "./examples/basic-pie-chart";
import _BudgetDonutDashboardPie from "./examples/budget-donut-dashboard-pie";
import _DevicePie from "./examples/device-pie";
import _DonutPieChart from "./examples/donut-pie-chart";
import _EnergyMixPie from "./examples/energy-mix-pie";
import _ExpenseBreakdownPieChart from "./examples/expense-breakdown-pie-chart";
import _MarketSharePieChart from "./examples/market-share-pie-chart";
import _ProgrammingLanguagePie from "./examples/programming-language-pie";
import _RevenueByRegionPie from "./examples/revenue-by-region-pie";
import _TimeAllocationPie from "./examples/time-allocation-pie";
import _TrafficSourcePie from "./examples/traffic-source-pie";

const _BasicPieChart_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {},
});`;
const _BudgetDonutDashboardPie_code = `import ToastPieChart from "./charts/toast-pie-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  EdgeInsets,
  MainAxisAlignment,
  CrossAxisAlignment,
  BorderRadius,
} from "flitter-ui";

const amounts = ["$2.4M", "$1.8M", "$1.2M", "$0.9M", "$0.6M", "$0.3M"];
const colors = ["#2563eb", "#7c3aed", "#db2777", "#ea580c", "#65a30d", "#94a3b8"];

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Payroll", value: 42 },
      { name: "Infrastructure", value: 18 },
      { name: "Marketing", value: 15 },
      { name: "R&D", value: 12 },
      { name: "Legal", value: 7 },
      { name: "Misc", value: 6 },
    ],
  },
  config: {
    colors: ["#2563eb", "#7c3aed", "#db2777", "#ea580c", "#65a30d", "#94a3b8"],
    legend: {
      position: "right-center",
    },
    pie: {
      innerRadiusRatio: 0.6,
    },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 8,
            height: 8,
            decoration: new BoxDecoration({
              color: colors[index],
              borderRadius: BorderRadius.circular(4),
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "#475569",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(amounts[index], {
            style: new TextStyle({
              fontSize: 11,
              color: "#94a3b8",
              fontWeight: "600",
            }),
          }),
        ],
      }),
  },
});`;
const _DevicePie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Desktop", value: 52 },
      { name: "Mobile", value: 38 },
      { name: "Tablet", value: 10 },
    ],
  },
  config: {
    colors: ["#6366f1", "#06b6d4", "#f59e0b"],
    pie: {
      innerRadiusRatio: 0.5,
      strokeWidth: 4,
      strokeColor: "white",
    },
  },
});`;
const _DonutPieChart_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    colors: ["#6366f1", "#ec4899", "#f59e0b", "#10b981", "#06b6d4"],
    pie: {
      innerRadiusRatio: 0.5,
    },
  },
});`;
const _EnergyMixPie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Coal", value: 27 },
      { name: "Natural Gas", value: 24 },
      { name: "Nuclear", value: 10 },
      { name: "Solar", value: 15 },
      { name: "Wind", value: 13 },
      { name: "Hydro", value: 11 },
    ],
  },
  config: {
    colors: ["#78716c", "#64748b", "#a855f7", "#eab308", "#22c55e", "#06b6d4"],
  },
});`;
const _ExpenseBreakdownPieChart_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Housing", value: 1800 },
      { name: "Food", value: 650 },
      { name: "Transport", value: 420 },
      { name: "Utilities", value: 280 },
      { name: "Healthcare", value: 350 },
      { name: "Entertainment", value: 200 },
      { name: "Education", value: 300 },
      { name: "Savings", value: 500 },
    ],
  },
  config: {
    colors: ["#0d9488", "#d97706", "#6366f1", "#ec4899", "#06b6d4", "#f43f5e", "#84cc16", "#a855f7"],
    pie: {
      innerRadiusRatio: 0.4,
      strokeWidth: 3,
    },
  },
});`;
const _MarketSharePieChart_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Apple", value: 28 },
      { name: "Samsung", value: 22 },
      { name: "Xiaomi", value: 13 },
      { name: "Oppo", value: 9 },
      { name: "Vivo", value: 8 },
      { name: "Others", value: 20 },
    ],
  },
  config: {
    colors: ["#3b82f6", "#10b981", "#f97316", "#8b5cf6", "#ef4444", "#64748b"],
  },
});`;
const _ProgrammingLanguagePie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Python", value: 28 },
      { name: "JavaScript", value: 22 },
      { name: "TypeScript", value: 15 },
      { name: "Java", value: 14 },
      { name: "Go", value: 11 },
      { name: "Rust", value: 10 },
    ],
  },
  config: {
    colors: ["#3572A5", "#f1e05a", "#3178c6", "#b07219", "#00ADD8", "#dea584"],
  },
});`;
const _RevenueByRegionPie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Americas", value: 42 },
      { name: "EMEA", value: 31 },
      { name: "APAC", value: 22 },
      { name: "Other", value: 5 },
    ],
  },
  config: {
    colors: ["#2563eb", "#dc2626", "#059669", "#d97706"],
  },
});`;
const _TimeAllocationPie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Meetings", value: 25 },
      { name: "Coding", value: 35 },
      { name: "Code Review", value: 15 },
      { name: "Planning", value: 15 },
      { name: "Break", value: 10 },
    ],
  },
  config: {
    colors: ["#ef4444", "#3b82f6", "#10b981", "#f59e0b", "#8b5cf6"],
    pie: {
      innerRadiusRatio: 0.45,
      strokeWidth: 3,
      strokeColor: "#f5f5f5",
    },
  },
});`;
const _TrafficSourcePie_code = `import ToastPieChart from "./charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Organic", value: 38 },
      { name: "Direct", value: 22 },
      { name: "Social", value: 18 },
      { name: "Referral", value: 14 },
      { name: "Email", value: 8 },
    ],
  },
  config: {
    colors: ["#3b82f6", "#10b981", "#f97316", "#ec4899", "#6366f1"],
    pie: {
      innerRadiusRatio: 0.55,
    },
  },
});`;

export const BasicPieChart = { Component: _BasicPieChart, code: _BasicPieChart_code };
export const DonutPieChart = { Component: _DonutPieChart, code: _DonutPieChart_code };
export const MarketSharePieChart = { Component: _MarketSharePieChart, code: _MarketSharePieChart_code };
export const ExpenseBreakdownPieChart = { Component: _ExpenseBreakdownPieChart, code: _ExpenseBreakdownPieChart_code };
export const EnergyMixPie = { Component: _EnergyMixPie, code: _EnergyMixPie_code };
export const TrafficSourcePie = { Component: _TrafficSourcePie, code: _TrafficSourcePie_code };
export const ProgrammingLanguagePie = { Component: _ProgrammingLanguagePie, code: _ProgrammingLanguagePie_code };
export const TimeAllocationPie = { Component: _TimeAllocationPie, code: _TimeAllocationPie_code };
export const RevenueByRegionPie = { Component: _RevenueByRegionPie, code: _RevenueByRegionPie_code };
export const DevicePie = { Component: _DevicePie, code: _DevicePie_code };
export const BudgetDonutDashboardPie = { Component: _BudgetDonutDashboardPie, code: _BudgetDonutDashboardPie_code };
