// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _DepartmentHeadcountAg from "./examples/department-headcount";
import _ProjectHoursAg from "./examples/project-hours";
import _RegionalSalesAg from "./examples/regional-sales";
import _RevenueByProductAg from "./examples/revenue-by-product";
import _SprintEffortAg from "./examples/sprint-effort";
import _SurveyResponsesAg from "./examples/survey-responses";
import _VolatileQuarterlyAg from "./examples/volatile-quarterly";

const _DepartmentHeadcountAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: {
    colors: { fills: ["#6366f1", "#ec4899", "#10b981"], strokes: ["#6366f1", "#ec4899", "#10b981"] },
  },
});`;
const _ProjectHoursAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";
import {
  Row,
  Container,
  BoxDecoration,
  EdgeInsets,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  BorderRadius,
} from "flitter-ui";

const chart = StackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Auth Service", "Dashboard", "Mobile App", "Data Pipeline", "Admin Portal"],
    datasets: [
      { legend: "Design", values: [40, 64, 56, 24, 32] },
      { legend: "Development", values: [120, 180, 160, 200, 96] },
      { legend: "QA", values: [32, 48, 44, 56, 28] },
    ],
  },
  custom: {
    title: () =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 3,
            height: 16,
            decoration: new BoxDecoration({
              color: "#6366f1",
              borderRadius: BorderRadius.circular(2),
            }),
          }),
          SizedBox({ width: 8 }),
          Text("Sprint Effort Breakdown", {
            style: new TextStyle({
              fontSize: 14,
              fontWeight: "700",
              color: "#1e293b",
            }),
          }),
        ],
      }),
  },
  config: {
    title: { text: "Hours by Phase", visible: true },
    subtitle: { text: "Q4 2025 Sprint Review", visible: true },
    colors: { fills: ["#f59e0b", "#3b82f6", "#10b981"], strokes: ["#f59e0b", "#3b82f6", "#10b981"] },
    grid: { dash: [2, 2] },
  },
});`;
const _RegionalSalesAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "North America", values: [120, 135, 110, 145, 160, 150, 170] },
      { legend: "Europe", values: [90, 85, 100, 95, 110, 105, 120] },
      { legend: "Asia Pacific", values: [65, 80, 75, 90, 85, 95, 100] },
    ],
  },
  config: {},
});`;
const _RevenueByProductAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 2023", "Q2 2023", "Q3 2023", "Q4 2023", "Q1 2024", "Q2 2024"],
    datasets: [
      { legend: "SaaS Platform", values: [850, 920, 980, 1050, 1120, 1200] },
      { legend: "Mobile App", values: [320, 380, 420, 460, 510, 560] },
      { legend: "API Services", values: [180, 210, 240, 280, 320, 370] },
    ],
  },
  config: {
    colors: { fills: ["#0d9488", "#d97706", "#7c3aed"], strokes: ["#0d9488", "#d97706", "#7c3aed"] },
    background: "#fafafa",
  },
});`;
const _SprintEffortAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Sprint 1", "Sprint 2", "Sprint 3", "Sprint 4", "Sprint 5", "Sprint 6"],
    datasets: [
      { legend: "Design", values: [24, 16, 12, 20, 14, 10] },
      { legend: "Development", values: [40, 56, 64, 48, 60, 72] },
      { legend: "QA", values: [8, 16, 20, 24, 18, 22] },
      { legend: "Deploy", values: [4, 8, 6, 8, 10, 8] },
    ],
  },
  config: {
    colors: { fills: ["#8b5cf6", "#3b82f6", "#f59e0b", "#ef4444"], strokes: ["#8b5cf6", "#3b82f6", "#f59e0b", "#ef4444"] },
    grid: { dash: [2, 2] },
  },
});`;
const _SurveyResponsesAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["Work-Life Balance", "Compensation", "Growth", "Culture", "Leadership"],
    datasets: [
      { legend: "Strongly Agree", values: [45, 28, 38, 52, 35] },
      { legend: "Agree", values: [30, 32, 28, 25, 30] },
      { legend: "Neutral", values: [15, 20, 18, 12, 18] },
      { legend: "Disagree", values: [10, 20, 16, 11, 17] },
    ],
  },
  config: {
    colors: { fills: ["#22c55e", "#86efac", "#fcd34d", "#f87171"], strokes: ["#22c55e", "#86efac", "#fcd34d", "#f87171"] },
  },
});`;
const _VolatileQuarterlyAg_code = `import StackedBarChart from "./charts/stacked-bar-chart";

const chart = StackedBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25", "Q3 '25"],
    datasets: [
      { legend: "Product A", values: [-20, 15, -5, 30, -10, 25, 8] },
      { legend: "Product B", values: [10, -12, 22, -8, 18, -15, 30] },
      { legend: "Product C", values: [5, -25, 12, 20, -18, 10, -7] },
    ],
  },
  config: {
    colors: { fills: ["#059669", "#dc2626", "#3b82f6"], strokes: ["#059669", "#dc2626", "#3b82f6"] },
    grid: { dash: [4, 4] },
  },
});`;

export const RegionalSalesAg = { Component: _RegionalSalesAg, code: _RegionalSalesAg_code };
export const DepartmentHeadcountAg = { Component: _DepartmentHeadcountAg, code: _DepartmentHeadcountAg_code };
export const VolatileQuarterlyAg = { Component: _VolatileQuarterlyAg, code: _VolatileQuarterlyAg_code };
export const RevenueByProductAg = { Component: _RevenueByProductAg, code: _RevenueByProductAg_code };
export const SurveyResponsesAg = { Component: _SurveyResponsesAg, code: _SurveyResponsesAg_code };
export const SprintEffortAg = { Component: _SprintEffortAg, code: _SprintEffortAg_code };
export const ProjectHoursAg = { Component: _ProjectHoursAg, code: _ProjectHoursAg_code };
