// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BudgetVsActualToast from "./examples/budget-vs-actual";
import _ConditionalPLToast from "./examples/conditional-pl";
import _FeaturedRevenueToast from "./examples/featured-revenue";
import _HorizontalRankingToast from "./examples/horizontal-ranking";
import _KpiCurrencyToast from "./examples/kpi-currency";
import _MonthlyRevenueToast from "./examples/monthly-revenue";
import _NegativeHorizontalToastBarChart from "./examples/negative-horizontal";
import _PopulationByAgeToast from "./examples/population-by-age";
import _ProfitLossToast from "./examples/profit-loss";
import _SalesKpiDashboardToast from "./examples/sales-kpi-dashboard";
import _SurveyResultsToast from "./examples/survey-results";
import _TopPerformersToast from "./examples/top-performers";
import _WeeklySalesTrackerToast from "./examples/weekly-sales";

const _BudgetVsActualToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1", "Q2", "Q3", "Q4"],
    datasets: [
      { legend: "Budget", values: [120, 135, 140, 150] },
      { legend: "Actual", values: [115, 142, 131, 158] },
    ],
  },
  config: {
    colors: ["#d4d4d4", "#0d9488"],
    bar: { cornerRadius: 4 },
    title: { text: "Budget vs Actual ($K)", visible: true },
  },
  custom: {
    dataLabel: (
      { value, legend }: { value: number; label: string; legend: string },
      context: any,
    ) => {
      if (legend !== "Actual") return Text("", { style: new TextStyle({}) });
      const { font } = context.config;
      return Text(\`$\${value}K\`, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: 10,
          fontWeight: "bold",
          color: "#0d9488",
        }),
      });
    },
  },
});`;
const _ConditionalPLToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Container, BoxDecoration, EdgeInsets, BorderRadius, Radius } from "flitter-ui";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "Net Income ($K)", values: [120, -45, 85, -60, 150, -30] },
    ],
  },
  config: {
    colors: ["#10b981"],
    title: { text: "Monthly P&L", visible: true },
    bar: { cornerRadius: 3 },
  },
  custom: {
    bar: (
      { value }: { value: number },
      context: any,
    ) => {
      const { bar } = context.config;
      return Container({
        margin: EdgeInsets.symmetric({ horizontal: 1 }),
        decoration: new BoxDecoration({
          color: value >= 0 ? "#10b981" : "#ef4444",
          borderRadius: BorderRadius.circular(bar.cornerRadius),
        }),
      });
    },
  },
});`;
const _FeaturedRevenueToast_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "North America", values: [4.2, 4.8, 3.9, 5.1, 5.6, 5.3] },
      { legend: "Europe", values: [3.1, 2.9, 3.4, 3.2, 3.8, 3.6] },
      { legend: "Asia Pacific", values: [2.1, 2.5, 2.3, 2.8, 2.6, 3.0] },
    ],
  },
  config: {
    colors: ["#0d9488", "#14b8a6", "#99f6e4"],
    title: { text: "Monthly Revenue ($M)", visible: true },
  },
});`;
const _HorizontalRankingToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Text, TextStyle, Row, SizedBox, MainAxisSize } from "flitter-ui";

const chart = ToastBarChart({
  direction: "horizontal",
  data: {
    labels: ["Alice", "Bob", "Carol", "Dave", "Eve"],
    datasets: [{ legend: "Sales ($K)", values: [142, 128, 115, 98, 87] }],
  },
  config: {
    colors: ["#0d9488"],
    title: { text: "Top Performers", visible: true },
    bar: { cornerRadius: 3 },
  },
  custom: {
    yAxisLabel: (
      { name, index }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      return Row({
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(\`\${index + 1}\`, {
            style: new TextStyle({
              fontFamily: font.family,
              fontSize: font.size,
              fontWeight: "bold",
              color: "#0d9488",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(name, {
            style: new TextStyle({
              fontFamily: font.family,
              fontSize: font.size,
              color: "#334155",
            }),
          }),
        ],
      });
    },
  },
});`;
const _KpiCurrencyToast_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["West", "East", "South", "North"],
    datasets: [
      { legend: "Closed", values: [82, 67, 54, 71] },
      { legend: "Pipeline", values: [45, 38, 62, 29] },
    ],
  },
  config: {
    colors: ["#0d9488", "#a7f3d0"],
    title: { text: "Sales by Region", visible: true },
    bar: { cornerRadius: 4 },
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "y" ? \`$\${name}K\` : name,
      },
    },
    grid: { color: "rgba(0,0,0,0.04)" },
    padding: { top: 16, right: 24, bottom: 16, left: 24 },
  },
});`;
const _MonthlyRevenueToast_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "North America", values: [4.2, 4.8, 3.9, 5.1, 5.6, 5.3] },
      { legend: "Europe", values: [3.1, 2.9, 3.4, 3.2, 3.8, 3.6] },
      { legend: "Asia Pacific", values: [2.1, 2.5, 2.3, 2.8, 2.6, 3.0] },
    ],
  },
  config: { colors: ["#0d9488", "#14b8a6", "#99f6e4"] },
});`;
const _NegativeHorizontalToastBarChart_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "horizontal",
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25"],
    datasets: [
      { legend: "Net Income", values: [32, -18, 45, -7, 28, -12] },
      { legend: "Operating Cash", values: [15, 22, -10, 38, -25, 19] },
    ],
  },
  config: { colors: ["#10b981", "#ef4444"] },
});`;
const _PopulationByAgeToast_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: [
      "Under\\n14",
      "15 to\\n24",
      "25 to\\n34",
      "35 to\\n44",
      "45 to\\n54",
      "55 to\\n64",
      "Over\\n65",
    ],
    datasets: [
      { legend: "Male (M)", values: [9.8, 8.2, 11.4, 10.6, 9.1, 7.8, 6.5] },
      { legend: "Female (M)", values: [9.3, 7.9, 11.1, 10.9, 9.4, 8.1, 7.2] },
    ],
  },
  config: {
    colors: ["#3b82f6", "#ec4899"],
    title: { text: "Population Distribution by Age", visible: true },
    bar: { cornerRadius: 2 },
  },
});`;
const _ProfitLossToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24", "Q1 '25", "Q2 '25"],
    datasets: [
      { legend: "Net Income", values: [32, -18, 45, -7, 28, -12] },
      { legend: "Operating Cash", values: [15, 22, -10, 38, -25, 19] },
    ],
  },
  config: {
    colors: ["#10b981", "#ef4444"],
    title: { text: "Quarterly P&L", visible: true },
    grid: { color: "rgba(0,0,0,0.06)" },
  },
  custom: {
    yAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      const val = parseFloat(name);
      const isZero = val === 0;
      return Text(name, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: font.size,
          fontWeight: isZero ? "bold" : "normal",
          color: isZero ? "#ef4444" : "#64748b",
        }),
      });
    },
  },
});`;
const _SalesKpiDashboardToast_code = `import ToastBarChart from "./charts/toast-bar-chart";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["West", "East", "South", "North"],
    datasets: [
      { legend: "Closed", values: [82, 67, 54, 71] },
      { legend: "Pipeline", values: [45, 38, 62, 29] },
    ],
  },
  config: {
    colors: ["#0d9488", "#a7f3d0"],
    bar: { cornerRadius: 3 },
    axis: {
      label: {
        format: (name: string, _index: number, axis: "x" | "y") =>
          axis === "y" ? \`$\${name}K\` : name,
      },
    },
    grid: { color: "rgba(0,0,0,0.04)" },
    padding: { top: 16, right: 24, bottom: 16, left: 24 },
  },
});`;
const _SurveyResultsToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Container, BoxDecoration, EdgeInsets, BorderRadius } from "flitter-ui";

const chart = ToastBarChart({
  direction: "horizontal",
  data: {
    labels: [
      "Ease of Use",
      "Performance",
      "Documentation",
      "Design Quality",
      "Support",
      "Value for Money",
    ],
    datasets: [{ legend: "Score (%)", values: [92, 87, 78, 95, 71, 84] }],
  },
  config: {
    colors: ["#f59e0b"],
    title: { text: "User Satisfaction Survey", visible: true },
    bar: { cornerRadius: 32 },
  },
  custom: {
    bar: (
      { value }: { value: number },
      context: any,
    ) => {
      return Container({
        margin: EdgeInsets.symmetric({ horizontal: 1 }),
        decoration: new BoxDecoration({
          color: value >= 90 ? "#10b981" : value >= 80 ? "#f59e0b" : "#94a3b8",
          borderRadius: BorderRadius.circular(8),
        }),
      });
    },
  },
});`;
const _TopPerformersToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  EdgeInsets,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  CrossAxisAlignment,
  SizedBox,
} from "flitter-ui";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Alice", "Bob", "Carol", "Dave", "Eve"],
    datasets: [{ legend: "Sales ($K)", values: [142, 128, 115, 98, 87] }],
  },
  config: {
    colors: ["#f97316"],
    bar: { cornerRadius: 3 },
    title: { text: "Top Performers", visible: true, alignment: "center" },
  },
  custom: {
    title: (
      _args: undefined,
      context: any,
    ) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 16, vertical: 8 }),
        decoration: new BoxDecoration({
          color: "#fff7ed",
          borderRadius: BorderRadius.circular(8),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text("🏆 Top Performers", {
              style: new TextStyle({
                fontFamily: title.fontFamily ?? font.family,
                fontSize: title.fontSize,
                fontWeight: "700",
                color: "#c2410c",
              }),
            }),
            SizedBox({ height: 2 }),
            Text("Monthly sales ranking", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 11,
                color: "#ea580c",
              }),
            }),
          ],
        }),
      });
    },
  },
});`;
const _WeeklySalesTrackerToast_code = `import ToastBarChart from "./charts/toast-bar-chart";
import { Transform, Text, TextStyle, Alignment } from "flitter-ui";

const chart = ToastBarChart({
  direction: "vertical",
  data: {
    labels: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    datasets: [{ legend: "Units Sold", values: [64, 82, 75, 93, 110, 142, 98] }],
  },
  config: {
    colors: ["#6366f1"],
    title: { text: "Weekly Sales Tracker", visible: true },
    bar: { cornerRadius: 2 },
  },
  custom: {
    xAxisLabel: (
      { name }: { name: string; index: number },
      context: any,
    ) => {
      const { font } = context.config;
      return Transform.rotate({
        angle: -Math.PI / 4,
        alignment: Alignment.centerRight,
        child: Text(name, {
          style: new TextStyle({
            fontFamily: font.family,
            fontSize: 10,
            color: "#64748b",
          }),
        }),
      });
    },
  },
});`;

export const FeaturedRevenueToast = { Component: _FeaturedRevenueToast, code: _FeaturedRevenueToast_code };
export const KpiCurrencyToast = { Component: _KpiCurrencyToast, code: _KpiCurrencyToast_code };
export const ConditionalPLToast = { Component: _ConditionalPLToast, code: _ConditionalPLToast_code };
export const HorizontalRankingToast = { Component: _HorizontalRankingToast, code: _HorizontalRankingToast_code };
export const MonthlyRevenueToast = { Component: _MonthlyRevenueToast, code: _MonthlyRevenueToast_code };
export const VerticalToastBarChart = { Component: _MonthlyRevenueToast, code: _MonthlyRevenueToast_code };
export const SurveyResultsToast = { Component: _SurveyResultsToast, code: _SurveyResultsToast_code };
export const HorizontalToastBarChart = { Component: _SurveyResultsToast, code: _SurveyResultsToast_code };
export const ProfitLossToast = { Component: _ProfitLossToast, code: _ProfitLossToast_code };
export const NegativeVerticalToastBarChart = { Component: _ProfitLossToast, code: _ProfitLossToast_code };
export const NegativeHorizontalToastBarChart = { Component: _NegativeHorizontalToastBarChart, code: _NegativeHorizontalToastBarChart_code };
export const BudgetVsActualToast = { Component: _BudgetVsActualToast, code: _BudgetVsActualToast_code };
export const PopulationByAgeToast = { Component: _PopulationByAgeToast, code: _PopulationByAgeToast_code };
export const SalesKpiDashboardToast = { Component: _SalesKpiDashboardToast, code: _SalesKpiDashboardToast_code };
export const TopPerformersToast = { Component: _TopPerformersToast, code: _TopPerformersToast_code };
export const WeeklySalesTrackerToast = { Component: _WeeklySalesTrackerToast, code: _WeeklySalesTrackerToast_code };
