// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _AppPerformanceAgArea from "./examples/app-performance-ag-area";
import _CloudUsageAgArea from "./examples/cloud-usage-ag-area";
import _DarkMonitoringAgArea from "./examples/dark-monitoring-ag-area";
import _DefaultAgAreaChart from "./examples/default-ag-area-chart";
import _QuarterlyRevenueAgArea from "./examples/quarterly-revenue-ag-area";
import _SplineAgAreaChart from "./examples/spline-ag-area-chart";

const _AppPerformanceAgArea_code = `import AreaChart from "./charts/area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = AreaChart({
  data: {
    labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
    datasets: [
      { legend: "CPU (%)", values: [15, 10, 68, 80, 65, 28] },
      { legend: "Memory (%)", values: [42, 38, 65, 75, 68, 48] },
    ],
  },
  config: {
    colors: { fills: ["#ef4444", "#6366f1"], strokes: ["#ef4444", "#6366f1"] },
    grid: { dash: [2, 2] },
    area: {
      strokeWidth: 1.5,
      opacity: 0.15,
      spline: true,
    },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }) => {
      const value = parseFloat(name);
      const isCritical = value >= 70;
      return Text(\`\${name}%\`, {
        style: new TextStyle({
          fontSize: 11,
          color: isCritical ? "#ef4444" : "#6b7280",
          fontWeight: isCritical ? "700" : undefined,
        }),
      });
    },
  },
});`;
const _CloudUsageAgArea_code = `import AreaChart from "./charts/area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = AreaChart({
  data: {
    labels: ["Jan\\nQ1", "Mar\\nQ1", "May\\nQ2", "Jul\\nQ3", "Sep\\nQ3", "Nov\\nQ4"],
    datasets: [
      { legend: "Compute ($K)", values: [12.5, 14.8, 18.5, 23.4, 24.2, 19.5] },
      { legend: "Storage ($K)", values: [5.2, 5.9, 7.0, 8.2, 9.2, 10.0] },
      { legend: "Network ($K)", values: [3.1, 3.8, 4.9, 6.5, 6.8, 5.0] },
    ],
  },
  config: {
    colors: { fills: ["#3b82f6", "#f59e0b", "#10b981"], strokes: ["#3b82f6", "#f59e0b", "#10b981"] },
    background: "#f8fafc",
    area: {
      strokeWidth: 2,
      opacity: 0.25,
      spline: false,
    },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }) => {
      const value = parseFloat(name);
      return Text(isNaN(value) ? name : \`$\${name}K\`, {
        style: new TextStyle({
          fontSize: 11,
          color: "#64748b",
        }),
      });
    },
  },
});`;
const _DarkMonitoringAgArea_code = `import AreaChart from "./charts/area-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  BorderRadius,
  BoxShadow,
} from "flitter-ui";

const colors = ["#22d3ee", "#a78bfa", "#f87171"];

const chart = AreaChart({
  data: {
    labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
    datasets: [
      { legend: "Inbound (Gbps)", values: [1.2, 0.4, 3.8, 6.5, 5.1, 2.8] },
      { legend: "Outbound (Gbps)", values: [0.9, 0.3, 2.5, 4.8, 3.9, 2.1] },
      { legend: "Errors (K)", values: [0.1, 0.05, 0.3, 0.8, 0.6, 0.2] },
    ],
  },
  config: {
    colors: { fills: ["#22d3ee", "#a78bfa", "#f87171"], strokes: ["#22d3ee", "#a78bfa", "#f87171"] },
    background: "#111827",
    grid: { dash: [4, 4], color: "rgba(255,255,255,0.1)" },
    axis: { color: "rgba(255,255,255,0.3)", label: { color: "rgba(255,255,255,0.6)" } },
    area: {
      strokeWidth: 1.5,
      opacity: 0.2,
      spline: true,
    },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 8,
            height: 8,
            decoration: new BoxDecoration({
              color: colors[index],
              borderRadius: BorderRadius.circular(4),
              boxShadow: [
                new BoxShadow({
                  color: colors[index] + "80",
                  blurRadius: 6,
                }),
              ],
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "rgba(255,255,255,0.7)",
            }),
          }),
        ],
      }),
  },
});`;
const _DefaultAgAreaChart_code = `import AreaChart from "./charts/area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = AreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Housing starts (MoM %)", values: [0, 12.38, -15.46, 5.56, -4.98, 0.84, -4.67, 9.96, -2.44, -0.37, -4.22, 16.91] },
      { legend: "Unemployment rate Δ (pp)", values: [0, 11.2, -8.4, 6.9, -5.8, 7.5, -6.2, 4.9, -4.1, 8.1, -5.6, 7.2] },
      { legend: "CPI MoM (1/10 index pts)", values: [0, 12.69, 13.78, 6.78, 1.52, -1.31, 5.25, 4.93, 6.70, 8.99, 8.97, 10.76] },
    ],
  },
  config: {
    area: {
      strokeWidth: 2,
      opacity: 0.3,
      spline: false,
    },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }) => {
      const value = parseFloat(name);
      const isHigh = value >= 10;
      return Text(name, {
        style: new TextStyle({
          fontSize: 11,
          color: isHigh ? "#d97706" : "#6b7280",
          fontWeight: isHigh ? "700" : undefined,
        }),
      });
    },
  },
});`;
const _QuarterlyRevenueAgArea_code = `import AreaChart from "./charts/area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = AreaChart({
  data: {
    labels: ["Q1 '22", "Q2 '22", "Q3 '22", "Q4 '22", "Q1 '23", "Q2 '23", "Q3 '23", "Q4 '23"],
    datasets: [
      { legend: "SaaS ($M)", values: [8.5, 9.2, 10.1, 11.5, 13.0, 14.8, 16.2, 18.5] },
      { legend: "On-Prem ($M)", values: [12.0, 11.5, 11.0, 10.2, 9.5, 8.8, 8.0, 7.2] },
    ],
  },
  config: {
    colors: { fills: ["#0d9488", "#d97706"], strokes: ["#0d9488", "#d97706"] },
    title: { text: "SaaS vs On-Prem Revenue", visible: true },
    area: {
      strokeWidth: 2.5,
      opacity: 0.35,
      spline: false,
    },
  },
  custom: {
    xAxisLabel: ({ name }: { name: string; index: number }) => {
      const isQ4 = name.startsWith("Q4");
      return Text(name, {
        style: new TextStyle({
          fontSize: 11,
          color: isQ4 ? "#0d9488" : "#6b7280",
          fontWeight: isQ4 ? "700" : undefined,
        }),
      });
    },
  },
});`;
const _SplineAgAreaChart_code = `import AreaChart from "./charts/area-chart";
import {
  Container,
  BoxDecoration,
  Text,
  TextStyle,
  EdgeInsets,
  Border,
  BorderSide,
} from "flitter-ui";

const chart = AreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Housing starts (MoM %)", values: [0, 12.38, -15.46, 5.56, -4.98, 0.84, -4.67, 9.96, -2.44, -0.37, -4.22, 16.91] },
      { legend: "Unemployment rate Δ (pp)", values: [0, 11.2, -8.4, 6.9, -5.8, 7.5, -6.2, 4.9, -4.1, 8.1, -5.6, 7.2] },
      { legend: "CPI MoM (1/10 index pts)", values: [0, 12.69, 13.78, 6.78, 1.52, -1.31, 5.25, 4.93, 6.70, 8.99, 8.97, 10.76] },
    ],
  },
  config: {
    colors: { fills: ["#7c3aed", "#0ea5e9"], strokes: ["#7c3aed", "#0ea5e9"] },
    grid: { dash: [4, 4] },
    area: {
      strokeWidth: 2,
      opacity: 0.2,
      spline: true,
    },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }) =>
      Container({
        padding: EdgeInsets.symmetric({ horizontal: 6, vertical: 3 }),
        decoration: new BoxDecoration({
          border: new Border({
            bottom: new BorderSide({
              color: index % 3 === 0 ? "#7c3aed" : "transparent",
              width: 2,
            }),
          }),
        }),
        child: Text(name, {
          style: new TextStyle({
            fontSize: 10,
            color: index % 3 === 0 ? "#7c3aed" : "#9ca3af",
            fontWeight: index % 3 === 0 ? "600" : undefined,
          }),
        }),
      }),
  },
});`;

export const DefaultAgAreaChart = { Component: _DefaultAgAreaChart, code: _DefaultAgAreaChart_code };
export const SplineAgAreaChart = { Component: _SplineAgAreaChart, code: _SplineAgAreaChart_code };
export const CloudUsageAgArea = { Component: _CloudUsageAgArea, code: _CloudUsageAgArea_code };
export const AppPerformanceAgArea = { Component: _AppPerformanceAgArea, code: _AppPerformanceAgArea_code };
export const QuarterlyRevenueAgArea = { Component: _QuarterlyRevenueAgArea, code: _QuarterlyRevenueAgArea_code };
export const DarkMonitoringAgArea = { Component: _DarkMonitoringAgArea, code: _DarkMonitoringAgArea_code };
