// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BasicAgPieChart from "./examples/basic-ag-pie-chart";
import _DonutAgPieChart from "./examples/donut-ag-pie-chart";
import _EnergyMixAgPie from "./examples/energy-mix-ag-pie";
import _ExpenseBreakdownAgPieChart from "./examples/expense-breakdown-ag-pie-chart";
import _MarketShareAgPieChart from "./examples/market-share-ag-pie-chart";
import _QuarterlyReportAgPie from "./examples/quarterly-report-ag-pie";

const _BasicAgPieChart_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {},
});`;
const _DonutAgPieChart_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    pie: {
      innerRadiusRatio: 0.5,
    },
  },
});`;
const _EnergyMixAgPie_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Coal", value: 27 },
      { name: "Natural Gas", value: 24 },
      { name: "Nuclear", value: 10 },
      { name: "Solar", value: 15 },
      { name: "Wind", value: 13 },
      { name: "Hydro", value: 11 },
    ],
  },
  config: {},
});`;
const _ExpenseBreakdownAgPieChart_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Housing", value: 1800 },
      { name: "Food", value: 650 },
      { name: "Transport", value: 420 },
      { name: "Utilities", value: 280 },
      { name: "Healthcare", value: 350 },
      { name: "Entertainment", value: 200 },
      { name: "Education", value: 300 },
      { name: "Savings", value: 500 },
    ],
  },
  config: {
    pie: {
      innerRadiusRatio: 0.4,
    },
  },
});`;
const _MarketShareAgPieChart_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Apple", value: 28 },
      { name: "Samsung", value: 22 },
      { name: "Xiaomi", value: 13 },
      { name: "Oppo", value: 9 },
      { name: "Vivo", value: 8 },
      { name: "Others", value: 20 },
    ],
  },
  config: {},
});`;
const _QuarterlyReportAgPie_code = `import PieChart from "./charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Product Sales", value: 48 },
      { name: "Subscriptions", value: 24 },
      { name: "Licensing", value: 14 },
      { name: "Consulting", value: 9 },
      { name: "Support", value: 5 },
    ],
  },
  config: {
    title: {
      text: "Revenue Split",
      visible: true,
      position: "bottom",
      alignment: "center",
    },
    subtitle: {
      text: "FY 2025 Q4",
      visible: true,
    },
  },
});`;

export const BasicAgPieChart = { Component: _BasicAgPieChart, code: _BasicAgPieChart_code };
export const DonutAgPieChart = { Component: _DonutAgPieChart, code: _DonutAgPieChart_code };
export const MarketShareAgPieChart = { Component: _MarketShareAgPieChart, code: _MarketShareAgPieChart_code };
export const ExpenseBreakdownAgPieChart = { Component: _ExpenseBreakdownAgPieChart, code: _ExpenseBreakdownAgPieChart_code };
export const EnergyMixAgPie = { Component: _EnergyMixAgPie, code: _EnergyMixAgPie_code };
export const QuarterlyReportAgPie = { Component: _QuarterlyReportAgPie, code: _QuarterlyReportAgPie_code };
