// AUTO-GENERATED — do not edit manually
// Run: npm run gen:examples

export const BasicAgPieChartCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function BasicAgPieChart() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Chrome\", value: 65 },\n            { name: \"Safari\", value: 18 },\n            { name: \"Firefox\", value: 8 },\n            { name: \"Edge\", value: 5 },\n            { name: \"Other\", value: 4 },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const DonutAgPieChartCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function DonutAgPieChart() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Chrome\", value: 65 },\n            { name: \"Safari\", value: 18 },\n            { name: \"Firefox\", value: 8 },\n            { name: \"Edge\", value: 5 },\n            { name: \"Other\", value: 4 },\n          ],\n        },\n        config: {\n          pie: {\n            innerRadiusRatio: 0.5,\n          },\n        },\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const EnergyMixAgPieCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function EnergyMixAgPie() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Coal\", value: 27 },\n            { name: \"Natural Gas\", value: 24 },\n            { name: \"Nuclear\", value: 10 },\n            { name: \"Solar\", value: 15 },\n            { name: \"Wind\", value: 13 },\n            { name: \"Hydro\", value: 11 },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const ExpenseBreakdownAgPieChartCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function ExpenseBreakdownAgPieChart() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Housing\", value: 1800 },\n            { name: \"Food\", value: 650 },\n            { name: \"Transport\", value: 420 },\n            { name: \"Utilities\", value: 280 },\n            { name: \"Healthcare\", value: 350 },\n            { name: \"Entertainment\", value: 200 },\n            { name: \"Education\", value: 300 },\n            { name: \"Savings\", value: 500 },\n          ],\n        },\n        config: {\n          pie: {\n            innerRadiusRatio: 0.4,\n          },\n        },\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const MarketShareAgPieChartCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function MarketShareAgPieChart() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Apple\", value: 28 },\n            { name: \"Samsung\", value: 22 },\n            { name: \"Xiaomi\", value: 13 },\n            { name: \"Oppo\", value: 9 },\n            { name: \"Vivo\", value: 8 },\n            { name: \"Others\", value: 20 },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const QuarterlyReportAgPieCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { PieChart } from \"shared/chart\";\n\nexport default function QuarterlyReportAgPie() {\n  return (\n    <Widget\n      widget={PieChart({\n        data: {\n          datasets: [\n            { name: \"Product Sales\", value: 48 },\n            { name: \"Subscriptions\", value: 24 },\n            { name: \"Licensing\", value: 14 },\n            { name: \"Consulting\", value: 9 },\n            { name: \"Support\", value: 5 },\n          ],\n        },\n        config: {\n          title: {\n            text: \"Revenue Split\",\n            visible: true,\n            position: \"bottom\",\n            alignment: \"center\",\n          },\n          subtitle: {\n            text: \"FY 2025 Q4\",\n            visible: true,\n          },\n        },\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
