// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _CompactCorrelationAg from "./examples/compact-correlation-ag";
import _CustomerSatisfactionAg from "./examples/customer-satisfaction-ag";
import _DefaultAgScatterChart from "./examples/default-ag-scatter-chart";
import _FilledAgScatterChart from "./examples/filled-ag-scatter-chart";
import _PerformanceBenchmarkAg from "./examples/performance-benchmark-ag";
import _StudentScoresAg from "./examples/student-scores-ag";

const _CompactCorrelationAg_code = `import ScatterChart from "./charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Engagement",
        data: [
          { x: 2.1, y: 34, label: "Email" },
          { x: 4.8, y: 67, label: "Social" },
          { x: 3.2, y: 48, label: "Blog" },
          { x: 6.5, y: 82, label: "Webinar" },
          { x: 1.8, y: 28, label: "Print" },
          { x: 5.1, y: 71, label: "Video" },
          { x: 3.9, y: 55, label: "Podcast" },
        ],
      },
      {
        legend: "Conversion",
        data: [
          { x: 1.5, y: 12, label: "Email" },
          { x: 3.6, y: 29, label: "Social" },
          { x: 2.4, y: 18, label: "Blog" },
          { x: 5.2, y: 41, label: "Webinar" },
          { x: 1.1, y: 8, label: "Print" },
          { x: 4.3, y: 35, label: "Video" },
          { x: 2.8, y: 22, label: "Podcast" },
        ],
      },
      {
        legend: "Retention",
        data: [
          { x: 3.0, y: 58, label: "Email" },
          { x: 2.2, y: 42, label: "Social" },
          { x: 4.1, y: 63, label: "Blog" },
          { x: 5.8, y: 78, label: "Webinar" },
          { x: 1.4, y: 31, label: "Print" },
          { x: 4.6, y: 69, label: "Video" },
          { x: 3.5, y: 52, label: "Podcast" },
        ],
      },
    ],
  },
  config: {
    scatter: { size: 8, strokeWidth: 2 },
    colors: {
      fills: ["#6366f1", "#f43f5e", "#10b981"],
      strokes: ["#6366f1", "#f43f5e", "#10b981"],
    },
    grid: { dash: [3, 3] },
    legend: { position: "right-top" },
    background: "#fafafa",
  },
});`;
const _CustomerSatisfactionAg_code = `import ScatterChart from "./charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Software",
        data: [
          { x: 49, y: 4.2, label: "Notion" },
          { x: 99, y: 4.5, label: "Figma" },
          { x: 29, y: 3.8, label: "Trello" },
          { x: 199, y: 4.7, label: "Salesforce" },
          { x: 79, y: 4.1, label: "Slack" },
        ],
      },
      {
        legend: "Hardware",
        data: [
          { x: 999, y: 4.3, label: "MacBook" },
          { x: 1299, y: 4.6, label: "iPhone" },
          { x: 699, y: 3.9, label: "Galaxy" },
          { x: 349, y: 4.0, label: "Pixel" },
          { x: 1499, y: 4.4, label: "Surface" },
        ],
      },
      {
        legend: "Services",
        data: [
          { x: 15, y: 4.1, label: "Netflix" },
          { x: 10, y: 3.5, label: "Spotify" },
          { x: 12, y: 3.9, label: "Disney+" },
          { x: 20, y: 4.3, label: "YouTube Premium" },
          { x: 8, y: 3.2, label: "Hulu" },
        ],
      },
      {
        legend: "Food Delivery",
        data: [
          { x: 25, y: 3.6, label: "DoorDash" },
          { x: 20, y: 3.4, label: "Uber Eats" },
          { x: 18, y: 3.8, label: "Grubhub" },
          { x: 30, y: 3.5, label: "Instacart" },
        ],
      },
    ],
  },
  config: {
    scatter: { size: 11, strokeWidth: 2 },
    colors: {
      fills: ["#0d9488", "#e11d48", "#2563eb", "#d97706"],
      strokes: ["#0d9488", "#e11d48", "#2563eb", "#d97706"],
    },
  },
});`;
const _DefaultAgScatterChart_code = `import ScatterChart from "./charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Africa",
        data: [
          { x: 4200, y: 70.35, label: "Morocco" },
          { x: 4200, y: 70.71, label: "Egypt" },
          { x: 5900, y: 56.46, label: "Gabon" },
          { x: 6600, y: 72.74, label: "Algeria" },
          { x: 6700, y: 76.28, label: "Libya" },
          { x: 7100, y: 74.66, label: "Tunisia" },
          { x: 10500, y: 69.28, label: "Trinidad and Tobago" },
          { x: 12800, y: 72.09, label: "Mauritius" },
          { x: 18200, y: 78.68, label: "Malta" },
        ],
      },
      {
        legend: "America",
        data: [
          { x: 4800, y: 74.64, label: "Paraguay" },
          { x: 4900, y: 70.92, label: "El Salvador" },
          { x: 5600, y: 69.22, label: "Peru" },
          { x: 5800, y: 74.06, label: "Venezuela" },
          { x: 6600, y: 71.43, label: "Colombia" },
          { x: 8100, y: 71.41, label: "Brazil" },
          { x: 9600, y: 76.63, label: "Costa Rica" },
          { x: 9600, y: 74.94, label: "Mexico" },
          { x: 12400, y: 75.7, label: "Argentina" },
          { x: 31500, y: 79.96, label: "Canada" },
          { x: 32100, y: 77.43, label: "United States" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 5600, y: 71.96, label: "China" },
          { x: 7700, y: 69.66, label: "Iran" },
          { x: 8100, y: 71.41, label: "Thailand" },
          { x: 9700, y: 71.95, label: "Malaysia" },
          { x: 12000, y: 75.23, label: "Saudi Arabia" },
          { x: 19200, y: 75.58, label: "Korea, South" },
          { x: 25300, y: 77.06, label: "Taiwan" },
          { x: 27800, y: 81.53, label: "Singapore" },
          { x: 29400, y: 81.04, label: "Japan" },
          { x: 34200, y: 81.39, label: "Hong Kong" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 9800, y: 66.39, label: "Russia" },
          { x: 12000, y: 74.16, label: "Poland" },
          { x: 17900, y: 77.35, label: "Portugal" },
          { x: 23300, y: 79.37, label: "Spain" },
          { x: 27700, y: 79.54, label: "Italy" },
          { x: 28700, y: 78.54, label: "Germany" },
          { x: 28700, y: 79.44, label: "France" },
          { x: 29600, y: 78.27, label: "United Kingdom" },
          { x: 33800, y: 80.31, label: "Switzerland" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 2200, y: 64.56, label: "Papua New Guinea" },
          { x: 5900, y: 69.2, label: "Fiji" },
          { x: 23200, y: 78.49, label: "New Zealand" },
          { x: 30700, y: 80.26, label: "Australia" },
        ],
      },
    ],
  },
  config: {},
});`;
const _FilledAgScatterChart_code = `import ScatterChart from "./charts/scatter-chart";
const defaultData = {
  datasets: [
    {
      legend: "Africa",
      data: [
        { x: 4200, y: 70.35, label: "Morocco" },
        { x: 4200, y: 70.71, label: "Egypt" },
        { x: 5900, y: 56.46, label: "Gabon" },
        { x: 6600, y: 72.74, label: "Algeria" },
        { x: 6700, y: 76.28, label: "Libya" },
        { x: 7100, y: 74.66, label: "Tunisia" },
        { x: 10500, y: 69.28, label: "Trinidad and Tobago" },
        { x: 12800, y: 72.09, label: "Mauritius" },
        { x: 18200, y: 78.68, label: "Malta" },
      ],
    },
    {
      legend: "America",
      data: [
        { x: 4800, y: 74.64, label: "Paraguay" },
        { x: 4900, y: 70.92, label: "El Salvador" },
        { x: 5600, y: 69.22, label: "Peru" },
        { x: 5800, y: 74.06, label: "Venezuela" },
        { x: 6600, y: 71.43, label: "Colombia" },
        { x: 8100, y: 71.41, label: "Brazil" },
        { x: 9600, y: 76.63, label: "Costa Rica" },
        { x: 9600, y: 74.94, label: "Mexico" },
        { x: 12400, y: 75.7, label: "Argentina" },
        { x: 31500, y: 79.96, label: "Canada" },
        { x: 32100, y: 77.43, label: "United States" },
      ],
    },
    {
      legend: "Asia",
      data: [
        { x: 5600, y: 71.96, label: "China" },
        { x: 7700, y: 69.66, label: "Iran" },
        { x: 8100, y: 71.41, label: "Thailand" },
        { x: 9700, y: 71.95, label: "Malaysia" },
        { x: 12000, y: 75.23, label: "Saudi Arabia" },
        { x: 19200, y: 75.58, label: "Korea, South" },
        { x: 25300, y: 77.06, label: "Taiwan" },
        { x: 27800, y: 81.53, label: "Singapore" },
        { x: 29400, y: 81.04, label: "Japan" },
        { x: 34200, y: 81.39, label: "Hong Kong" },
      ],
    },
    {
      legend: "Europe",
      data: [
        { x: 9800, y: 66.39, label: "Russia" },
        { x: 12000, y: 74.16, label: "Poland" },
        { x: 17900, y: 77.35, label: "Portugal" },
        { x: 23300, y: 79.37, label: "Spain" },
        { x: 27700, y: 79.54, label: "Italy" },
        { x: 28700, y: 78.54, label: "Germany" },
        { x: 28700, y: 79.44, label: "France" },
        { x: 29600, y: 78.27, label: "United Kingdom" },
        { x: 33800, y: 80.31, label: "Switzerland" },
      ],
    },
    {
      legend: "Oceania",
      data: [
        { x: 2200, y: 64.56, label: "Papua New Guinea" },
        { x: 5900, y: 69.2, label: "Fiji" },
        { x: 23200, y: 78.49, label: "New Zealand" },
        { x: 30700, y: 80.26, label: "Australia" },
      ],
    },
  ],
};

const chart = ScatterChart({
  data: defaultData,
  config: {
    scatter: { size: 8 },
    colors: {
      fills: ["#6366f1", "#ec4899", "#10b981"],
      strokes: ["#6366f1", "#ec4899", "#10b981"],
    },
  },
});`;
const _PerformanceBenchmarkAg_code = `import ScatterChart from "./charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "System A (Node.js)",
        data: [
          { x: 12, y: 8500, label: "GET /api" },
          { x: 18, y: 7200, label: "POST /data" },
          { x: 25, y: 6100, label: "PUT /update" },
          { x: 8, y: 9800, label: "GET /health" },
          { x: 35, y: 4500, label: "POST /batch" },
          { x: 15, y: 8000, label: "GET /list" },
        ],
      },
      {
        legend: "System B (Go)",
        data: [
          { x: 5, y: 15000, label: "GET /api" },
          { x: 8, y: 13500, label: "POST /data" },
          { x: 12, y: 11000, label: "PUT /update" },
          { x: 3, y: 18000, label: "GET /health" },
          { x: 20, y: 9000, label: "POST /batch" },
          { x: 6, y: 14200, label: "GET /list" },
        ],
      },
      {
        legend: "System C (Python)",
        data: [
          { x: 45, y: 3200, label: "GET /api" },
          { x: 60, y: 2800, label: "POST /data" },
          { x: 80, y: 2100, label: "PUT /update" },
          { x: 30, y: 4000, label: "GET /health" },
          { x: 100, y: 1500, label: "POST /batch" },
          { x: 50, y: 3000, label: "GET /list" },
        ],
      },
    ],
  },
  config: {
    scatter: { size: 12, strokeWidth: 3 },
    colors: {
      fills: ["#ef4444", "#3b82f6", "#10b981"],
      strokes: ["#ef4444", "#3b82f6", "#10b981"],
    },
    grid: { dash: [4, 4] },
    background: "#fafafa",
  },
});`;
const _StudentScoresAg_code = `import ScatterChart from "./charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Class A",
        data: [
          { x: 85, y: 78, label: "Student 1" },
          { x: 92, y: 88, label: "Student 2" },
          { x: 76, y: 82, label: "Student 3" },
          { x: 68, y: 65, label: "Student 4" },
          { x: 95, y: 91, label: "Student 5" },
          { x: 80, y: 75, label: "Student 6" },
        ],
      },
      {
        legend: "Class B",
        data: [
          { x: 70, y: 85, label: "Student 1" },
          { x: 88, y: 92, label: "Student 2" },
          { x: 65, y: 70, label: "Student 3" },
          { x: 78, y: 80, label: "Student 4" },
          { x: 90, y: 95, label: "Student 5" },
          { x: 72, y: 76, label: "Student 6" },
        ],
      },
      {
        legend: "Class C",
        data: [
          { x: 60, y: 55, label: "Student 1" },
          { x: 75, y: 70, label: "Student 2" },
          { x: 82, y: 78, label: "Student 3" },
          { x: 90, y: 85, label: "Student 4" },
          { x: 55, y: 60, label: "Student 5" },
          { x: 68, y: 72, label: "Student 6" },
        ],
      },
    ],
  },
  config: {
    scatter: { size: 9 },
    colors: {
      fills: ["#f59e0b", "#8b5cf6", "#06b6d4"],
      strokes: ["#f59e0b", "#8b5cf6", "#06b6d4"],
    },
  },
});`;

export const DefaultAgScatterChart = { Component: _DefaultAgScatterChart, code: _DefaultAgScatterChart_code };
export const FilledAgScatterChart = { Component: _FilledAgScatterChart, code: _FilledAgScatterChart_code };
export const PerformanceBenchmarkAg = { Component: _PerformanceBenchmarkAg, code: _PerformanceBenchmarkAg_code };
export const StudentScoresAg = { Component: _StudentScoresAg, code: _StudentScoresAg_code };
export const CustomerSatisfactionAg = { Component: _CustomerSatisfactionAg, code: _CustomerSatisfactionAg_code };
export const CompactCorrelationAg = { Component: _CompactCorrelationAg, code: _CompactCorrelationAg_code };
