// AUTO-GENERATED — do not edit manually
// Run: npm run gen:examples

export const AssessmentOverviewCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function AssessmentOverviewAg() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"Analytics\", \"Strategy\", \"Delivery\", \"Communication\", \"Leadership\"],\n          datasets: [\n            { legend: \"Self\", values: [82, 78, 90, 85, 70] },\n            { legend: \"Manager\", values: [75, 88, 85, 80, 82] },\n            { legend: \"Peer\", values: [80, 72, 88, 92, 68] },\n          ],\n        },\n        config: {\n          legend: { position: \"right-top\" },\n          background: \"#f8fafc\",\n        },\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const AthleteProfileCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function AthleteProfileAgRadar() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"Speed\", \"Strength\", \"Endurance\", \"Agility\", \"Flexibility\"],\n          datasets: [\n            { legend: \"Sprinter\", values: [98, 75, 50, 90, 60] },\n            { legend: \"Marathoner\", values: [70, 55, 98, 65, 75] },\n            { legend: \"Gymnast\", values: [72, 68, 60, 95, 98] },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const BasicRadarCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function BasicAgRadarChart() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"JavaScript\", \"TypeScript\", \"React\", \"Node.js\", \"CSS\", \"GraphQL\", \"Testing\", \"DevOps\"],\n          datasets: [\n            { legend: \"Senior Dev\", values: [95, 90, 85, 80, 70, 75, 80, 65] },\n            { legend: \"Junior Dev\", values: [70, 50, 60, 40, 65, 30, 35, 20] },\n            { legend: \"Full Stack\", values: [80, 75, 70, 85, 60, 65, 70, 80] },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const ProductReviewCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function ProductReviewAgRadar() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"Price\", \"Quality\", \"Design\", \"Durability\", \"Support\"],\n          datasets: [\n            { legend: \"Product A\", values: [60, 90, 85, 95, 70] },\n            { legend: \"Product B\", values: [85, 70, 75, 60, 90] },\n            { legend: \"Product C\", values: [75, 80, 90, 80, 65] },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const SkillComparisonCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function SkillComparisonAgRadar() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"Leadership\", \"Problem Solving\", \"Communication\", \"Technical\", \"Creativity\", \"Teamwork\"],\n          datasets: [\n            { legend: \"Alice\", values: [90, 85, 95, 70, 80, 92] },\n            { legend: \"Bob\", values: [75, 92, 60, 95, 65, 78] },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
export const TeamPerformanceCode = "\"use client\";\n\nimport Widget from \"@flitterjs/react\";\nimport { RadarChart } from \"shared/chart\";\n\nexport default function TeamPerformanceAgRadar() {\n  return (\n    <Widget\n      widget={RadarChart({\n        data: {\n          labels: [\"Speed\", \"Quality\", \"Communication\", \"Innovation\", \"Reliability\"],\n          datasets: [\n            { legend: \"Frontend\", values: [88, 82, 90, 85, 78] },\n            { legend: \"Backend\", values: [75, 95, 72, 70, 92] },\n            { legend: \"DevOps\", values: [80, 88, 68, 75, 98] },\n          ],\n        },\n        config: {},\n      })}\n      width=\"100%\"\n      height=\"100%\"\n    />\n  );\n}\n";
