// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _AssessmentOverviewAg from "./examples/assessment-overview";
import _AthleteProfileAgRadar from "./examples/athlete-profile";
import _BasicAgRadarChart from "./examples/basic-radar";
import _ProductReviewAgRadar from "./examples/product-review";
import _SkillComparisonAgRadar from "./examples/skill-comparison";
import _TeamPerformanceAgRadar from "./examples/team-performance";

const _AssessmentOverviewAg_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Analytics", "Strategy", "Delivery", "Communication", "Leadership"],
    datasets: [
      { legend: "Self", values: [82, 78, 90, 85, 70] },
      { legend: "Manager", values: [75, 88, 85, 80, 82] },
      { legend: "Peer", values: [80, 72, 88, 92, 68] },
    ],
  },
  config: {
    background: "#f8fafc",
  },
});`;
const _AthleteProfileAgRadar_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Speed", "Strength", "Endurance", "Agility", "Flexibility"],
    datasets: [
      { legend: "Sprinter", values: [98, 75, 50, 90, 60] },
      { legend: "Marathoner", values: [70, 55, 98, 65, 75] },
      { legend: "Gymnast", values: [72, 68, 60, 95, 98] },
    ],
  },
  config: {
    background: "#1e293b",
    colors: { fills: ["#fb923c", "#38bdf8", "#4ade80"] },
    radar: {
      fillOpacity: 0.15,
      strokeWidth: 2.5,
      gridColor: "rgba(255, 255, 255, 0.1)",
      axisColor: "rgba(255, 255, 255, 0.15)",
    },
    axis: { label: { color: "#94a3b8" } },
  },
});`;
const _BasicAgRadarChart_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["JavaScript", "TypeScript", "React", "Node.js", "CSS", "GraphQL", "Testing", "DevOps"],
    datasets: [
      { legend: "Senior Dev", values: [95, 90, 85, 80, 70, 75, 80, 65] },
      { legend: "Junior Dev", values: [70, 50, 60, 40, 65, 30, 35, 20] },
      { legend: "Full Stack", values: [80, 75, 70, 85, 60, 65, 70, 80] },
    ],
  },
  config: {},
});`;
const _ProductReviewAgRadar_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Price", "Quality", "Design", "Durability", "Support"],
    datasets: [
      { legend: "Product A", values: [60, 90, 85, 95, 70] },
      { legend: "Product B", values: [85, 70, 75, 60, 90] },
      { legend: "Product C", values: [75, 80, 90, 80, 65] },
    ],
  },
  config: {
    title: { text: "Product Comparison", visible: true },
    subtitle: { text: "Across 5 key dimensions", visible: true },
    radar: { fillOpacity: 0.15 },
  },
});`;
const _SkillComparisonAgRadar_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Leadership", "Problem Solving", "Communication", "Technical", "Creativity", "Teamwork"],
    datasets: [
      { legend: "Alice", values: [90, 85, 95, 70, 80, 92] },
      { legend: "Bob", values: [75, 92, 60, 95, 65, 78] },
    ],
  },
  config: {
    background: "#f0f9ff",
    radar: { fillOpacity: 0.2, strokeWidth: 2.5 },
  },
});`;
const _TeamPerformanceAgRadar_code = `import RadarChart from "./charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Speed", "Quality", "Communication", "Innovation", "Reliability"],
    datasets: [
      { legend: "Frontend", values: [88, 82, 90, 85, 78] },
      { legend: "Backend", values: [75, 95, 72, 70, 92] },
      { legend: "DevOps", values: [80, 88, 68, 75, 98] },
    ],
  },
  config: {
    colors: { fills: ["#7c3aed", "#e11d48", "#0891b2"] },
    radar: { fillOpacity: 0.4, strokeWidth: 3 },
  },
});`;

export const BasicAgRadarChart = { Component: _BasicAgRadarChart, code: _BasicAgRadarChart_code };
export const SkillComparisonAgRadar = { Component: _SkillComparisonAgRadar, code: _SkillComparisonAgRadar_code };
export const ProductReviewAgRadar = { Component: _ProductReviewAgRadar, code: _ProductReviewAgRadar_code };
export const TeamPerformanceAgRadar = { Component: _TeamPerformanceAgRadar, code: _TeamPerformanceAgRadar_code };
export const AthleteProfileAgRadar = { Component: _AthleteProfileAgRadar, code: _AthleteProfileAgRadar_code };
export const AssessmentOverviewAg = { Component: _AssessmentOverviewAg, code: _AssessmentOverviewAg_code };
