import type { Meta, StoryObj } from "@storybook/react";
import DualRenderer from "../../components/DualRenderer";
import type { FlowEdge, FlowNode } from "flitter-diagram";
// The CLI output of `flitter add flow-diagram`, regenerated by
// `pnpm --dir shared/diagram-presets run sync`. Rendering it here proves the
// copied template behaves like the in-repo style.
import { FlowDiagram } from "diagram-presets";

const meta = {
  title: "Diagram/CLI preset",
  component: DualRenderer,
  parameters: { chromatic: { delay: 500 } },
} satisfies Meta<typeof DualRenderer>;
export default meta;
type Story = StoryObj<typeof meta>;

const nodes: FlowNode[] = [
  { id: "1", type: "input", position: { x: 100, y: 50 }, data: { label: "Installed via CLI" } },
  { id: "2", position: { x: 100, y: 180 }, data: { label: "flow-diagram" }, resizable: true },
  { id: "3", type: "output", position: { x: 320, y: 180 }, data: { label: "xyflow style" } },
];
const edges: FlowEdge[] = [
  { id: "e1-2", source: "1", target: "2" },
  { id: "e1-3", source: "1", target: "3", label: "preset", markerEnd: "arrowclosed" },
];

export const FromPreset: Story = {
  args: {
    width: "560px",
    height: "400px",
    widget: FlowDiagram({
      nodes,
      edges,
      fitView: true,
      onInit: (controller) => {
        if (typeof window !== "undefined") ((window as any).__flows ??= []).push(controller);
      },
    }),
    description: "Rendered from shared/diagram-presets, the copy produced by `flitter add flow-diagram --style xyflow`.",
  },
};
