// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _CashFlowToastArea from "./examples/cash-flow-toast-area";
import _DefaultToastAreaChart from "./examples/default-toast-area-chart";
import _EnergyConsumptionToastArea from "./examples/energy-consumption-toast-area";
import _GrowthAnalyticsToastArea from "./examples/growth-analytics-toast-area";
import _NetworkTrafficToastArea from "./examples/network-traffic-toast-area";
import _RevenueGrowthToastArea from "./examples/revenue-growth-toast-area";
import _SplineToastAreaChart from "./examples/spline-toast-area-chart";
import _UserEngagementToastArea from "./examples/user-engagement-toast-area";

const _CashFlowToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"],
    datasets: [
      { legend: "Operating", values: [120, -45, 80, -30, 150, -60, 95, 200] },
      { legend: "Net P&L", values: [60, -90, 25, -55, 70, -110, 40, 130] },
    ],
  },
  config: {
    colors: ["#10b981", "#ef4444"],
    area: {
      strokeWidth: 2,
      opacity: 0.3,
      spline: false,
    },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }) => {
      const value = parseFloat(name);
      const isNegative = value < 0;
      const isZero = value === 0;
      return Text(name, {
        style: new TextStyle({
          fontSize: 11,
          color: isZero ? "#475569" : isNegative ? "#ef4444" : "#10b981",
          fontWeight: isZero ? "700" : isNegative ? "600" : undefined,
        }),
      });
    },
  },
});`;
const _DefaultToastAreaChart_code = `import ToastAreaChart from "./charts/toast-area-chart";
import { Transform, Alignment, Text, TextStyle } from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    datasets: [
      { legend: "Housing starts (MoM %)", values: [0, 12.38, -15.46, 5.56, -4.98, 0.84, -4.67, 9.96, -2.44, -0.37, -4.22, 16.91] },
      { legend: "Unemployment rate Δ (pp)", values: [0, 11.2, -8.4, 6.9, -5.8, 7.5, -6.2, 4.9, -4.1, 8.1, -5.6, 7.2] },
      { legend: "CPI MoM (1/10 index pts)", values: [0, 12.69, 13.78, 6.78, 1.52, -1.31, 5.25, 4.93, 6.70, 8.99, 8.97, 10.76] },
    ],
  },
  config: {
    area: {
      strokeWidth: 2,
      opacity: 0.3,
      spline: false,
    },
  },
  custom: {
    xAxisLabel: ({ name }: { name: string; index: number }) =>
      Transform.rotate({
        angle: -Math.PI / 6,
        alignment: Alignment.centerRight,
        child: Text(name, {
          style: new TextStyle({
            fontSize: 10,
            color: "#64748b",
          }),
        }),
      }),
  },
});`;
const _EnergyConsumptionToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  BorderRadius,
} from "flitter-ui";

const colors = ["#eab308", "#22c55e", "#64748b"];
const icons = ["\\u2600", "\\u{1F32C}", "\\u26A1"];

const chart = ToastAreaChart({
  data: {
    labels: ["Jan", "Mar", "May", "Jul", "Sep", "Nov"],
    datasets: [
      { legend: "Solar (MWh)", values: [120, 210, 420, 510, 350, 150] },
      { legend: "Wind (MWh)", values: [380, 310, 220, 160, 240, 360] },
      { legend: "Grid (MWh)", values: [500, 440, 320, 280, 370, 470] },
    ],
  },
  config: {
    colors,
    area: {
      strokeWidth: 2,
      opacity: 0.35,
      spline: true,
    },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 18,
            height: 18,
            decoration: new BoxDecoration({
              color: colors[index] + "20",
              borderRadius: BorderRadius.circular(4),
            }),
            child: Text(icons[index], {
              style: new TextStyle({ fontSize: 10 }),
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "#475569",
            }),
          }),
        ],
      }),
  },
});`;
const _GrowthAnalyticsToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import {
  Row,
  Container,
  BoxDecoration,
  SizedBox,
  Text,
  TextStyle,
  CrossAxisAlignment,
  EdgeInsets,
  BorderRadius,
} from "flitter-ui";

const colors = ["#0ea5e9", "#8b5cf6", "#f59e0b"];
const latestValues = ["$76K", "$900K", "128%"];

const chart = ToastAreaChart({
  data: {
    labels: ["Q1", "Q2", "Q3", "Q4", "Q5", "Q6", "Q7", "Q8"],
    datasets: [
      { legend: "MRR ($K)", values: [18, 24, 31, 38, 47, 55, 64, 76] },
      { legend: "ARR ($K)", values: [210, 280, 365, 450, 560, 650, 760, 900] },
      { legend: "NRR (%)", values: [105, 108, 112, 115, 118, 121, 124, 128] },
    ],
  },
  config: {
    colors: ["#0ea5e9", "#8b5cf6", "#f59e0b"],
    title: { text: "Growth Metrics", visible: true },
    area: {
      strokeWidth: 2,
      opacity: 0.25,
      spline: false,
    },
  },
  custom: {
    legend: ({ name, index }: { name: string; index: number }) =>
      Row({
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container({
            width: 8,
            height: 8,
            decoration: new BoxDecoration({
              color: colors[index],
              borderRadius: BorderRadius.circular(4),
            }),
          }),
          SizedBox({ width: 6 }),
          Text(name, {
            style: new TextStyle({
              fontSize: 11,
              color: "#475569",
            }),
          }),
          SizedBox({ width: 4 }),
          Text(latestValues[index] ?? "", {
            style: new TextStyle({
              fontSize: 11,
              color: "#0ea5e9",
              fontWeight: "600",
            }),
          }),
        ],
      }),
  },
});`;
const _NetworkTrafficToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import {
  Column,
  Container,
  BoxDecoration,
  Text,
  TextStyle,
  SizedBox,
  MainAxisSize,
  EdgeInsets,
  Border,
  BorderSide,
} from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"],
    datasets: [
      { legend: "Inbound (Gbps)", values: [2.1, 0.8, 1.8, 6.2, 8.1, 5.2] },
      { legend: "Outbound (Gbps)", values: [1.8, 0.5, 1.5, 5.5, 7.2, 4.5] },
    ],
  },
  config: {
    colors: ["#3b82f6", "#f97316"],
    area: {
      strokeWidth: 1.5,
      opacity: 0.15,
      spline: true,
    },
  },
  custom: {
    title: () =>
      Container({
        padding: EdgeInsets.only({ left: 8, bottom: 8 }),
        decoration: new BoxDecoration({
          border: new Border({
            left: new BorderSide({ color: "#3b82f6", width: 3 }),
          }),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          children: [
            Text("Network Traffic", {
              style: new TextStyle({
                fontSize: 14,
                fontWeight: "700",
                color: "#1e293b",
              }),
            }),
            SizedBox({ height: 2 }),
            Text("24-hour bandwidth monitor", {
              style: new TextStyle({
                fontSize: 11,
                color: "#94a3b8",
              }),
            }),
          ],
        }),
      }),
  },
});`;
const _RevenueGrowthToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["Q1 '23", "Q2 '23", "Q3 '23", "Q4 '23", "Q1 '24", "Q2 '24", "Q3 '24", "Q4 '24"],
    datasets: [
      { legend: "Revenue ($M)", values: revenueValues },
      { legend: "Costs ($M)", values: costValues },
    ],
  },
  config: {
    colors: ["#10b981", "#f43f5e"],
    title: { text: "Revenue vs Costs", visible: true },
    area: {
      strokeWidth: 2,
      opacity: 0.4,
      spline: false,
    },
  },
  custom: {
    dataLabel: (
      { value, label, legend }: { value: number; label: string; legend: string },
      context: any,
    ) => {
      const labels = context.data?.labels ?? [];
      const isLast = label === labels[labels.length - 1];
      if (!isLast) return Text("", { style: new TextStyle({}) });
      return Text(\`$\${value}M\`, {
        style: new TextStyle({
          fontSize: 10,
          fontWeight: "700",
          color: legend === "Revenue ($M)" ? "#10b981" : "#f43f5e",
        }),
      });
    },
  },
});`;
const _SplineToastAreaChart_code = `import ToastAreaChart from "./charts/toast-area-chart";
import {
  Container,
  BoxDecoration,
  Text,
  TextStyle,
  EdgeInsets,
  BorderRadius,
} from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Housing starts (MoM %)", values: [0, 12.38, -15.46, 5.56, -4.98, 0.84, -4.67, 9.96, -2.44, -0.37, -4.22, 16.91] },
      { legend: "Unemployment rate Δ (pp)", values: [0, 11.2, -8.4, 6.9, -5.8, 7.5, -6.2, 4.9, -4.1, 8.1, -5.6, 7.2] },
      { legend: "CPI MoM (1/10 index pts)", values: [0, 12.69, 13.78, 6.78, 1.52, -1.31, 5.25, 4.93, 6.70, 8.99, 8.97, 10.76] },
    ],
  },
  config: {
    colors: ["#8b5cf6", "#06b6d4"],
    area: {
      opacity: 0.2,
      spline: true,
      strokeWidth: 2,
    },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }) => {
      const isQuarterStart = index % 3 === 0;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 4, vertical: 2 }),
        decoration: new BoxDecoration({
          color: isQuarterStart ? "#f1f5f9" : undefined,
          borderRadius: BorderRadius.circular(4),
        }),
        child: Text(name, {
          style: new TextStyle({
            fontSize: 10,
            color: isQuarterStart ? "#6366f1" : "#94a3b8",
            fontWeight: isQuarterStart ? "600" : undefined,
          }),
        }),
      });
    },
  },
});`;
const _UserEngagementToastArea_code = `import ToastAreaChart from "./charts/toast-area-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = ToastAreaChart({
  data: {
    labels: ["Jan", "Mar", "May", "Jul", "Sep", "Nov"],
    datasets: [
      { legend: "DAU (K)", values: [12, 15, 22, 28, 27, 35] },
      { legend: "WAU (K)", values: [45, 55, 70, 85, 82, 102] },
      { legend: "MAU (K)", values: [120, 140, 175, 210, 215, 260] },
    ],
  },
  config: {
    colors: ["#6366f1", "#ec4899", "#f59e0b"],
    title: { text: "User Engagement", visible: true },
    area: {
      strokeWidth: 2.5,
      opacity: 0.25,
      spline: false,
    },
  },
  custom: {
    yAxisLabel: ({ name }: { name: string; index: number }) => {
      const value = parseFloat(name);
      return Text(value >= 1000 ? \`\${(value / 1000).toFixed(0)}K\` : name, {
        style: new TextStyle({
          fontSize: 11,
          color: value >= 200 ? "#6366f1" : "#94a3b8",
          fontWeight: value >= 200 ? "600" : undefined,
        }),
      });
    },
  },
});`;

export const DefaultToastAreaChart = { Component: _DefaultToastAreaChart, code: _DefaultToastAreaChart_code };
export const SplineToastAreaChart = { Component: _SplineToastAreaChart, code: _SplineToastAreaChart_code };
export const RevenueGrowthToastArea = { Component: _RevenueGrowthToastArea, code: _RevenueGrowthToastArea_code };
export const NetworkTrafficToastArea = { Component: _NetworkTrafficToastArea, code: _NetworkTrafficToastArea_code };
export const UserEngagementToastArea = { Component: _UserEngagementToastArea, code: _UserEngagementToastArea_code };
export const EnergyConsumptionToastArea = { Component: _EnergyConsumptionToastArea, code: _EnergyConsumptionToastArea_code };
export const GrowthAnalyticsToastArea = { Component: _GrowthAnalyticsToastArea, code: _GrowthAnalyticsToastArea_code };
export const CashFlowToastArea = { Component: _CashFlowToastArea, code: _CashFlowToastArea_code };
