// Auto-generated by scripts/generate-example-strings.mjs
// Do not edit manually. Run: npm run gen:examples

import _BasicHeatmapAg from "./examples/basic-heatmap";
import _CorrelationMatrixAg from "./examples/correlation-matrix";
import _GithubActivityAg from "./examples/github-activity";
import _SalesByRegionAg from "./examples/sales-by-region";
import _ServerLoadMonitorAg from "./examples/server-load-monitor";
import _ServerLoadAg from "./examples/server-load";

const _BasicHeatmapAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import { Text, TextStyle, Column, MainAxisSize, CrossAxisAlignment, SizedBox, Container, BoxDecoration, BorderRadius, EdgeInsets } from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    yLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    values: [
      [2, 5, 8, 12, 18, 24, 28, 30, 25, 16, 9, 4],
      [3, 6, 9, 13, 19, 25, 29, 31, 26, 17, 10, 5],
      [4, 7, 11, 15, 21, 27, 32, 34, 28, 19, 12, 6],
      [5, 8, 12, 16, 22, 28, 33, 35, 29, 20, 13, 7],
      [4, 7, 10, 14, 20, 26, 31, 33, 27, 18, 11, 6],
      [3, 5, 8, 11, 17, 23, 27, 29, 24, 15, 9, 4],
      [2, 4, 7, 10, 16, 22, 26, 28, 23, 14, 8, 3],
    ],
  },
  config: {
    heatmap: { colorRange: ["#eff6ff", "#60a5fa", "#1e40af"] },
  },
  custom: {
    title: (_args: undefined, context: any) => {
      const { font, title } = context.config;
      return Container({
        padding: EdgeInsets.symmetric({ horizontal: 12, vertical: 6 }),
        decoration: new BoxDecoration({
          color: "#eff6ff",
          borderRadius: BorderRadius.circular(6),
        }),
        child: Column({
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text("Weekly Temperature", {
              style: new TextStyle({
                fontFamily: title?.fontFamily ?? font.family,
                fontSize: 14,
                fontWeight: "700",
                color: "#1e40af",
              }),
            }),
            SizedBox({ height: 2 }),
            Text("Avg. daily highs in Celsius", {
              style: new TextStyle({
                fontFamily: font.family,
                fontSize: 10,
                color: "#3b82f6",
              }),
            }),
          ],
        }),
      });
    },
  },
});`;
const _CorrelationMatrixAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  Center,
  Text,
  TextStyle,
  EdgeInsets,
} from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["Rev", "Users", "Sess", "Bounce", "Dur", "Pages"],
    yLabels: ["Rev", "Users", "Sess", "Bounce", "Dur", "Pages"],
    values: [
      [100, 85, 78, -45, 62, 70],
      [85, 100, 92, -52, 58, 75],
      [78, 92, 100, -60, 65, 82],
      [-45, -52, -60, 100, -38, -55],
      [62, 58, 65, -38, 100, 72],
      [70, 75, 82, -55, 72, 100],
    ],
  },
  config: {
    heatmap: { colorRange: ["#ef4444", "#f5f5f5", "#3b82f6"], segment: { gap: 2 } },
  },
  custom: {
    segment: ({ value, xIndex, yIndex }: { value: number; xIndex: number; yIndex: number }, _context: any) => {
      const isDiag = xIndex === yIndex;
      const isUpper = xIndex > yIndex;
      if (isUpper) {
        return Container({
          decoration: new BoxDecoration({ color: "transparent" }),
        });
      }
      const abs = Math.abs(value);
      const isNeg = value < 0;
      const bg = isDiag
        ? "#334155"
        : isNeg
          ? \`rgba(239,68,68,\${abs / 110})\`
          : \`rgba(59,130,246,\${abs / 110})\`;
      return Container({
        margin: EdgeInsets.all(1),
        decoration: new BoxDecoration({
          color: bg,
          borderRadius: BorderRadius.circular(isDiag ? 0 : 4),
        }),
        child: Center({
          child: Text(isDiag ? "1.0" : (value / 100).toFixed(1), {
            style: new TextStyle({
              fontSize: 10,
              color: isDiag || abs > 50 ? "#ffffff" : "#374151",
              fontWeight: isDiag ? "700" : "400",
            }),
          }),
        }),
      });
    },
  },
});`;
const _GithubActivityAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import { Text, TextStyle } from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    yLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    values: [
      [3, 0, 5, 2, 8, 1, 0, 4, 6, 9, 2, 1],
      [0, 7, 3, 0, 2, 5, 1, 0, 8, 3, 0, 4],
      [5, 2, 0, 6, 1, 0, 9, 3, 2, 0, 7, 2],
      [1, 0, 4, 3, 0, 8, 2, 7, 0, 5, 1, 0],
      [0, 3, 1, 0, 5, 2, 0, 1, 4, 0, 3, 6],
      [2, 1, 0, 0, 1, 0, 3, 0, 1, 2, 0, 0],
      [0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0],
    ],
  },
  config: {
    heatmap: { colorRange: ["#ebedf0", "#9be9a8", "#216e39"], segment: { gap: 2 } },
  },
  custom: {
    xAxisLabel: ({ name, index }: { name: string; index: number }, context: any) => {
      const { font } = context.config;
      const short = name.substring(0, 1);
      const isQ = index % 3 === 0;
      return Text(isQ ? name : short, {
        style: new TextStyle({
          fontFamily: font.family,
          fontSize: isQ ? font.size : font.size - 1,
          fontWeight: isQ ? "700" : "normal",
          color: isQ ? "#216e39" : "#9ca3af",
        }),
      });
    },
  },
});`;
const _SalesByRegionAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import {
  Container,
  BoxDecoration,
  BorderRadius,
  Center,
  Text,
  TextStyle,
  Column,
  MainAxisSize,
  SizedBox,
  EdgeInsets,
} from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["Elec", "Cloth", "Food", "Furn", "Sports", "Books"],
    yLabels: ["NA", "EU", "APAC", "LATAM", "ME"],
    values: [
      [420, 280, 350, 180, 220, 150],
      [380, 310, 290, 160, 190, 200],
      [510, 260, 400, 120, 170, 130],
      [180, 220, 310, 90, 140, 80],
      [150, 170, 250, 110, 200, 60],
    ],
  },
  config: {
    heatmap: { colorRange: ["#fef3c7", "#f59e0b", "#92400e"], segment: { gap: 2 } },
  },
  custom: {
    segment: ({ value }: { value: number; xIndex: number; yIndex: number }, _context: any) => {
      const max = 510;
      const t = Math.min(value / max, 1);
      const r = Math.round(254 + (146 - 254) * t);
      const g = Math.round(243 + (64 - 243) * t);
      const b = Math.round(199 + (14 - 199) * t);
      const isTop = value >= 400;
      return Container({
        margin: EdgeInsets.all(1),
        decoration: new BoxDecoration({
          color: \`rgb(\${r},\${g},\${b})\`,
          borderRadius: BorderRadius.circular(6),
        }),
        child: Center({
          child: Column({
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(isTop ? "$" + value : \`\${value}\`, {
                style: new TextStyle({
                  fontSize: isTop ? 11 : 9,
                  color: t > 0.5 ? "#ffffff" : "#78350f",
                  fontWeight: isTop ? "700" : "400",
                }),
              }),
              ...(isTop
                ? [
                    SizedBox({ height: 1 }),
                    Text("TOP", {
                      style: new TextStyle({
                        fontSize: 6,
                        color: "#fef3c7",
                        fontWeight: "700",
                      }),
                    }),
                  ]
                : []),
            ],
          }),
        }),
      });
    },
  },
});`;
const _ServerLoadMonitorAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import {
  Container,
  BoxDecoration,
  Border,
  Center,
  Text,
  TextStyle,
} from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["00", "04", "08", "12", "16", "20"],
    yLabels: ["web-01", "web-02", "api-01", "api-02", "db-01", "cache"],
    values: [
      [15, 8, 72, 85, 68, 30],
      [12, 6, 78, 90, 72, 25],
      [20, 10, 65, 80, 55, 35],
      [18, 9, 70, 82, 60, 32],
      [40, 25, 88, 95, 82, 50],
      [8, 4, 45, 60, 38, 15],
    ],
  },
  config: {
    title: { text: "Infrastructure Dashboard", visible: true },
    background: "#111827",
    heatmap: { segment: { gap: 2 } },
  },
  custom: {
    segment: ({ value }: { value: number; xIndex: number; yIndex: number }, _context: any) => {
      const status = value >= 90 ? "critical" : value >= 75 ? "warning" : value >= 50 ? "elevated" : "normal";
      const bgMap: Record<string, string> = {
        critical: "#dc2626",
        warning: "#d97706",
        elevated: "#2563eb",
        normal: "#1e3a5f",
      };
      const borderColor = status === "critical" ? "#fca5a5" : status === "warning" ? "#fcd34d" : "transparent";
      return Container({
        decoration: new BoxDecoration({
          color: bgMap[status],
          border: status === "critical" || status === "warning"
            ? Border.all({ color: borderColor, width: 2 })
            : undefined,
        }),
        child: Center({
          child: Text(
            status === "critical" ? \`!! \${value}%\` : \`\${value}%\`,
            {
              style: new TextStyle({
                fontSize: 9,
                color: "#ffffff",
                fontWeight: status === "critical" ? "800" : status === "warning" ? "600" : "400",
              }),
            },
          ),
        }),
      });
    },
  },
});`;
const _ServerLoadAg_code = `import HeatmapChart from "./charts/heatmap-chart";
import {
  Container,
  BoxDecoration,
  Center,
  Text,
  TextStyle,
} from "flitter-ui";

const chart = HeatmapChart({
  data: {
    xLabels: ["00", "02", "04", "06", "08", "10", "12", "14", "16", "18", "20", "22"],
    yLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    values: [
      [12, 8, 5, 15, 65, 82, 78, 85, 80, 72, 45, 20],
      [10, 7, 4, 18, 70, 88, 82, 90, 85, 68, 42, 18],
      [14, 9, 6, 20, 72, 85, 80, 88, 82, 70, 48, 22],
      [11, 8, 5, 17, 68, 80, 75, 82, 78, 65, 40, 19],
      [15, 10, 7, 22, 75, 90, 85, 92, 88, 74, 50, 25],
      [8, 5, 3, 10, 25, 35, 40, 38, 32, 28, 20, 12],
      [6, 4, 2, 8, 18, 28, 32, 30, 25, 22, 15, 9],
    ],
  },
  config: {
    background: "#0f172a",
    title: { text: "Server CPU", visible: true },
  },
  custom: {
    segment: ({ value }: { value: number; xIndex: number; yIndex: number }, _context: any) => {
      const t = Math.min(value / 95, 1);
      const bg = value >= 85
        ? \`rgba(239,68,68,\${0.7 + t * 0.3})\`
        : value >= 60
          ? \`rgba(251,191,36,\${0.4 + t * 0.4})\`
          : \`rgba(56,189,248,\${0.1 + t * 0.5})\`;
      return Container({
        decoration: new BoxDecoration({ color: bg }),
        child: Center({
          child: Text(\`\${value}%\`, {
            style: new TextStyle({
              fontSize: 8,
              color: value >= 60 ? "#ffffff" : "rgba(255,255,255,0.6)",
              fontWeight: value >= 85 ? "700" : "400",
            }),
          }),
        }),
      });
    },
  },
});`;

export const BasicHeatmapAg = { Component: _BasicHeatmapAg, code: _BasicHeatmapAg_code };
export const ServerLoadAg = { Component: _ServerLoadAg, code: _ServerLoadAg_code };
export const CorrelationMatrixAg = { Component: _CorrelationMatrixAg, code: _CorrelationMatrixAg_code };
export const GithubActivityAg = { Component: _GithubActivityAg, code: _GithubActivityAg_code };
export const SalesByRegionAg = { Component: _SalesByRegionAg, code: _SalesByRegionAg_code };
export const ServerLoadMonitorAg = { Component: _ServerLoadMonitorAg, code: _ServerLoadMonitorAg_code };
