// Auto-generated by scripts/generate-gallery.mjs
// Do not edit manually. Run: npm run gen:gallery

import _AreaChartAg from "./entries/area-chart-ag";
import _AreaChartToast from "./entries/area-chart-toast";
import _BarChartAg from "./entries/bar-chart-ag";
import _BarChartToast from "./entries/bar-chart-toast";
import _BubbleChartAg from "./entries/bubble-chart-ag";
import _BubbleChartToast from "./entries/bubble-chart-toast";
import _DonutChartAg from "./entries/donut-chart-ag";
import _DonutChartToast from "./entries/donut-chart-toast";
import _HeatmapChartAg from "./entries/heatmap-chart-ag";
import _HeatmapChartToast from "./entries/heatmap-chart-toast";
import _LineChartAg from "./entries/line-chart-ag";
import _LineChartToast from "./entries/line-chart-toast";
import _PieChartAg from "./entries/pie-chart-ag";
import _PieChartToast from "./entries/pie-chart-toast";
import _RadarChartAg from "./entries/radar-chart-ag";
import _RadarChartToast from "./entries/radar-chart-toast";
import _ScatterChartAg from "./entries/scatter-chart-ag";
import _ScatterChartToast from "./entries/scatter-chart-toast";
import _StackedAreaChartAg from "./entries/stacked-area-chart-ag";
import _StackedAreaChartToast from "./entries/stacked-area-chart-toast";
import _StackedBarChartAg from "./entries/stacked-bar-chart-ag";
import _StackedBarChartToast from "./entries/stacked-bar-chart-toast";
import _SunburstChartAg from "./entries/sunburst-chart-ag";
import _SunburstChartToast from "./entries/sunburst-chart-toast";
import _TreemapChartAg from "./entries/treemap-chart-ag";
import _TreemapChartToast from "./entries/treemap-chart-toast";

const _AreaChartAg_files = [
  { filename: "index.tsx", code: `import AreaChart from "@/components/flitter/charts/area-chart";

const chart = AreaChart({
  data: {
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    datasets: [
      { legend: "Organic", values: [4200, 4800, 5100, 4900, 5300, 6100, 5800] },
      { legend: "Paid", values: [2100, 2400, 2800, 3100, 2700, 3500, 3200] },
    ],
  },
  config: {
    title: { text: "Website Traffic", visible: true },
  },
});` },
];

const _AreaChartToast_files = [
  { filename: "index.tsx", code: `import ToastAreaChart from "@/components/flitter/charts/toast-area-chart";

const chart = ToastAreaChart({
  data: {
    labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    datasets: [
      { legend: "Organic", values: [4200, 4800, 5100, 4900, 5300, 6100, 5800] },
      { legend: "Paid", values: [2100, 2400, 2800, 3100, 2700, 3500, 3200] },
    ],
  },
  config: {
    title: { text: "Website Traffic", visible: true },
  },
});` },
];

const _BarChartAg_files = [
  { filename: "index.tsx", code: `import BarChart from "@/components/flitter/charts/bar-chart";

const chart = BarChart({
  data: {
    labels: ["Q1", "Q2", "Q3", "Q4", "H1", "H2"],
    datasets: [
      { legend: "2024 Revenue", values: [42, 51, 47, 58, 93, 105] },
      { legend: "2023 Revenue", values: [38, 44, 41, 49, 82, 90] },
    ],
  },
  config: {
    title: { text: "Quarterly Revenue ($M)", visible: true },
  },
});` },
];

const _BarChartToast_files = [
  { filename: "index.tsx", code: `import ToastBarChart from "@/components/flitter/charts/toast-bar-chart";

const chart = ToastBarChart({
  data: {
    labels: ["Q1", "Q2", "Q3", "Q4", "H1", "H2"],
    datasets: [
      { legend: "2024 Revenue", values: [42, 51, 47, 58, 93, 105] },
      { legend: "2023 Revenue", values: [38, 44, 41, 49, 82, 90] },
    ],
  },
  config: {
    title: { text: "Quarterly Revenue ($M)", visible: true },
  },
});` },
];

const _BubbleChartAg_files = [
  { filename: "index.tsx", code: `import BubbleChart from "@/components/flitter/charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "North America",
        data: [
          { x: 62000, y: 78.5, value: 331000000, label: "USA" },
          { x: 48000, y: 82.3, value: 38000000, label: "Canada" },
          { x: 19000, y: 75.1, value: 128000000, label: "Mexico" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 46000, y: 81.2, value: 83000000, label: "Germany" },
          { x: 42000, y: 82.7, value: 67000000, label: "France" },
          { x: 34000, y: 83.5, value: 60000000, label: "Italy" },
          { x: 41000, y: 81.3, value: 67000000, label: "UK" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 40000, y: 84.6, value: 126000000, label: "Japan" },
          { x: 31000, y: 83.4, value: 52000000, label: "South Korea" },
          { x: 12000, y: 77.3, value: 1400000000, label: "China" },
        ],
      },
    ],
  },
  config: {
    title: { text: "GDP per Capita vs Life Expectancy", visible: true },
  },
});` },
];

const _BubbleChartToast_files = [
  { filename: "index.tsx", code: `import ToastBubbleChart from "@/components/flitter/charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "North America",
        data: [
          { x: 62000, y: 78.5, value: 331000000, label: "USA" },
          { x: 48000, y: 82.3, value: 38000000, label: "Canada" },
          { x: 19000, y: 75.1, value: 128000000, label: "Mexico" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 46000, y: 81.2, value: 83000000, label: "Germany" },
          { x: 42000, y: 82.7, value: 67000000, label: "France" },
          { x: 34000, y: 83.5, value: 60000000, label: "Italy" },
          { x: 41000, y: 81.3, value: 67000000, label: "UK" },
        ],
      },
      {
        legend: "Asia",
        data: [
          { x: 40000, y: 84.6, value: 126000000, label: "Japan" },
          { x: 31000, y: 83.4, value: 52000000, label: "South Korea" },
          { x: 12000, y: 77.3, value: 1400000000, label: "China" },
        ],
      },
    ],
  },
  config: {
    title: { text: "GDP per Capita vs Life Expectancy", visible: true },
  },
});` },
];

const _DonutChartAg_files = [
  { filename: "index.tsx", code: `import DonutChart from "@/components/flitter/charts/donut-chart";

const chart = DonutChart({
  data: {
    datasets: [
      { name: "Housing", value: 35 },
      { name: "Food", value: 20 },
      { name: "Transport", value: 15 },
      { name: "Entertainment", value: 12 },
      { name: "Savings", value: 10 },
      { name: "Other", value: 8 },
    ],
  },
  config: {
    title: { text: "Monthly Expenses", visible: true },
  },
});` },
];

const _DonutChartToast_files = [
  { filename: "index.tsx", code: `import ToastDonutChart from "@/components/flitter/charts/toast-donut-chart";

const chart = ToastDonutChart({
  data: {
    datasets: [
      { name: "Housing", value: 35 },
      { name: "Food", value: 20 },
      { name: "Transport", value: 15 },
      { name: "Entertainment", value: 12 },
      { name: "Savings", value: 10 },
      { name: "Other", value: 8 },
    ],
  },
  config: {
    title: { text: "Monthly Expenses", visible: true },
  },
});` },
];

const _HeatmapChartAg_files = [
  { filename: "index.tsx", code: `import HeatmapChart from "@/components/flitter/charts/heatmap-chart";

const chart = HeatmapChart({
  data: {
    xLabels: ["6am", "8am", "10am", "12pm", "2pm", "4pm", "6pm", "8pm"],
    yLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    values: [
      [2, 5, 12, 18, 15, 10, 6, 3],
      [3, 7, 14, 20, 17, 12, 8, 4],
      [1, 4, 11, 16, 14, 9, 5, 2],
      [4, 8, 15, 22, 19, 13, 9, 5],
      [5, 9, 16, 24, 21, 15, 11, 7],
      [8, 12, 20, 28, 25, 18, 14, 10],
      [6, 10, 17, 23, 20, 14, 10, 6],
    ],
  },
  config: {
    title: { text: "Activity by Day & Hour", visible: true },
  },
});` },
];

const _HeatmapChartToast_files = [
  { filename: "index.tsx", code: `import ToastHeatmapChart from "@/components/flitter/charts/toast-heatmap-chart";

const chart = ToastHeatmapChart({
  data: {
    xLabels: ["6am", "8am", "10am", "12pm", "2pm", "4pm", "6pm", "8pm"],
    yLabels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    values: [
      [2, 5, 12, 18, 15, 10, 6, 3],
      [3, 7, 14, 20, 17, 12, 8, 4],
      [1, 4, 11, 16, 14, 9, 5, 2],
      [4, 8, 15, 22, 19, 13, 9, 5],
      [5, 9, 16, 24, 21, 15, 11, 7],
      [8, 12, 20, 28, 25, 18, 14, 10],
      [6, 10, 17, 23, 20, 14, 10, 6],
    ],
  },
  config: {
    title: { text: "Activity by Day & Hour", visible: true },
  },
});` },
];

const _LineChartAg_files = [
  { filename: "index.tsx", code: `import LineChart from "@/components/flitter/charts/line-chart";

const chart = LineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "Active Users", values: [12400, 14200, 15800, 17300, 19100, 21500, 24000] },
      { legend: "New Signups", values: [3200, 3800, 4100, 4500, 5200, 5900, 6400] },
      { legend: "Churned", values: [800, 950, 870, 1100, 980, 1050, 900] },
    ],
  },
  config: {
    title: { text: "Monthly User Growth", visible: true },
  },
});` },
];

const _LineChartToast_files = [
  { filename: "index.tsx", code: `import ToastLineChart from "@/components/flitter/charts/toast-line-chart";

const chart = ToastLineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "Active Users", values: [12400, 14200, 15800, 17300, 19100, 21500, 24000] },
      { legend: "New Signups", values: [3200, 3800, 4100, 4500, 5200, 5900, 6400] },
      { legend: "Churned", values: [800, 950, 870, 1100, 980, 1050, 900] },
    ],
  },
  config: {
    title: { text: "Monthly User Growth", visible: true },
  },
});` },
];

const _PieChartAg_files = [
  { filename: "index.tsx", code: `import PieChart from "@/components/flitter/charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Apple", value: 27 },
      { name: "Samsung", value: 21 },
      { name: "Xiaomi", value: 14 },
      { name: "Oppo", value: 10 },
      { name: "Vivo", value: 8 },
      { name: "Others", value: 20 },
    ],
  },
  config: {
    title: { text: "Smartphone Market Share", visible: true },
  },
});` },
];

const _PieChartToast_files = [
  { filename: "index.tsx", code: `import ToastPieChart from "@/components/flitter/charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "Apple", value: 27 },
      { name: "Samsung", value: 21 },
      { name: "Xiaomi", value: 14 },
      { name: "Oppo", value: 10 },
      { name: "Vivo", value: 8 },
      { name: "Others", value: 20 },
    ],
  },
  config: {
    title: { text: "Smartphone Market Share", visible: true },
  },
});` },
];

const _RadarChartAg_files = [
  { filename: "index.tsx", code: `import RadarChart from "@/components/flitter/charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: ["Communication", "Problem Solving", "Leadership", "Teamwork", "Creativity", "Technical"],
    datasets: [
      { legend: "Self Assessment", values: [85, 90, 70, 80, 75, 95] },
      { legend: "Peer Review", values: [78, 85, 82, 88, 72, 80] },
    ],
  },
  config: {
    title: { text: "Skill Assessment", visible: true },
  },
});` },
];

const _RadarChartToast_files = [
  { filename: "index.tsx", code: `import ToastRadarChart from "@/components/flitter/charts/toast-radar-chart";

const chart = ToastRadarChart({
  data: {
    labels: ["Communication", "Problem Solving", "Leadership", "Teamwork", "Creativity", "Technical"],
    datasets: [
      { legend: "Self Assessment", values: [85, 90, 70, 80, 75, 95] },
      { legend: "Peer Review", values: [78, 85, 82, 88, 72, 80] },
    ],
  },
  config: {
    title: { text: "Skill Assessment", visible: true },
  },
});` },
];

const _ScatterChartAg_files = [
  { filename: "index.tsx", code: `import ScatterChart from "@/components/flitter/charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Male",
        data: [
          { x: 170, y: 68, label: "A" },
          { x: 175, y: 73, label: "B" },
          { x: 180, y: 78, label: "C" },
          { x: 168, y: 65, label: "D" },
          { x: 183, y: 82, label: "E" },
          { x: 177, y: 76, label: "F" },
          { x: 172, y: 70, label: "G" },
        ],
      },
      {
        legend: "Female",
        data: [
          { x: 158, y: 52, label: "H" },
          { x: 163, y: 57, label: "I" },
          { x: 155, y: 49, label: "J" },
          { x: 167, y: 61, label: "K" },
          { x: 160, y: 55, label: "L" },
          { x: 165, y: 59, label: "M" },
          { x: 162, y: 54, label: "N" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Height vs Weight", visible: true },
  },
});` },
];

const _ScatterChartToast_files = [
  { filename: "index.tsx", code: `import ToastScatterChart from "@/components/flitter/charts/toast-scatter-chart";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Male",
        data: [
          { x: 170, y: 68, label: "A" },
          { x: 175, y: 73, label: "B" },
          { x: 180, y: 78, label: "C" },
          { x: 168, y: 65, label: "D" },
          { x: 183, y: 82, label: "E" },
          { x: 177, y: 76, label: "F" },
          { x: 172, y: 70, label: "G" },
        ],
      },
      {
        legend: "Female",
        data: [
          { x: 158, y: 52, label: "H" },
          { x: 163, y: 57, label: "I" },
          { x: 155, y: 49, label: "J" },
          { x: 167, y: 61, label: "K" },
          { x: 160, y: 55, label: "L" },
          { x: 165, y: 59, label: "M" },
          { x: 162, y: 54, label: "N" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Height vs Weight", visible: true },
  },
});` },
];

const _StackedAreaChartAg_files = [
  { filename: "index.tsx", code: `import StackedAreaChart from "@/components/flitter/charts/stacked-area-chart";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "SaaS", values: [120, 135, 148, 162, 175, 190] },
      { legend: "Consulting", values: [80, 75, 90, 85, 95, 100] },
      { legend: "Licensing", values: [45, 50, 42, 55, 48, 60] },
    ],
  },
  config: {
    title: { text: "Revenue by Product Line ($K)", visible: true },
  },
});` },
];

const _StackedAreaChartToast_files = [
  { filename: "index.tsx", code: `import ToastStackedAreaChart from "@/components/flitter/charts/toast-stacked-area-chart";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      { legend: "SaaS", values: [120, 135, 148, 162, 175, 190] },
      { legend: "Consulting", values: [80, 75, 90, 85, 95, 100] },
      { legend: "Licensing", values: [45, 50, 42, 55, 48, 60] },
    ],
  },
  config: {
    title: { text: "Revenue by Product Line ($K)", visible: true },
  },
});` },
];

const _StackedBarChartAg_files = [
  { filename: "index.tsx", code: `import StackedBarChart from "@/components/flitter/charts/stacked-bar-chart";

const chart = StackedBarChart({
  data: {
    labels: ["Engineering", "Marketing", "Sales", "Design", "HR"],
    datasets: [
      { legend: "Salaries", values: [520, 280, 310, 190, 150] },
      { legend: "Tools", values: [85, 120, 65, 95, 30] },
      { legend: "Training", values: [45, 35, 55, 40, 60] },
    ],
  },
  config: {
    title: { text: "Department Budget Allocation ($K)", visible: true },
  },
});` },
];

const _StackedBarChartToast_files = [
  { filename: "index.tsx", code: `import ToastStackedBarChart from "@/components/flitter/charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  data: {
    labels: ["Engineering", "Marketing", "Sales", "Design", "HR"],
    datasets: [
      { legend: "Salaries", values: [520, 280, 310, 190, 150] },
      { legend: "Tools", values: [85, 120, 65, 95, 30] },
      { legend: "Training", values: [45, 35, 55, 40, 60] },
    ],
  },
  config: {
    title: { text: "Department Budget Allocation ($K)", visible: true },
  },
});` },
];

const _SunburstChartAg_files = [
  { filename: "index.tsx", code: `import SunburstChart from "@/components/flitter/charts/sunburst-chart";

const chart = SunburstChart({
  data: {
    nodes: [
      {
        label: "Engineering",
        value: 45,
        children: [
          { label: "Frontend", value: 18, children: [] },
          { label: "Backend", value: 15, children: [] },
          { label: "DevOps", value: 12, children: [] },
        ],
      },
      {
        label: "Product",
        value: 25,
        children: [
          { label: "Design", value: 10, children: [] },
          { label: "Research", value: 8, children: [] },
          { label: "Management", value: 7, children: [] },
        ],
      },
      {
        label: "Operations",
        value: 20,
        children: [
          { label: "HR", value: 8, children: [] },
          { label: "Finance", value: 7, children: [] },
          { label: "Legal", value: 5, children: [] },
        ],
      },
      {
        label: "Sales",
        value: 10,
        children: [
          { label: "Enterprise", value: 6, children: [] },
          { label: "SMB", value: 4, children: [] },
        ],
      },
    ],
  },
  config: {
    title: { text: "Organization Structure", visible: true },
  },
});` },
];

const _SunburstChartToast_files = [
  { filename: "index.tsx", code: `import ToastSunburstChart from "@/components/flitter/charts/toast-sunburst-chart";

const chart = ToastSunburstChart({
  data: {
    nodes: [
      {
        label: "Engineering",
        value: 45,
        children: [
          { label: "Frontend", value: 18, children: [] },
          { label: "Backend", value: 15, children: [] },
          { label: "DevOps", value: 12, children: [] },
        ],
      },
      {
        label: "Product",
        value: 25,
        children: [
          { label: "Design", value: 10, children: [] },
          { label: "Research", value: 8, children: [] },
          { label: "Management", value: 7, children: [] },
        ],
      },
      {
        label: "Operations",
        value: 20,
        children: [
          { label: "HR", value: 8, children: [] },
          { label: "Finance", value: 7, children: [] },
          { label: "Legal", value: 5, children: [] },
        ],
      },
      {
        label: "Sales",
        value: 10,
        children: [
          { label: "Enterprise", value: 6, children: [] },
          { label: "SMB", value: 4, children: [] },
        ],
      },
    ],
  },
  config: {
    title: { text: "Organization Structure", visible: true },
  },
});` },
];

const _TreemapChartAg_files = [
  { filename: "index.tsx", code: `import TreemapChart from "@/components/flitter/charts/treemap-chart";

const chart = TreemapChart({
  data: {
    datasets: [
      {
        legend: "Equities",
        children: [
          { label: "US Large Cap", secondaryLabel: "$45K", value: 45 },
          { label: "US Small Cap", secondaryLabel: "$15K", value: 15 },
          { label: "International", secondaryLabel: "$20K", value: 20 },
        ],
      },
      {
        legend: "Fixed Income",
        children: [
          { label: "Government", secondaryLabel: "$25K", value: 25 },
          { label: "Corporate", secondaryLabel: "$18K", value: 18 },
        ],
      },
      {
        legend: "Alternatives",
        value: 12,
        secondaryLabel: "$12K",
      },
      {
        legend: "Cash",
        value: 8,
        secondaryLabel: "$8K",
      },
    ],
  },
  config: {
    title: { text: "Portfolio Allocation", visible: true },
  },
});` },
];

const _TreemapChartToast_files = [
  { filename: "index.tsx", code: `import ToastTreemapChart from "@/components/flitter/charts/toast-treemap-chart";

const chart = ToastTreemapChart({
  data: {
    datasets: [
      {
        legend: "Equities",
        children: [
          { label: "US Large Cap", secondaryLabel: "$45K", value: 45 },
          { label: "US Small Cap", secondaryLabel: "$15K", value: 15 },
          { label: "International", secondaryLabel: "$20K", value: 20 },
        ],
      },
      {
        legend: "Fixed Income",
        children: [
          { label: "Government", secondaryLabel: "$25K", value: 25 },
          { label: "Corporate", secondaryLabel: "$18K", value: 18 },
        ],
      },
      {
        legend: "Alternatives",
        value: 12,
        secondaryLabel: "$12K",
      },
      {
        legend: "Cash",
        value: 8,
        secondaryLabel: "$8K",
      },
    ],
  },
  config: {
    title: { text: "Portfolio Allocation", visible: true },
  },
});` },
];

export type GalleryEntryGenerated = {
  slug: string;
  chartType: string;
  style: "Toast" | "AG";
  title: string;
  Component: React.ComponentType;
  thumbnailUrl: string;
  files: { filename: string; code: string }[];
  installCommand: string;
};

export const galleryEntries: GalleryEntryGenerated[] = [
  {
    slug: "area-chart-ag",
    chartType: "area-chart",
    style: "AG",
    title: "Website Traffic",
    Component: _AreaChartAg,
    thumbnailUrl: "/charts/area-chart-ag.svg",
    files: _AreaChartAg_files,
    installCommand: "npx flitter-ui add area-chart --ag",
  },
  {
    slug: "area-chart-toast",
    chartType: "area-chart",
    style: "Toast",
    title: "Website Traffic",
    Component: _AreaChartToast,
    thumbnailUrl: "/charts/area-chart-toast.svg",
    files: _AreaChartToast_files,
    installCommand: "npx flitter-ui add area-chart --toast",
  },
  {
    slug: "bar-chart-ag",
    chartType: "bar-chart",
    style: "AG",
    title: "Quarterly Revenue ($M)",
    Component: _BarChartAg,
    thumbnailUrl: "/charts/bar-chart-ag.svg",
    files: _BarChartAg_files,
    installCommand: "npx flitter-ui add bar-chart --ag",
  },
  {
    slug: "bar-chart-toast",
    chartType: "bar-chart",
    style: "Toast",
    title: "Quarterly Revenue ($M)",
    Component: _BarChartToast,
    thumbnailUrl: "/charts/bar-chart-toast.svg",
    files: _BarChartToast_files,
    installCommand: "npx flitter-ui add bar-chart --toast",
  },
  {
    slug: "bubble-chart-ag",
    chartType: "bubble-chart",
    style: "AG",
    title: "GDP per Capita vs Life Expectancy",
    Component: _BubbleChartAg,
    thumbnailUrl: "/charts/bubble-chart-ag.svg",
    files: _BubbleChartAg_files,
    installCommand: "npx flitter-ui add bubble-chart --ag",
  },
  {
    slug: "bubble-chart-toast",
    chartType: "bubble-chart",
    style: "Toast",
    title: "GDP per Capita vs Life Expectancy",
    Component: _BubbleChartToast,
    thumbnailUrl: "/charts/bubble-chart-toast.svg",
    files: _BubbleChartToast_files,
    installCommand: "npx flitter-ui add bubble-chart --toast",
  },
  {
    slug: "donut-chart-ag",
    chartType: "donut-chart",
    style: "AG",
    title: "Monthly Expenses",
    Component: _DonutChartAg,
    thumbnailUrl: "/charts/donut-chart-ag.svg",
    files: _DonutChartAg_files,
    installCommand: "npx flitter-ui add donut-chart --ag",
  },
  {
    slug: "donut-chart-toast",
    chartType: "donut-chart",
    style: "Toast",
    title: "Monthly Expenses",
    Component: _DonutChartToast,
    thumbnailUrl: "/charts/donut-chart-toast.svg",
    files: _DonutChartToast_files,
    installCommand: "npx flitter-ui add donut-chart --toast",
  },
  {
    slug: "heatmap-chart-ag",
    chartType: "heatmap-chart",
    style: "AG",
    title: "Activity by Day & Hour",
    Component: _HeatmapChartAg,
    thumbnailUrl: "/charts/heatmap-chart-ag.svg",
    files: _HeatmapChartAg_files,
    installCommand: "npx flitter-ui add heatmap-chart --ag",
  },
  {
    slug: "heatmap-chart-toast",
    chartType: "heatmap-chart",
    style: "Toast",
    title: "Activity by Day & Hour",
    Component: _HeatmapChartToast,
    thumbnailUrl: "/charts/heatmap-chart-toast.svg",
    files: _HeatmapChartToast_files,
    installCommand: "npx flitter-ui add heatmap-chart --toast",
  },
  {
    slug: "line-chart-ag",
    chartType: "line-chart",
    style: "AG",
    title: "Monthly User Growth",
    Component: _LineChartAg,
    thumbnailUrl: "/charts/line-chart-ag.svg",
    files: _LineChartAg_files,
    installCommand: "npx flitter-ui add line-chart --ag",
  },
  {
    slug: "line-chart-toast",
    chartType: "line-chart",
    style: "Toast",
    title: "Monthly User Growth",
    Component: _LineChartToast,
    thumbnailUrl: "/charts/line-chart-toast.svg",
    files: _LineChartToast_files,
    installCommand: "npx flitter-ui add line-chart --toast",
  },
  {
    slug: "pie-chart-ag",
    chartType: "pie-chart",
    style: "AG",
    title: "Smartphone Market Share",
    Component: _PieChartAg,
    thumbnailUrl: "/charts/pie-chart-ag.svg",
    files: _PieChartAg_files,
    installCommand: "npx flitter-ui add pie-chart --ag",
  },
  {
    slug: "pie-chart-toast",
    chartType: "pie-chart",
    style: "Toast",
    title: "Smartphone Market Share",
    Component: _PieChartToast,
    thumbnailUrl: "/charts/pie-chart-toast.svg",
    files: _PieChartToast_files,
    installCommand: "npx flitter-ui add pie-chart --toast",
  },
  {
    slug: "radar-chart-ag",
    chartType: "radar-chart",
    style: "AG",
    title: "Skill Assessment",
    Component: _RadarChartAg,
    thumbnailUrl: "/charts/radar-chart-ag.svg",
    files: _RadarChartAg_files,
    installCommand: "npx flitter-ui add radar-chart --ag",
  },
  {
    slug: "radar-chart-toast",
    chartType: "radar-chart",
    style: "Toast",
    title: "Skill Assessment",
    Component: _RadarChartToast,
    thumbnailUrl: "/charts/radar-chart-toast.svg",
    files: _RadarChartToast_files,
    installCommand: "npx flitter-ui add radar-chart --toast",
  },
  {
    slug: "scatter-chart-ag",
    chartType: "scatter-chart",
    style: "AG",
    title: "Height vs Weight",
    Component: _ScatterChartAg,
    thumbnailUrl: "/charts/scatter-chart-ag.svg",
    files: _ScatterChartAg_files,
    installCommand: "npx flitter-ui add scatter-chart --ag",
  },
  {
    slug: "scatter-chart-toast",
    chartType: "scatter-chart",
    style: "Toast",
    title: "Height vs Weight",
    Component: _ScatterChartToast,
    thumbnailUrl: "/charts/scatter-chart-toast.svg",
    files: _ScatterChartToast_files,
    installCommand: "npx flitter-ui add scatter-chart --toast",
  },
  {
    slug: "stacked-area-chart-ag",
    chartType: "stacked-area-chart",
    style: "AG",
    title: "Revenue by Product Line ($K)",
    Component: _StackedAreaChartAg,
    thumbnailUrl: "/charts/stacked-area-chart-ag.svg",
    files: _StackedAreaChartAg_files,
    installCommand: "npx flitter-ui add stacked-area-chart --ag",
  },
  {
    slug: "stacked-area-chart-toast",
    chartType: "stacked-area-chart",
    style: "Toast",
    title: "Revenue by Product Line ($K)",
    Component: _StackedAreaChartToast,
    thumbnailUrl: "/charts/stacked-area-chart-toast.svg",
    files: _StackedAreaChartToast_files,
    installCommand: "npx flitter-ui add stacked-area-chart --toast",
  },
  {
    slug: "stacked-bar-chart-ag",
    chartType: "stacked-bar-chart",
    style: "AG",
    title: "Department Budget Allocation ($K)",
    Component: _StackedBarChartAg,
    thumbnailUrl: "/charts/stacked-bar-chart-ag.svg",
    files: _StackedBarChartAg_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --ag",
  },
  {
    slug: "stacked-bar-chart-toast",
    chartType: "stacked-bar-chart",
    style: "Toast",
    title: "Department Budget Allocation ($K)",
    Component: _StackedBarChartToast,
    thumbnailUrl: "/charts/stacked-bar-chart-toast.svg",
    files: _StackedBarChartToast_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --toast",
  },
  {
    slug: "sunburst-chart-ag",
    chartType: "sunburst-chart",
    style: "AG",
    title: "Organization Structure",
    Component: _SunburstChartAg,
    thumbnailUrl: "/charts/sunburst-chart-ag.svg",
    files: _SunburstChartAg_files,
    installCommand: "npx flitter-ui add sunburst-chart --ag",
  },
  {
    slug: "sunburst-chart-toast",
    chartType: "sunburst-chart",
    style: "Toast",
    title: "Organization Structure",
    Component: _SunburstChartToast,
    thumbnailUrl: "/charts/sunburst-chart-toast.svg",
    files: _SunburstChartToast_files,
    installCommand: "npx flitter-ui add sunburst-chart --toast",
  },
  {
    slug: "treemap-chart-ag",
    chartType: "treemap-chart",
    style: "AG",
    title: "Portfolio Allocation",
    Component: _TreemapChartAg,
    thumbnailUrl: "/charts/treemap-chart-ag.svg",
    files: _TreemapChartAg_files,
    installCommand: "npx flitter-ui add treemap-chart --ag",
  },
  {
    slug: "treemap-chart-toast",
    chartType: "treemap-chart",
    style: "Toast",
    title: "Portfolio Allocation",
    Component: _TreemapChartToast,
    thumbnailUrl: "/charts/treemap-chart-toast.svg",
    files: _TreemapChartToast_files,
    installCommand: "npx flitter-ui add treemap-chart --toast",
  },
];

export const galleryCategories = [
  { id: "area-chart", label: "Area" },
  { id: "bar-chart", label: "Bar" },
  { id: "bubble-chart", label: "Bubble" },
  { id: "donut-chart", label: "Donut" },
  { id: "heatmap-chart", label: "Heatmap" },
  { id: "line-chart", label: "Line" },
  { id: "pie-chart", label: "Pie" },
  { id: "radar-chart", label: "Radar" },
  { id: "scatter-chart", label: "Scatter" },
  { id: "stacked-area-chart", label: "Stacked Area" },
  { id: "stacked-bar-chart", label: "Stacked Bar" },
  { id: "sunburst-chart", label: "Sunburst" },
  { id: "treemap-chart", label: "Treemap" },
];

export const todoCategories = [
  "box-plot-chart",
  "bullet-chart",
  "candlestick-chart",
  "funnel-chart",
  "histogram-chart",
  "sankey-chart",
  "waterfall-chart",
];
