// Auto-generated by scripts/generate-gallery.mjs
// Do not edit manually. Run: npm run gen:gallery

import type { Widget } from "flitter-core";
import { createWidget as _AreaChartAgProfitLoss } from "./entries/area-chart/ag/profit-loss";
import { createWidget as _AreaChartToastAppDownloads } from "./entries/area-chart/toast/app-downloads";
import { createWidget as _BarChartAgCityRent } from "./entries/bar-chart/ag/city-rent";
import { createWidget as _BarChartToastDepartmentRevenue } from "./entries/bar-chart/toast/department-revenue";
import { createWidget as _BarChartToastHorizontalPill } from "./entries/bar-chart/toast/horizontal-pill";
import { createWidget as _BoxPlotChartAgApiLatency } from "./entries/box-plot-chart/ag/api-latency";
import { createWidget as _BoxPlotChartToastDeliveryTimes } from "./entries/box-plot-chart/toast/delivery-times";
import { createWidget as _BubbleChartAgGdpLifeExpectancy } from "./entries/bubble-chart/ag/gdp-life-expectancy";
import { createWidget as _BubbleChartToastProductMargin } from "./entries/bubble-chart/toast/product-margin";
import { createWidget as _BulletChartAgRevenueTargets } from "./entries/bullet-chart/ag/revenue-targets";
import { createWidget as _BulletChartToastServiceQuality } from "./entries/bullet-chart/toast/service-quality";
import { createWidget as _CandlestickChartAgBitcoinMonthly } from "./entries/candlestick-chart/ag/bitcoin-monthly";
import { createWidget as _DonutChartAgPaymentMethods } from "./entries/donut-chart/ag/payment-methods";
import { createWidget as _DonutChartToastProjectStatus } from "./entries/donut-chart/toast/project-status";
import { createWidget as _FunnelChartAgProductOnboarding } from "./entries/funnel-chart/ag/product-onboarding";
import { createWidget as _FunnelChartToastSalesPipeline } from "./entries/funnel-chart/toast/sales-pipeline";
import { createWidget as _HeatmapChartAgHourlyTraffic } from "./entries/heatmap-chart/ag/hourly-traffic";
import { createWidget as _HeatmapChartToastMonthlyProductSales } from "./entries/heatmap-chart/toast/monthly-product-sales";
import { createWidget as _HistogramChartAgParcelWeights } from "./entries/histogram-chart/ag/parcel-weights";
import { createWidget as _HistogramChartToastResponseTimes } from "./entries/histogram-chart/toast/response-times";
import { createWidget as _LineChartAgMonthlyActiveUsers } from "./entries/line-chart/ag/monthly-active-users";
import { createWidget as _LineChartToastChannelTraffic } from "./entries/line-chart/toast/channel-traffic";
import { createWidget as _PieChartAgBrowserShare } from "./entries/pie-chart/ag/browser-share";
import { createWidget as _PieChartToastBudgetAllocation } from "./entries/pie-chart/toast/budget-allocation";
import { createWidget as _RadarChartAgSkillAssessment } from "./entries/radar-chart/ag/skill-assessment";
import { createWidget as _RadarChartToastTeamComparison } from "./entries/radar-chart/toast/team-comparison";
import { createWidget as _SankeyChartAgEnergyFlow } from "./entries/sankey-chart/ag/energy-flow";
import { createWidget as _SankeyChartToastCustomerJourney } from "./entries/sankey-chart/toast/customer-journey";
import { createWidget as _ScatterChartAgRevenueGrowth } from "./entries/scatter-chart/ag/revenue-growth";
import { createWidget as _ScatterChartToastStudentScores } from "./entries/scatter-chart/toast/student-scores";
import { createWidget as _StackedAreaChartAgMonthlyExpenses } from "./entries/stacked-area-chart/ag/monthly-expenses";
import { createWidget as _StackedAreaChartToastTrafficSources } from "./entries/stacked-area-chart/toast/traffic-sources";
import { createWidget as _StackedBarChartAgEnergyMix } from "./entries/stacked-bar-chart/ag/energy-mix";
import { createWidget as _StackedBarChartToastNivoPattern } from "./entries/stacked-bar-chart/toast/nivo-pattern";
import { createWidget as _StackedBarChartToastRegionalSales } from "./entries/stacked-bar-chart/toast/regional-sales";
import { createWidget as _SunburstChartAgOrgStructure } from "./entries/sunburst-chart/ag/org-structure";
import { createWidget as _SunburstChartToastWorldPopulation } from "./entries/sunburst-chart/toast/world-population";
import { createWidget as _TreemapChartAgDiskSpaceUsage } from "./entries/treemap-chart/ag/disk-space-usage";
import { createWidget as _TreemapChartToastGlobalRevenueBreakdown } from "./entries/treemap-chart/toast/global-revenue-breakdown";
import { createWidget as _WaterfallChartAgOperatingProfit } from "./entries/waterfall-chart/ag/operating-profit";
import { createWidget as _WaterfallChartToastProjectBudget } from "./entries/waterfall-chart/toast/project-budget";

const _AreaChartAgProfitLoss_files = [
  { filename: "index.tsx", code: `import AreaChart from "@/components/flitter/charts/area-chart";

const chart = AreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Hardware", values: [-12.4, -8.7, -3.2, 4.5, 9.8, 15.2, 18.6, 14.3, 7.1, -2.5, -9.8, -14.1] },
      { legend: "Software", values: [5.3, 8.1, 12.7, 18.4, 22.0, 25.6, 28.9, 26.2, 19.5, 11.8, 6.4, 3.1] },
      { legend: "Services", values: [-4.8, -6.2, -1.5, 3.7, 8.4, 11.0, 13.5, 9.8, 2.3, -3.6, -7.9, -10.2] },
    ],
  },
  config: {
    title: { text: "Monthly Profit & Loss by Division", visible: true, alignment: "center" },
    subtitle: { text: "Revenue minus costs ($M) — 2024", visible: true },
    area: { spline: false, strokeWidth: 2, opacity: 0.25 },
  },
});` },
];

const _AreaChartToastAppDownloads_files = [
  { filename: "index.tsx", code: `import ToastAreaChart from "@/components/flitter/charts/toast-area-chart";

const chart = ToastAreaChart({
  data: {
    labels: ["plane", "helicopter", "boat", "train", "subway", "bus", "car", "moto", "bicycle", "horse", "skateboard", "others"],
    datasets: [
      { legend: "Norway", values: [600, 1000, 800, 1000, 500, 850, 600, 675, 720, 890, 700, 950] },
      { legend: "Germany", values: [565, 850, 734, 863, 268, 571, 396, 588, 442, 726, 640, 732] },
      { legend: "US", values: [435, 559, 482, 580, 167, 308, 255, 557, 437, 438, 543, 554] },
    ],
  },
  config: {
    title: { text: "Transportation Usage by Country", visible: true, alignment: "center" },
    area: { spline: true, strokeWidth: 2, opacity: 0.3 },
  },
});` },
];

const _BarChartAgCityRent_files = [
  { filename: "index.tsx", code: `import BarChart from "@/components/flitter/charts/bar-chart";

const chart = BarChart({
  data: {
    labels: [
      "Tokyo",
      "Paris",
      "London",
      "New York",
      "Seoul",
      "Berlin",
      "Sydney",
      "Toronto",
      "Dubai",
    ],
    datasets: [
      {
        legend: "Orders",
        values: [92, 78, 85, 70, 88, 45, 63, 51, 34],
      },
    ],
  },
  config: {
    title: { text: "Weekend Coffee Orders by City", visible: true },
    legend: { visible: false },
    bar: { cornerRadius: 2 },
  },
});` },
];

const _BarChartToastDepartmentRevenue_files = [
  { filename: "index.tsx", code: `import ToastBarChart from "@/components/flitter/charts/toast-bar-chart";

const chart = ToastBarChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "Seoul", values: [65, 59, 80, 81, 56, 55, 40] },
      { legend: "Seattle", values: [28, 48, 40, 19, 86, 27, 90] },
      { legend: "Sydney", values: [35, 25, 30, 45, 35, 40, 25] },
    ],
  },
  config: {
    title: { text: "Monthly Visitors by City", visible: true },
    legend: { visible: true },
  },
});` },
];

const _BarChartToastHorizontalPill_files = [
  { filename: "index.tsx", code: `import ToastBarChart from "@/components/flitter/charts/toast-bar-chart";
import {
  Container,
  EdgeInsets,
  BoxDecoration,
  BorderRadius,
  Radius,
  Border,
  ZIndex,
  type Widget as FlitterWidget,
} from "flitter-core";
import type { BarChartContext } from "flitter-ui/chart";

const pillColors = ["#ef4444", "#10b981"];

function pillBar(
  { legend, value, isHovered }: { value: number; label: string; legend: string; index: number; isHovered: boolean },
  context: BarChartContext,
): FlitterWidget {
  const idx = context.legends.indexOf(legend);
  const baseColor = pillColors[idx % pillColors.length];
  const fillColor = baseColor + "44";
  const borderRadius = BorderRadius.all(Radius.circular(10));

  const decoration = isHovered
    ? new BoxDecoration({
        color: baseColor + "66",
        borderRadius,
        border: Border.all({ color: baseColor, width: 2 }),
      })
    : new BoxDecoration({
        color: fillColor,
        borderRadius,
        border: Border.all({ color: baseColor, width: 1.5 }),
      });

  return ZIndex({
    zIndex: isHovered ? 1 : 0,
    child: Container({
      margin: EdgeInsets.symmetric({ horizontal: 1 }),
      decoration,
    }),
  });
}

const chart = ToastBarChart({
  direction: "horizontal",
  data: {
    labels: ["Cloud", "Hardware", "Consulting", "Retail", "Media", "Logistics", "R&D", "Finance"],
    datasets: [
      { legend: "Loss", values: [-42, -18, -7, -3, -31, -12, -55, -8] },
      { legend: "Profit", values: [15, 6, 22, 26, 9, 38, 11, 64] },
    ],
  },
  custom: {
    bar: pillBar,
  },
  config: {
    colors: pillColors,
    title: { text: "Quarterly Profit / Loss by Division", visible: true },
    legend: { visible: true },
    bar: { cornerRadius: 10, gap: 1 },
  },
});` },
];

const _BoxPlotChartAgApiLatency_files = [
  { filename: "index.tsx", code: `import BoxPlotChart from "@/components/flitter/charts/box-plot-chart";

const chart = BoxPlotChart({
  data: {
    labels: ["Search", "Catalog", "Checkout", "Billing"],
    datasets: [
      {
        legend: "Baseline",
        data: [
          {
            min: 60,
            q1: 80,
            median: 95,
            q3: 120,
            max: 150,
            outliers: [195],
          },
          {
            min: 35,
            q1: 48,
            median: 60,
            q3: 76,
            max: 90,
          },
          {
            min: 120,
            q1: 160,
            median: 195,
            q3: 235,
            max: 280,
            outliers: [340],
          },
          {
            min: 70,
            q1: 95,
            median: 110,
            q3: 145,
            max: 175,
          },
        ],
      },
      {
        legend: "Peak traffic",
        data: [
          {
            min: 85,
            q1: 110,
            median: 138,
            q3: 170,
            max: 210,
          },
          {
            min: 45,
            q1: 60,
            median: 75,
            q3: 95,
            max: 120,
          },
          {
            min: 155,
            q1: 195,
            median: 230,
            q3: 280,
            max: 330,
            outliers: [390],
          },
          {
            min: 90,
            q1: 115,
            median: 140,
            q3: 175,
            max: 210,
          },
        ],
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _BoxPlotChartToastDeliveryTimes_files = [
  { filename: "index.tsx", code: `import ToastBoxPlotChart from "@/components/flitter/charts/toast-box-plot-chart";

const chart = ToastBoxPlotChart({
  data: {
    labels: ["North", "South", "East", "West"],
    datasets: [
      {
        legend: "Standard",
        data: [
          {
            min: 2,
            q1: 3,
            median: 4,
            q3: 5,
            max: 7,
            outliers: [9],
          },
          {
            min: 3,
            q1: 4,
            median: 5,
            q3: 6,
            max: 8,
          },
          {
            min: 2,
            q1: 3,
            median: 3.5,
            q3: 4.5,
            max: 6,
          },
          {
            min: 3,
            q1: 4,
            median: 5,
            q3: 7,
            max: 9,
          },
        ],
      },
      {
        legend: "Express",
        data: [
          {
            min: 1,
            q1: 1.5,
            median: 2,
            q3: 2.5,
            max: 3.5,
          },
          {
            min: 1,
            q1: 2,
            median: 2.5,
            q3: 3,
            max: 4,
          },
          {
            min: 0.5,
            q1: 1,
            median: 1.5,
            q3: 2,
            max: 3,
          },
          {
            min: 1,
            q1: 1.5,
            median: 2,
            q3: 3,
            max: 4,
            outliers: [5.5],
          },
        ],
      },
    ],
  },
  direction: "horizontal",
  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _BubbleChartAgGdpLifeExpectancy_files = [
  { filename: "index.tsx", code: `import BubbleChart from "@/components/flitter/charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 75, y: 82, value: 62, label: "China" },
          { x: 42, y: 74, value: 55, label: "India" },
          { x: 18, y: 68, value: 45, label: "Indonesia" },
          { x: 55, y: 78, value: 38, label: "Japan" },
          { x: 30, y: 71, value: 50, label: "Pakistan" },
          { x: 85, y: 84, value: 25, label: "S. Korea" },
          { x: 12, y: 65, value: 42, label: "Bangladesh" },
          { x: 48, y: 76, value: 35, label: "Thailand" },
          { x: 22, y: 70, value: 30, label: "Vietnam" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 52, y: 81, value: 48, label: "Germany" },
          { x: 45, y: 82, value: 40, label: "France" },
          { x: 60, y: 80, value: 35, label: "UK" },
          { x: 38, y: 83, value: 28, label: "Italy" },
          { x: 68, y: 81, value: 20, label: "Netherlands" },
          { x: 55, y: 79, value: 45, label: "Russia" },
          { x: 72, y: 82, value: 22, label: "Switzerland" },
          { x: 48, y: 80, value: 32, label: "Poland" },
          { x: 35, y: 78, value: 25, label: "Spain" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 65, y: 78, value: 60, label: "USA" },
          { x: 50, y: 81, value: 30, label: "Canada" },
          { x: 10, y: 72, value: 52, label: "Brazil" },
          { x: 15, y: 75, value: 35, label: "Mexico" },
          { x: 8, y: 74, value: 45, label: "Colombia" },
          { x: 20, y: 77, value: 18, label: "Chile" },
          { x: 12, y: 73, value: 40, label: "Argentina" },
          { x: 25, y: 76, value: 22, label: "Peru" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 6, y: 55, value: 58, label: "Nigeria" },
          { x: 8, y: 64, value: 42, label: "Ethiopia" },
          { x: 4, y: 62, value: 50, label: "Congo" },
          { x: 3, y: 58, value: 38, label: "Tanzania" },
          { x: 5, y: 72, value: 28, label: "S. Africa" },
          { x: 2, y: 60, value: 45, label: "Kenya" },
          { x: 7, y: 66, value: 22, label: "Uganda" },
          { x: 10, y: 68, value: 35, label: "Ghana" },
        ],
      },
    ],
  },
  config: {
    title: { text: "GDP per Capita vs Life Expectancy", visible: true },
    subtitle: {
      text: "Bubble size = population (millions) · by continent",
      visible: true,
    },
  },
});` },
];

const _BubbleChartToastProductMargin_files = [
  { filename: "index.tsx", code: `import ToastBubbleChart from "@/components/flitter/charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 82, y: 45, value: 55, label: "China" },
          { x: 68, y: 58, value: 40, label: "India" },
          { x: 55, y: 35, value: 62, label: "Japan" },
          { x: 40, y: 68, value: 30, label: "S. Korea" },
          { x: 75, y: 52, value: 48, label: "Indonesia" },
          { x: 28, y: 42, value: 35, label: "Thailand" },
          { x: 62, y: 72, value: 25, label: "Vietnam" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 35, y: 78, value: 42, label: "Germany" },
          { x: 48, y: 65, value: 55, label: "France" },
          { x: 22, y: 82, value: 30, label: "UK" },
          { x: 58, y: 48, value: 38, label: "Italy" },
          { x: 42, y: 72, value: 20, label: "Spain" },
          { x: 15, y: 55, value: 45, label: "Poland" },
          { x: 52, y: 60, value: 28, label: "Netherlands" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 88, y: 32, value: 65, label: "USA" },
          { x: 72, y: 42, value: 50, label: "Canada" },
          { x: 45, y: 25, value: 58, label: "Brazil" },
          { x: 60, y: 38, value: 42, label: "Mexico" },
          { x: 32, y: 55, value: 35, label: "Argentina" },
          { x: 78, y: 28, value: 48, label: "Chile" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 50, y: 85, value: 20, label: "Australia" },
          { x: 65, y: 75, value: 32, label: "N. Zealand" },
          { x: 38, y: 62, value: 28, label: "Fiji" },
          { x: 72, y: 68, value: 18, label: "Papua N.G." },
          { x: 45, y: 80, value: 24, label: "Samoa" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Product Revenue vs Profit Margin", visible: true },
  },
});` },
];

const _BulletChartAgRevenueTargets_files = [
  { filename: "index.tsx", code: `import BulletChart from "@/components/flitter/charts/bullet-chart";

const chart = BulletChart({
  data: {
    labels: ["Americas", "Europe", "Asia Pacific", "Other"],
    datasets: [
      {
        value: 118,
        target: 110,
        ranges: [65, 95, 130],
      },
      {
        value: 92,
        target: 100,
        ranges: [50, 80, 115],
      },
      {
        value: 104,
        target: 100,
        ranges: [60, 85, 120],
      },
      {
        value: 48,
        target: 55,
        ranges: [25, 40, 65],
      },
    ],
  },
  direction: "horizontal",
  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _BulletChartToastServiceQuality_files = [
  { filename: "index.tsx", code: `import ToastBulletChart from "@/components/flitter/charts/toast-bullet-chart";

const chart = ToastBulletChart({
  data: {
    labels: ["Chat", "Email", "Phone", "Self-service"],
    datasets: [
      {
        value: 94,
        target: 95,
        ranges: [70, 85, 100],
      },
      {
        value: 88,
        target: 90,
        ranges: [70, 85, 100],
      },
      {
        value: 97,
        target: 95,
        ranges: [70, 85, 100],
      },
      {
        value: 82,
        target: 90,
        ranges: [70, 85, 100],
      },
    ],
  },
  direction: "horizontal",
  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _CandlestickChartAgBitcoinMonthly_files = [
  { filename: "index.tsx", code: `import CandlestickChart from "@/components/flitter/charts/candlestick-chart";
function formatUsd(name: string, _index: number, axis: "x" | "y"): string {
  if (axis !== "y") return name;
  const v = Number(name);
  return Number.isFinite(v) ? \`$\${Math.round(v).toLocaleString("en-US")}\` : name;
}

const chart = CandlestickChart({
  data: {
    rows: [
      { tick: 0, open: 387.43, high: 411.70, low: 289.30, close: 338.32 },
      { tick: 1, open: 338.65, high: 457.09, low: 320.63, close: 378.05 },
      { tick: 2, open: 378.25, high: 384.04, low: 304.23, close: 320.19 },
      { tick: 3, open: 320.43, high: 320.43, low: 171.51, close: 217.46 },
      { tick: 4, open: 216.87, high: 265.61, low: 212.01, close: 254.26 },
      { tick: 5, open: 254.28, high: 300.04, low: 236.51, close: 244.22 },
      { tick: 6, open: 244.22, high: 261.80, low: 214.87, close: 236.15 },
      { tick: 7, open: 235.94, high: 247.80, low: 228.57, close: 230.19 },
      { tick: 8, open: 230.23, high: 267.87, low: 221.30, close: 263.07 },
      { tick: 9, open: 263.35, high: 314.39, low: 253.51, close: 284.65 },
      { tick: 10, open: 284.69, high: 285.71, low: 199.57, close: 230.06 },
      { tick: 11, open: 230.26, high: 259.18, low: 225.12, close: 236.06 },
      { tick: 12, open: 236.00, high: 334.17, low: 235.62, close: 314.17 },
      { tick: 13, open: 315.01, high: 495.56, low: 301.00, close: 377.32 },
      { tick: 14, open: 377.41, high: 469.10, low: 349.46, close: 430.57 },
      { tick: 15, open: 430.72, high: 462.93, low: 354.91, close: 368.77 },
      { tick: 16, open: 369.35, high: 448.05, low: 367.96, close: 437.70 },
      { tick: 17, open: 437.92, high: 439.65, low: 394.04, close: 416.73 },
      { tick: 18, open: 416.76, high: 467.96, low: 415.83, close: 448.32 },
      { tick: 19, open: 448.48, high: 553.96, low: 437.39, close: 531.39 },
      { tick: 20, open: 531.11, high: 778.00, low: 525.64, close: 673.34 },
      { tick: 21, open: 672.52, high: 704.97, low: 611.83, close: 624.68 },
      { tick: 22, open: 624.60, high: 626.12, low: 531.33, close: 575.47 },
      { tick: 23, open: 575.55, high: 628.82, low: 570.81, close: 609.73 },
      { tick: 24, open: 609.93, high: 720.40, low: 609.48, close: 700.97 },
    ],
    xKey: "tick",
  },
  config: {
    title: { text: "Bitcoin Monthly OHLC", visible: true },
    subtitle: { visible: true, text: "Sep 2014 – Oct 2016" },
    axis: { label: { format: formatUsd } },
  },
});` },
];

const _DonutChartAgPaymentMethods_files = [
  { filename: "index.tsx", code: `import DonutChart from "@/components/flitter/charts/donut-chart";

const chart = DonutChart({
  data: {
    datasets: [
      { name: "Credit Card", value: 35 },
      { name: "Digital Wallet", value: 28 },
      { name: "Bank Transfer", value: 16 },
      { name: "Debit Card", value: 12 },
      { name: "Cash", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    radial: { visible: true },
    dataLabel: { visible: true },
    dataCenter: { visible: true },
    legend: { visible: false },
  },
});` },
];

const _DonutChartToastProjectStatus_files = [
  { filename: "index.tsx", code: `import ToastDonutChart from "@/components/flitter/charts/toast-donut-chart";

const chart = ToastDonutChart({
  data: {
    datasets: [
      { name: "AWS", value: 32 },
      { name: "Azure", value: 23 },
      { name: "Google Cloud", value: 11 },
      { name: "Alibaba", value: 5 },
      { name: "Oracle", value: 4 },
      { name: "Other", value: 25 },
    ],
  },
  config: {
    legend: { visible: false },
    radial: { visible: false },
  },
});` },
];

const _FunnelChartAgProductOnboarding_files = [
  { filename: "index.tsx", code: `import FunnelChart from "@/components/flitter/charts/funnel-chart";

const chart = FunnelChart({
  data: {
    stages: [
      {
        label: "Sign-ups",
        value: 12000,
      },
      {
        label: "Email verified",
        value: 9600,
      },
      {
        label: "Workspace created",
        value: 7200,
      },
      {
        label: "First project",
        value: 4800,
      },
      {
        label: "Team invited",
        value: 3000,
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _FunnelChartToastSalesPipeline_files = [
  { filename: "index.tsx", code: `import ToastFunnelChart from "@/components/flitter/charts/toast-funnel-chart";

const chart = ToastFunnelChart({
  data: {
    stages: [
      {
        label: "Leads",
        value: 2400,
      },
      {
        label: "Qualified",
        value: 1680,
      },
      {
        label: "Demo booked",
        value: 1080,
      },
      {
        label: "Proposal sent",
        value: 720,
      },
      {
        label: "Closed won",
        value: 480,
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _HeatmapChartAgHourlyTraffic_files = [
  { filename: "index.tsx", code: `import HeatmapChart from "@/components/flitter/charts/heatmap-chart";

const chart = HeatmapChart({
  data: {
    xLabels: [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ],
    yLabels: ["Seoul", "Seattle", "Sydney", "Moscow", "Jungfrau"],
    values: [
      [-3.5, -1.1, 4.0, 11.3, 17.2, 22.0, 25.5, 26.1, 21.3, 14.2, 6.1, -0.8],
      [5.4, 6.1, 8.0, 10.3, 13.5, 16.2, 19.4, 19.6, 16.5, 11.8, 7.5, 4.8],
      [25.8, 25.6, 24.0, 21.2, 17.5, 14.6, 13.5, 14.8, 17.4, 20.0, 22.4, 24.6],
      [-9.3, -7.5, -2.0, 6.2, 13.1, 17.5, 19.8, 17.6, 11.8, 5.3, -1.5, -6.8],
      [-8.1, -8.5, -5.8, -2.0, 2.8, 6.4, 8.9, 8.6, 5.8, 1.5, -3.4, -6.9],
    ],
  },
  config: {
    title: { text: "Average Monthly Temperature (\\u00B0C)", visible: true },
  },
});` },
];

const _HeatmapChartToastMonthlyProductSales_files = [
  { filename: "index.tsx", code: `import ToastHeatmapChart from "@/components/flitter/charts/toast-heatmap-chart";

const chart = ToastHeatmapChart({
  data: {
    xLabels: [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ],
    yLabels: [
      "Vanilla", "Chocolate", "Strawberry",
      "Mint Chip", "Cookie Dough", "Mango Sorbet",
    ],
    values: [
      [12, 11, 14, 18, 28, 38, 52, 50, 32, 20, 14, 13],
      [15, 14, 16, 20, 30, 40, 54, 51, 34, 22, 16, 17],
      [8, 7, 10, 15, 24, 34, 46, 44, 28, 16, 9, 8],
      [6, 5, 7, 10, 16, 22, 30, 28, 18, 11, 7, 6],
      [10, 9, 12, 16, 22, 30, 42, 40, 26, 17, 11, 12],
      [4, 3, 6, 12, 22, 36, 48, 46, 30, 14, 5, 3],
    ],
  },
  config: {
    title: { text: "Monthly Ice Cream Sales by Flavor ($K)", visible: true },
    heatmap: {
      colorRange: ["#FEE2E2", "#EF4444", "#7F1D1D"],
      segment: { gap: 0 },
    },
  },
});` },
];

const _HistogramChartAgParcelWeights_files = [
  { filename: "index.tsx", code: `import HistogramChart from "@/components/flitter/charts/histogram-chart";

const chart = HistogramChart({
  data: {
    rows: [
      {
        weight: 0.4,
      },
      {
        weight: 0.6,
      },
      {
        weight: 0.7,
      },
      {
        weight: 0.8,
      },
      {
        weight: 0.9,
      },
      {
        weight: 1,
      },
      {
        weight: 1.1,
      },
      {
        weight: 1.2,
      },
      {
        weight: 1.3,
      },
      {
        weight: 1.3,
      },
      {
        weight: 1.4,
      },
      {
        weight: 1.5,
      },
      {
        weight: 1.5,
      },
      {
        weight: 1.6,
      },
      {
        weight: 1.6,
      },
      {
        weight: 1.7,
      },
      {
        weight: 1.8,
      },
      {
        weight: 1.8,
      },
      {
        weight: 1.9,
      },
      {
        weight: 2,
      },
      {
        weight: 2,
      },
      {
        weight: 2.1,
      },
      {
        weight: 2.2,
      },
      {
        weight: 2.2,
      },
      {
        weight: 2.3,
      },
      {
        weight: 2.4,
      },
      {
        weight: 2.4,
      },
      {
        weight: 2.5,
      },
      {
        weight: 2.6,
      },
      {
        weight: 2.8,
      },
      {
        weight: 2.9,
      },
      {
        weight: 3,
      },
      {
        weight: 3.2,
      },
      {
        weight: 3.4,
      },
      {
        weight: 3.8,
      },
      {
        weight: 4.1,
      },
    ],
    xKey: "weight",
  },
  transform: { binCount: 8, aggregation: "count" },
  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _HistogramChartToastResponseTimes_files = [
  { filename: "index.tsx", code: `import ToastHistogramChart from "@/components/flitter/charts/toast-histogram-chart";

const chart = ToastHistogramChart({
  data: {
    rows: [
      {
        latency: 45,
      },
      {
        latency: 58,
      },
      {
        latency: 63,
      },
      {
        latency: 71,
      },
      {
        latency: 74,
      },
      {
        latency: 79,
      },
      {
        latency: 83,
      },
      {
        latency: 86,
      },
      {
        latency: 88,
      },
      {
        latency: 92,
      },
      {
        latency: 95,
      },
      {
        latency: 98,
      },
      {
        latency: 101,
      },
      {
        latency: 103,
      },
      {
        latency: 108,
      },
      {
        latency: 110,
      },
      {
        latency: 112,
      },
      {
        latency: 117,
      },
      {
        latency: 122,
      },
      {
        latency: 128,
      },
      {
        latency: 136,
      },
      {
        latency: 145,
      },
      {
        latency: 157,
      },
      {
        latency: 168,
      },
      {
        latency: 184,
      },
      {
        latency: 201,
      },
      {
        latency: 225,
      },
      {
        latency: 252,
      },
      {
        latency: 286,
      },
      {
        latency: 320,
      },
    ],
    xKey: "latency",
  },
  transform: { binCount: 8, aggregation: "count" },
  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _LineChartAgMonthlyActiveUsers_files = [
  { filename: "index.tsx", code: `import LineChart from "@/components/flitter/charts/line-chart";

const chart = LineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Seoul", values: [-3.5, -1.1, 4.0, 11.3, 17.5, 21.5, 25.9, 27.2, 24.4, 13.9, 6.6, -0.6] },
      { legend: "Seattle", values: [3.8, 5.6, 7.0, 9.1, 12.4, 15.3, 17.5, 17.8, 15.0, 10.6, 6.6, 3.7] },
      { legend: "Sydney", values: [22.1, 22.0, 20.9, 18.3, 15.2, 12.8, 11.8, 13.0, 15.2, 17.6, 19.4, 21.2] },
    ],
  },
  config: {
    title: { text: "Average Monthly Temperature", visible: true },
    subtitle: { text: "Celsius degrees by city (2024)", visible: true },
  },
});` },
];

const _LineChartToastChannelTraffic_files = [
  { filename: "index.tsx", code: `import ToastLineChart from "@/components/flitter/charts/toast-line-chart";

const chart = ToastLineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Moscow", values: [-9.1, -7.2, -1.3, 6.4, 13.2, 17.0, 19.2, 17.1, 11.3, 5.0, -1.8, -6.5] },
      { legend: "London", values: [4.9, 5.2, 7.3, 9.6, 12.8, 16.0, 18.4, 18.1, 15.2, 11.5, 7.6, 5.1] },
      { legend: "Tokyo", values: [5.4, 6.1, 9.4, 14.3, 18.7, 21.8, 25.7, 27.2, 23.5, 17.6, 12.4, 7.2] },
    ],
  },
  config: {
    title: { text: "Monthly Average Temperature (°C)", visible: true, alignment: "center" },
    line: { spline: true },
  },
});` },
];

const _PieChartAgBrowserShare_files = [
  { filename: "index.tsx", code: `import PieChart from "@/components/flitter/charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    legend: { visible: false },
    radial: { visible: false },
    dataLabel: {
      visible: true,
      formatter: (args) =>
        args.percentage >= 5 ? \`\${args.name}\\n\${args.percentage.toFixed(0)}%\` : "",
    },
  },
});` },
];

const _PieChartToastBudgetAllocation_files = [
  { filename: "index.tsx", code: `import ToastPieChart from "@/components/flitter/charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "CRM", value: 22 },
      { name: "ERP", value: 19 },
      { name: "Security", value: 17 },
      { name: "Collaboration", value: 16 },
      { name: "Analytics", value: 14 },
      { name: "Other", value: 12 },
    ],
  },
  config: {
    title: { text: "Enterprise Software Market Share", visible: true },
    legend: { visible: true, position: "bottom" },
    radial: { visible: true },
    radialLabel: {
      formatter: (args) => args.name,
    },
    dataLabel: {
      visible: true,
      formatter: (args) => \`\${args.percentage.toFixed(1)}%\`,
    },
  },
});` },
];

const _RadarChartAgSkillAssessment_files = [
  { filename: "index.tsx", code: `import RadarChart from "@/components/flitter/charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: [
      "Acidity",
      "Sweetness",
      "Body",
      "Bitterness",
      "Aroma",
      "Aftertaste",
    ],
    datasets: [
      { legend: "Ethiopian Yirgacheffe", values: [85, 72, 60, 35, 90, 78] },
    ],
  },
  config: {
    legend: { visible: false },
  },
});` },
];

const _RadarChartToastTeamComparison_files = [
  { filename: "index.tsx", code: `import ToastRadarChart from "@/components/flitter/charts/toast-radar-chart";

const chart = ToastRadarChart({
  data: {
    labels: [
      "Attack",
      "Defense",
      "Speed",
      "HP",
      "Sp.Atk",
      "Sp.Def",
    ],
    datasets: [
      { legend: "Pikachu", values: [55, 30, 95, 35, 50, 40] },
      { legend: "Bulbasaur", values: [49, 65, 45, 80, 65, 65] },
      { legend: "Charmander", values: [85, 43, 65, 39, 80, 35] },
    ],
  },
  config: {
    title: { text: "Pokémon Stats Battle", visible: true },
  },
});` },
];

const _SankeyChartAgEnergyFlow_files = [
  { filename: "index.tsx", code: `import SankeyChart from "@/components/flitter/charts/sankey-chart";

const chart = SankeyChart({
  data: [
    {
      from: "Solar",
      to: "Grid",
      value: 36,
    },
    {
      from: "Wind",
      to: "Grid",
      value: 44,
    },
    {
      from: "Hydro",
      to: "Grid",
      value: 20,
    },
    {
      from: "Grid",
      to: "Homes",
      value: 42,
    },
    {
      from: "Grid",
      to: "Industry",
      value: 38,
    },
    {
      from: "Grid",
      to: "Transport",
      value: 20,
    },
  ],

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _SankeyChartToastCustomerJourney_files = [
  { filename: "index.tsx", code: `import ToastSankeyChart from "@/components/flitter/charts/toast-sankey-chart";

const chart = ToastSankeyChart({
  data: [
    {
      from: "Search",
      to: "Trial",
      value: 420,
    },
    {
      from: "Referrals",
      to: "Trial",
      value: 260,
    },
    {
      from: "Social",
      to: "Trial",
      value: 180,
    },
    {
      from: "Trial",
      to: "Subscribed",
      value: 560,
    },
    {
      from: "Trial",
      to: "Not converted",
      value: 300,
    },
  ],

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _ScatterChartAgRevenueGrowth_files = [
  { filename: "index.tsx", code: `import ScatterChart from "@/components/flitter/charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 12, y: 28, label: "A1" }, { x: 18, y: 35, label: "A2" }, { x: 25, y: 42, label: "A3" },
          { x: 31, y: 48, label: "A4" }, { x: 38, y: 55, label: "A5" }, { x: 45, y: 61, label: "A6" },
          { x: 52, y: 67, label: "A7" }, { x: 58, y: 72, label: "A8" }, { x: 15, y: 32, label: "A9" },
          { x: 22, y: 39, label: "A10" }, { x: 35, y: 52, label: "A11" }, { x: 42, y: 58, label: "A12" },
          { x: 48, y: 63, label: "A13" }, { x: 55, y: 69, label: "A14" }, { x: 62, y: 74, label: "A15" },
          { x: 68, y: 78, label: "A16" }, { x: 75, y: 82, label: "A17" }, { x: 82, y: 86, label: "A18" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 8, y: 22, label: "E1" }, { x: 14, y: 30, label: "E2" }, { x: 20, y: 36, label: "E3" },
          { x: 27, y: 43, label: "E4" }, { x: 33, y: 49, label: "E5" }, { x: 40, y: 54, label: "E6" },
          { x: 46, y: 60, label: "E7" }, { x: 53, y: 65, label: "E8" }, { x: 60, y: 71, label: "E9" },
          { x: 66, y: 76, label: "E10" }, { x: 72, y: 80, label: "E11" }, { x: 10, y: 25, label: "E12" },
          { x: 24, y: 40, label: "E13" }, { x: 50, y: 62, label: "E14" }, { x: 78, y: 84, label: "E15" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 5, y: 15, label: "M1" }, { x: 11, y: 24, label: "M2" }, { x: 19, y: 33, label: "M3" },
          { x: 26, y: 41, label: "M4" }, { x: 34, y: 50, label: "M5" }, { x: 41, y: 57, label: "M6" },
          { x: 49, y: 64, label: "M7" }, { x: 56, y: 70, label: "M8" }, { x: 63, y: 75, label: "M9" },
          { x: 70, y: 81, label: "M10" }, { x: 77, y: 85, label: "M11" }, { x: 83, y: 88, label: "M12" },
          { x: 16, y: 29, label: "M13" }, { x: 37, y: 53, label: "M14" }, { x: 88, y: 90, label: "M15" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 3, y: 10, label: "F1" }, { x: 9, y: 18, label: "F2" }, { x: 17, y: 27, label: "F3" },
          { x: 23, y: 34, label: "F4" }, { x: 30, y: 44, label: "F5" }, { x: 36, y: 50, label: "F6" },
          { x: 44, y: 56, label: "F7" }, { x: 50, y: 62, label: "F8" }, { x: 57, y: 68, label: "F9" },
          { x: 64, y: 73, label: "F10" }, { x: 13, y: 21, label: "F11" }, { x: 42, y: 52, label: "F12" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Revenue vs Annual Growth Rate", visible: true },
    subtitle: {
      text: "Regional performance by continent · $M vs %",
      visible: true,
    },
    scatter: {
      size: 7,
    },
  },
});` },
];

const _ScatterChartToastStudentScores_files = [
  { filename: "index.tsx", code: `import ToastScatterChart from "@/components/flitter/charts/toast-scatter-chart";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 72, y: 68, label: "A1" }, { x: 65, y: 78, label: "A2" }, { x: 80, y: 85, label: "A3" },
          { x: 85, y: 75, label: "A4" }, { x: 70, y: 82, label: "A5" }, { x: 77, y: 70, label: "A6" },
          { x: 63, y: 88, label: "A7" }, { x: 75, y: 60, label: "A8" }, { x: 82, y: 72, label: "A9" },
          { x: 68, y: 90, label: "A10" }, { x: 88, y: 80, label: "A11" }, { x: 58, y: 74, label: "A12" },
          { x: 92, y: 70, label: "A13" }, { x: 74, y: 92, label: "A14" }, { x: 60, y: 65, label: "A15" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 45, y: 52, label: "E1" }, { x: 38, y: 48, label: "E2" }, { x: 55, y: 60, label: "E3" },
          { x: 42, y: 55, label: "E4" }, { x: 50, y: 45, label: "E5" }, { x: 35, y: 42, label: "E6" },
          { x: 48, y: 58, label: "E7" }, { x: 52, y: 50, label: "E8" }, { x: 40, y: 62, label: "E9" },
          { x: 58, y: 40, label: "E10" }, { x: 33, y: 55, label: "E11" }, { x: 62, y: 35, label: "E12" },
          { x: 28, y: 60, label: "E13" }, { x: 46, y: 44, label: "E14" }, { x: 54, y: 68, label: "E15" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 75, y: 18, label: "M1" }, { x: 82, y: 25, label: "M2" }, { x: 68, y: 12, label: "M3" },
          { x: 88, y: 30, label: "M4" }, { x: 72, y: 22, label: "M5" }, { x: 80, y: 15, label: "M6" },
          { x: 65, y: 28, label: "M7" }, { x: 85, y: 20, label: "M8" }, { x: 78, y: 10, label: "M9" },
          { x: 60, y: 32, label: "M10" }, { x: 90, y: 8, label: "M11" }, { x: 95, y: 14, label: "M12" },
          { x: 55, y: 38, label: "M13" }, { x: 70, y: 5, label: "M14" }, { x: 84, y: 35, label: "M15" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 10, y: 75, label: "F1" }, { x: 18, y: 82, label: "F2" }, { x: 25, y: 68, label: "F3" },
          { x: 15, y: 85, label: "F4" }, { x: 8, y: 78, label: "F5" }, { x: 20, y: 70, label: "F6" },
          { x: 12, y: 88, label: "F7" }, { x: 22, y: 65, label: "F8" }, { x: 5, y: 80, label: "F9" },
          { x: 30, y: 72, label: "F10" }, { x: 3, y: 92, label: "F11" }, { x: 16, y: 60, label: "F12" },
          { x: 28, y: 90, label: "F13" }, { x: 7, y: 68, label: "F14" }, { x: 14, y: 95, label: "F15" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 30, y: 35, label: "O1" }, { x: 22, y: 28, label: "O2" }, { x: 40, y: 45, label: "O3" },
          { x: 35, y: 30, label: "O4" }, { x: 28, y: 40, label: "O5" }, { x: 18, y: 22, label: "O6" },
          { x: 45, y: 50, label: "O7" }, { x: 32, y: 38, label: "O8" }, { x: 25, y: 48, label: "O9" },
          { x: 50, y: 55, label: "O10" }, { x: 15, y: 15, label: "O11" }, { x: 38, y: 25, label: "O12" },
          { x: 42, y: 58, label: "O13" }, { x: 20, y: 42, label: "O14" }, { x: 48, y: 32, label: "O15" },
        ],
      },
    ],
  },
  config: {
    title: {
      text: "Math vs Science Scores by Region",
      visible: true,
    },
    scatter: {
      size: 8,
      fill: false,
      strokeWidth: 2,
    },
  },
});` },
];

const _StackedAreaChartAgMonthlyExpenses_files = [
  { filename: "index.tsx", code: `import StackedAreaChart from "@/components/flitter/charts/stacked-area-chart";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    datasets: [
      { legend: "Housing", values: [1200, 1200, 1250, 1250, 1300, 1300, 1350, 1350, 1400, 1400] },
      { legend: "Food & Dining", values: [480, 520, 450, 510, 560, 620, 580, 640, 550, 590] },
      { legend: "Transport", values: [320, 280, 310, 350, 390, 420, 450, 380, 340, 360] },
      { legend: "Utilities", values: [180, 200, 170, 150, 130, 160, 210, 240, 190, 170] },
    ],
  },
  config: {
    title: { text: "Monthly Household Expenses ($)", visible: true },
    area: { opacity: 0.65, spline: true },
  },
});` },
];

const _StackedAreaChartToastTrafficSources_files = [
  { filename: "index.tsx", code: `import ToastStackedAreaChart from "@/components/flitter/charts/toast-stacked-area-chart";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    datasets: [
      { legend: "Organic", values: [40, 50, 60, 55, 70, 80, 95, 110, 125] },
      { legend: "Paid", values: [30, 35, 40, 45, 50, 55, 52, 58, 62] },
      { legend: "Referral", values: [20, 25, 20, 30, 25, 35, 32, 28, 38] },
    ],
  },
  config: {
    title: { text: "Website Traffic Sources (K visits)", visible: true, alignment: "center" },
    area: { opacity: 0.6, strokeWidth: 2, spline: true },
  },
});` },
];

const _StackedBarChartAgEnergyMix_files = [
  { filename: "index.tsx", code: `import StackedBarChart from "@/components/flitter/charts/stacked-bar-chart";

const chart = StackedBarChart({
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Budget", values: [5000, 3000, 5000, 7000, 6000, 4000, 1000] },
      { legend: "Income", values: [8000, 4000, 7000, 2000, 6000, 3000, 5000] },
      { legend: "Expenses", values: [4000, 3000, 5000, 4000, 3000, 4000, 3000] },
      { legend: "Debt", values: [6000, 3000, 3000, 2000, 5000, 4000, 2000] },
    ],
  },
  config: {
    title: { text: "Monthly Financial Overview", visible: true },
    legend: { visible: true, position: "right" },
  },
});` },
];

const _StackedBarChartToastNivoPattern_files = [
  { filename: "index.tsx", code: `import ToastStackedBarChart from "@/components/flitter/charts/toast-stacked-bar-chart";
import {
  Container,
  EdgeInsets,
  Stack,
  Alignment,
  CustomPaint,
  Size,
  Path,
  Rect,
  Offset,
  Text,
  TextStyle,
  ZIndex,
  Row,
  SizedBox,
  MainAxisSize,
  Padding,
  BoxDecoration,
  Opacity,
  type Widget as FlitterWidget,
} from "flitter-core";
import type { BarChartContext } from "flitter-ui/chart";

const backgroundColors = ["#e8c1a0", "#f47560", "#f1e15b", "#e8a838", "#61cdbb"];
const patternColors = ["#c49c81", "#d4573f", "#c9bd3e", "#c08a25", "#38bcb2"];

type LegendPatternType = "dots" | "stripes" | "crosshatch" | "diagonal-stripes" | "grid";
const legendPatterns: LegendPatternType[] = ["dots", "stripes", "crosshatch", "diagonal-stripes", "grid"];

function drawDotsPattern(path: Path, width: number, height: number) {
  for (let y = 4; y < height; y += 10) {
    for (let x = 4 + ((y % 20) / 2); x < width; x += 10) {
      path.addOval(Rect.fromCircle({ center: new Offset({ x, y }), radius: 2.5 }));
    }
  }
}

function drawStripesPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 12) {
    path.moveTo({ x: width, y });
    path.lineTo({ x: 0, y: y + width });
  }
}

function drawCrosshatchPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 14) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y: y + width });
    path.moveTo({ x: width, y });
    path.lineTo({ x: 0, y: y + width });
  }
}

function drawDiagonalStripesPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 10) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y: y + width });
  }
}

function drawGridPattern(path: Path, width: number, height: number) {
  for (let x = 0; x < width; x += 12) {
    path.moveTo({ x, y: 0 });
    path.lineTo({ x, y: height });
  }
  for (let y = 0; y < height; y += 12) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y });
  }
}

function PatternBar(
  { legend, value, label, index, isHovered }: { value: number; label: string; legend: string; index: number; isHovered: boolean },
  context: BarChartContext,
): FlitterWidget {
  const idx = context.legends.indexOf(legend);
  const bgColor = backgroundColors[idx % backgroundColors.length];
  const patternColor = patternColors[idx % patternColors.length];
  const patternType = legendPatterns[idx % legendPatterns.length];

  return ZIndex({
    zIndex: isHovered ? 1 : 0,
    child: Container({
      width: Infinity,
      height: Infinity,
      margin: EdgeInsets.symmetric({ horizontal: 0 }),
      color: bgColor,
      child: Stack({
        alignment: Alignment.center,
        clipped: true,
        children: [
          CustomPaint({
            size: Size.maximum(),
            painter: {
              svg: {
                createDefaultSvgEl(svgContext: any) {
                  return { bar: svgContext.createSvgEl("path") };
                },
                paint({ bar }: any, size: any) {
                  const path = new Path();
                  const { width, height } = size;

                  if (patternType === "dots") {
                    bar.setAttribute("fill", patternColor);
                    drawDotsPattern(path, width, height);
                  } else if (patternType === "stripes") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "4");
                    bar.setAttribute("fill", "none");
                    drawStripesPattern(path, width, height);
                  } else if (patternType === "crosshatch") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "2");
                    bar.setAttribute("fill", "none");
                    drawCrosshatchPattern(path, width, height);
                  } else if (patternType === "diagonal-stripes") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "3");
                    bar.setAttribute("fill", "none");
                    drawDiagonalStripesPattern(path, width, height);
                  } else if (patternType === "grid") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "1.5");
                    bar.setAttribute("fill", "none");
                    drawGridPattern(path, width, height);
                  }
                  bar.setAttribute("d", path.getD());
                },
              },
              canvas: {
                paint(context: any, size: any) {
                  const { width, height } = size;
                  const ctx = context as CanvasRenderingContext2D;

                  if (patternType === "dots") {
                    ctx.fillStyle = patternColor;
                    for (let y = 4; y < height; y += 10) {
                      for (let x = 4 + ((y % 20) / 2); x < width; x += 10) {
                        ctx.beginPath();
                        ctx.arc(x, y, 2.5, 0, Math.PI * 2);
                        ctx.fill();
                      }
                    }
                  } else if (patternType === "stripes") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 4;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 12) {
                      ctx.beginPath();
                      ctx.moveTo(width, y);
                      ctx.lineTo(0, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "crosshatch") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 2;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 14) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y + width);
                      ctx.stroke();
                      ctx.beginPath();
                      ctx.moveTo(width, y);
                      ctx.lineTo(0, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "diagonal-stripes") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 3;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 10) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "grid") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 1.5;
                    for (let x = 0; x < width; x += 12) {
                      ctx.beginPath();
                      ctx.moveTo(x, 0);
                      ctx.lineTo(x, height);
                      ctx.stroke();
                    }
                    for (let y = 0; y < height; y += 12) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y);
                      ctx.stroke();
                    }
                  }
                },
              },
            },
          }),
          Text(value > 1500 ? \`\${value}\` : "", {
            style: new TextStyle({ fontSize: 11, color: "#555555", fontWeight: "bold" }),
          }),
        ],
      }),
    }),
  });
}

function PatternLegend(
  { name, index, isVisible }: { name: string; index: number; isVisible?: boolean },
  context: { config: any; isSeriesVisible?(legend: string): boolean },
): FlitterWidget {
  const bgColor = backgroundColors[index % backgroundColors.length];
  const visible = isVisible ?? context.isSeriesVisible?.(name) ?? true;

  const markerSize = 28;

  const marker = Container({
    width: markerSize,
    height: markerSize,
    color: bgColor,
  });

  const content = Padding({
    padding: EdgeInsets.symmetric({ horizontal: 8 }),
    child: Row({
      mainAxisSize: MainAxisSize.min,
      children: [
        marker,
        SizedBox({ width: 6 }),
        Text(name, {
          style: new TextStyle({
            fontSize: 12,
            color: context.config.legend.color,
          }),
        }),
      ],
    }),
  });

  return visible
    ? content
    : Opacity({
        opacity: 0.4,
        child: content,
      });
}

const chart = ToastStackedBarChart({
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Budget", values: [5000, 3000, 5000, 7000, 6000, 4000, 1000] },
      { legend: "Income", values: [8000, 4000, 7000, 2000, 6000, 3000, 5000] },
      { legend: "Expenses", values: [4000, 3000, 5000, 4000, 3000, 4000, 3000] },
      { legend: "Debt", values: [6000, 3000, 3000, 2000, 5000, 4000, 2000] },
    ],
  },
  custom: {
    bar: PatternBar,
    legend: PatternLegend,
  },
  config: {
    title: { text: "Monthly Financial Breakdown", visible: true },
    legend: {
      visible: true,
      position: "right-bottom",
    },
    bar: {
      gap: 0,
    },
  },
});` },
];

const _StackedBarChartToastRegionalSales_files = [
  { filename: "index.tsx", code: `import ToastStackedBarChart from "@/components/flitter/charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Revenue", values: [8000, 4000, 7000, -2000, 6000, -3000, 5000] },
      { legend: "Costs", values: [-4000, -3000, -5000, -4000, 3000, 4000, -3000] },
      { legend: "Net", values: [3000, -2000, 4000, 2000, -5000, 4000, -2000] },
    ],
  },
  config: {
    title: { text: "Monthly Revenue Breakdown", visible: true },
  },
});` },
];

const _SunburstChartAgOrgStructure_files = [
  { filename: "index.tsx", code: `import SunburstChart from "@/components/flitter/charts/sunburst-chart";

const chart = SunburstChart({
  data: {
    nodes: [
      {
        label: "Engineering",
        value: 66,
        children: [
          {
            label: "Frontend",
            value: 28,
            children: [],
          },
          {
            label: "Platform",
            value: 22,
            children: [],
          },
          {
            label: "Data",
            value: 16,
            children: [],
          },
        ],
      },
      {
        label: "Product",
        value: 20,
        children: [
          {
            label: "Design",
            value: 12,
            children: [],
          },
          {
            label: "Research",
            value: 8,
            children: [],
          },
        ],
      },
      {
        label: "Business",
        value: 42,
        children: [
          {
            label: "Sales",
            value: 18,
            children: [],
          },
          {
            label: "Success",
            value: 14,
            children: [],
          },
          {
            label: "Operations",
            value: 10,
            children: [],
          },
        ],
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _SunburstChartToastWorldPopulation_files = [
  { filename: "index.tsx", code: `import ToastSunburstChart from "@/components/flitter/charts/toast-sunburst-chart";

const chart = ToastSunburstChart({
  data: {
    nodes: [
      {
        label: "Asia",
        value: 4820,
        children: [
          {
            label: "East",
            value: 1660,
            children: [],
          },
          {
            label: "South",
            value: 2050,
            children: [],
          },
          {
            label: "Southeast",
            value: 690,
            children: [],
          },
          {
            label: "West & Central",
            value: 420,
            children: [],
          },
        ],
      },
      {
        label: "Africa",
        value: 1520,
        children: [
          {
            label: "North",
            value: 270,
            children: [],
          },
          {
            label: "Sub-Saharan",
            value: 1250,
            children: [],
          },
        ],
      },
      {
        label: "Americas",
        value: 1040,
        children: [
          {
            label: "North",
            value: 380,
            children: [],
          },
          {
            label: "Latin America",
            value: 660,
            children: [],
          },
        ],
      },
      {
        label: "Europe",
        value: 740,
        children: [
          {
            label: "West & North",
            value: 310,
            children: [],
          },
          {
            label: "East & South",
            value: 430,
            children: [],
          },
        ],
      },
      {
        label: "Oceania",
        value: 46,
        children: [
          {
            label: "Oceania",
            value: 46,
            children: [],
          },
        ],
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _TreemapChartAgDiskSpaceUsage_files = [
  { filename: "index.tsx", code: `import TreemapChart from "@/components/flitter/charts/treemap-chart";

const chart = TreemapChart({
  data: {
    datasets: [
      {
        legend: "Media",
        children: [
          { label: "Photos", secondaryLabel: "30 GB", value: 30 },
          { label: "Videos", secondaryLabel: "45 GB", value: 45 },
          { label: "Music", secondaryLabel: "12 GB", value: 12 },
        ],
      },
      {
        legend: "Work",
        children: [
          { label: "Documents", secondaryLabel: "18 GB", value: 18 },
          { label: "Projects", secondaryLabel: "25 GB", value: 25 },
        ],
      },
      {
        legend: "System",
        children: [
          { label: "Applications", secondaryLabel: "22 GB", value: 22 },
          { label: "OS & Cache", secondaryLabel: "35 GB", value: 35 },
        ],
      },
      {
        legend: "Other",
        value: 8,
        secondaryLabel: "8 GB",
      },
    ],
  },
  config: {
    title: { text: "Disk Space Usage (195 GB)", visible: true },
  },
});` },
];

const _TreemapChartToastGlobalRevenueBreakdown_files = [
  { filename: "index.tsx", code: `import ToastTreemapChart from "@/components/flitter/charts/toast-treemap-chart";

const chart = ToastTreemapChart({
  data: {
    datasets: [
      {
        legend: "Video",
        children: [
          { label: "Netflix", secondaryLabel: "$38.3B", value: 383 },
          { label: "Disney+", secondaryLabel: "$22.1B", value: 221 },
          { label: "YouTube Premium", secondaryLabel: "$15.7B", value: 157 },
        ],
      },
      {
        legend: "Music",
        children: [
          { label: "Spotify", secondaryLabel: "$18.4B", value: 184 },
          { label: "Apple Music", secondaryLabel: "$9.6B", value: 96 },
        ],
      },
      {
        legend: "Gaming",
        children: [
          { label: "Xbox Game Pass", secondaryLabel: "$12.2B", value: 122 },
          { label: "PS Plus", secondaryLabel: "$8.5B", value: 85 },
        ],
      },
      {
        legend: "Other",
        value: 42,
        secondaryLabel: "$4.2B",
      },
    ],
  },
  config: {
    title: { text: "Global Streaming Revenue by Platform (2025)", visible: true },
  },
});` },
];

const _WaterfallChartAgOperatingProfit_files = [
  { filename: "index.tsx", code: `import WaterfallChart from "@/components/flitter/charts/waterfall-chart";

const chart = WaterfallChart({
  data: {
    rows: [
      {
        item: "Revenue",
        amount: 180,
      },
      {
        item: "Services",
        amount: 25,
      },
      {
        item: "Materials",
        amount: -54,
      },
      {
        item: "Payroll",
        amount: -62,
      },
      {
        item: "Operations",
        amount: -24,
      },
    ],
    xKey: "item",
    yKey: "amount",
    totals: [
      {
        totalType: "total",
        index: 4,
        axisLabel: "Profit",
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

const _WaterfallChartToastProjectBudget_files = [
  { filename: "index.tsx", code: `import ToastWaterfallChart from "@/components/flitter/charts/toast-waterfall-chart";

const chart = ToastWaterfallChart({
  data: {
    rows: [
      {
        item: "Budget",
        amount: 120,
      },
      {
        item: "Design",
        amount: -22,
      },
      {
        item: "Engineering",
        amount: -46,
      },
      {
        item: "QA",
        amount: -14,
      },
      {
        item: "Scope added",
        amount: 18,
      },
      {
        item: "Launch",
        amount: -12,
      },
    ],
    xKey: "item",
    yKey: "amount",
    totals: [
      {
        totalType: "total",
        index: 5,
        axisLabel: "Remaining",
      },
    ],
  },

  config: { title: { text: galleryTitle, visible: true } },
});` },
];

export type GalleryEntryGenerated = {
  slug: string;
  chartType: string;
  style: "Toast" | "AG";
  title: string;
  createWidget: () => Widget;
  thumbnailUrl: string;
  files: { filename: string; code: string }[];
  installCommand: string;
};

export const galleryEntries: GalleryEntryGenerated[] = [
  {
    slug: "area-chart-ag-profit-loss",
    chartType: "area-chart",
    style: "AG",
    title: "Quarterly Profit & Loss by Division",
    createWidget: _AreaChartAgProfitLoss,
    thumbnailUrl: "/charts/area-chart-ag-profit-loss.svg",
    files: _AreaChartAgProfitLoss_files,
    installCommand: "npx flitter-ui add area-chart --ag",
  },
  {
    slug: "area-chart-toast-app-downloads",
    chartType: "area-chart",
    style: "Toast",
    title: "Transportation Usage by Country",
    createWidget: _AreaChartToastAppDownloads,
    thumbnailUrl: "/charts/area-chart-toast-app-downloads.svg",
    files: _AreaChartToastAppDownloads_files,
    installCommand: "npx flitter-ui add area-chart --toast",
  },
  {
    slug: "bar-chart-ag-city-rent",
    chartType: "bar-chart",
    style: "AG",
    title: "Weekend Coffee Orders by City",
    createWidget: _BarChartAgCityRent,
    thumbnailUrl: "/charts/bar-chart-ag-city-rent.svg",
    files: _BarChartAgCityRent_files,
    installCommand: "npx flitter-ui add bar-chart --ag",
  },
  {
    slug: "bar-chart-toast-department-revenue",
    chartType: "bar-chart",
    style: "Toast",
    title: "Monthly Visitors by City",
    createWidget: _BarChartToastDepartmentRevenue,
    thumbnailUrl: "/charts/bar-chart-toast-department-revenue.svg",
    files: _BarChartToastDepartmentRevenue_files,
    installCommand: "npx flitter-ui add bar-chart --toast",
  },
  {
    slug: "bar-chart-toast-horizontal-pill",
    chartType: "bar-chart",
    style: "Toast",
    title: "Quarterly Profit / Loss by Division",
    createWidget: _BarChartToastHorizontalPill,
    thumbnailUrl: "/charts/bar-chart-toast-horizontal-pill.svg",
    files: _BarChartToastHorizontalPill_files,
    installCommand: "npx flitter-ui add bar-chart --toast",
  },
  {
    slug: "box-plot-chart-ag-api-latency",
    chartType: "box-plot-chart",
    style: "AG",
    title: "API Latency Distribution (ms)",
    createWidget: _BoxPlotChartAgApiLatency,
    thumbnailUrl: "/charts/box-plot-chart-ag-api-latency.svg",
    files: _BoxPlotChartAgApiLatency_files,
    installCommand: "npx flitter-ui add box-plot-chart --ag",
  },
  {
    slug: "box-plot-chart-toast-delivery-times",
    chartType: "box-plot-chart",
    style: "Toast",
    title: "Delivery Times by Region (days)",
    createWidget: _BoxPlotChartToastDeliveryTimes,
    thumbnailUrl: "/charts/box-plot-chart-toast-delivery-times.svg",
    files: _BoxPlotChartToastDeliveryTimes_files,
    installCommand: "npx flitter-ui add box-plot-chart --toast",
  },
  {
    slug: "bubble-chart-ag-gdp-life-expectancy",
    chartType: "bubble-chart",
    style: "AG",
    title: "GDP vs Life Expectancy",
    createWidget: _BubbleChartAgGdpLifeExpectancy,
    thumbnailUrl: "/charts/bubble-chart-ag-gdp-life-expectancy.svg",
    files: _BubbleChartAgGdpLifeExpectancy_files,
    installCommand: "npx flitter-ui add bubble-chart --ag",
  },
  {
    slug: "bubble-chart-toast-product-margin",
    chartType: "bubble-chart",
    style: "Toast",
    title: "Product Revenue vs Margin",
    createWidget: _BubbleChartToastProductMargin,
    thumbnailUrl: "/charts/bubble-chart-toast-product-margin.svg",
    files: _BubbleChartToastProductMargin_files,
    installCommand: "npx flitter-ui add bubble-chart --toast",
  },
  {
    slug: "bullet-chart-ag-revenue-targets",
    chartType: "bullet-chart",
    style: "AG",
    title: "Revenue Against Target ($M)",
    createWidget: _BulletChartAgRevenueTargets,
    thumbnailUrl: "/charts/bullet-chart-ag-revenue-targets.svg",
    files: _BulletChartAgRevenueTargets_files,
    installCommand: "npx flitter-ui add bullet-chart --ag",
  },
  {
    slug: "bullet-chart-toast-service-quality",
    chartType: "bullet-chart",
    style: "Toast",
    title: "Service Quality Against Target (%)",
    createWidget: _BulletChartToastServiceQuality,
    thumbnailUrl: "/charts/bullet-chart-toast-service-quality.svg",
    files: _BulletChartToastServiceQuality_files,
    installCommand: "npx flitter-ui add bullet-chart --toast",
  },
  {
    slug: "candlestick-chart-ag-bitcoin-monthly",
    chartType: "candlestick-chart",
    style: "AG",
    title: "Bitcoin Monthly OHLC",
    createWidget: _CandlestickChartAgBitcoinMonthly,
    thumbnailUrl: "/charts/candlestick-chart-ag-bitcoin-monthly.svg",
    files: _CandlestickChartAgBitcoinMonthly_files,
    installCommand: "npx flitter-ui add candlestick-chart --ag",
  },
  {
    slug: "donut-chart-ag-payment-methods",
    chartType: "donut-chart",
    style: "AG",
    title: "Payment Methods",
    createWidget: _DonutChartAgPaymentMethods,
    thumbnailUrl: "/charts/donut-chart-ag-payment-methods.svg",
    files: _DonutChartAgPaymentMethods_files,
    installCommand: "npx flitter-ui add donut-chart --ag",
  },
  {
    slug: "donut-chart-toast-project-status",
    chartType: "donut-chart",
    style: "Toast",
    title: "Cloud Infrastructure Spend",
    createWidget: _DonutChartToastProjectStatus,
    thumbnailUrl: "/charts/donut-chart-toast-project-status.svg",
    files: _DonutChartToastProjectStatus_files,
    installCommand: "npx flitter-ui add donut-chart --toast",
  },
  {
    slug: "funnel-chart-ag-product-onboarding",
    chartType: "funnel-chart",
    style: "AG",
    title: "Product Onboarding Funnel",
    createWidget: _FunnelChartAgProductOnboarding,
    thumbnailUrl: "/charts/funnel-chart-ag-product-onboarding.svg",
    files: _FunnelChartAgProductOnboarding_files,
    installCommand: "npx flitter-ui add funnel-chart --ag",
  },
  {
    slug: "funnel-chart-toast-sales-pipeline",
    chartType: "funnel-chart",
    style: "Toast",
    title: "Sales Pipeline Conversion",
    createWidget: _FunnelChartToastSalesPipeline,
    thumbnailUrl: "/charts/funnel-chart-toast-sales-pipeline.svg",
    files: _FunnelChartToastSalesPipeline_files,
    installCommand: "npx flitter-ui add funnel-chart --toast",
  },
  {
    slug: "heatmap-chart-ag-hourly-traffic",
    chartType: "heatmap-chart",
    style: "AG",
    title: "City Temperatures by Month",
    createWidget: _HeatmapChartAgHourlyTraffic,
    thumbnailUrl: "/charts/heatmap-chart-ag-hourly-traffic.svg",
    files: _HeatmapChartAgHourlyTraffic_files,
    installCommand: "npx flitter-ui add heatmap-chart --ag",
  },
  {
    slug: "heatmap-chart-toast-monthly-product-sales",
    chartType: "heatmap-chart",
    style: "Toast",
    title: "Ice Cream Sales by Flavor ($K)",
    createWidget: _HeatmapChartToastMonthlyProductSales,
    thumbnailUrl: "/charts/heatmap-chart-toast-monthly-product-sales.svg",
    files: _HeatmapChartToastMonthlyProductSales_files,
    installCommand: "npx flitter-ui add heatmap-chart --toast",
  },
  {
    slug: "histogram-chart-ag-parcel-weights",
    chartType: "histogram-chart",
    style: "AG",
    title: "Parcel Weight Distribution (kg)",
    createWidget: _HistogramChartAgParcelWeights,
    thumbnailUrl: "/charts/histogram-chart-ag-parcel-weights.svg",
    files: _HistogramChartAgParcelWeights_files,
    installCommand: "npx flitter-ui add histogram-chart --ag",
  },
  {
    slug: "histogram-chart-toast-response-times",
    chartType: "histogram-chart",
    style: "Toast",
    title: "Response Time Distribution (ms)",
    createWidget: _HistogramChartToastResponseTimes,
    thumbnailUrl: "/charts/histogram-chart-toast-response-times.svg",
    files: _HistogramChartToastResponseTimes_files,
    installCommand: "npx flitter-ui add histogram-chart --toast",
  },
  {
    slug: "line-chart-ag-monthly-active-users",
    chartType: "line-chart",
    style: "AG",
    title: "Average Monthly Temperature by City",
    createWidget: _LineChartAgMonthlyActiveUsers,
    thumbnailUrl: "/charts/line-chart-ag-monthly-active-users.svg",
    files: _LineChartAgMonthlyActiveUsers_files,
    installCommand: "npx flitter-ui add line-chart --ag",
  },
  {
    slug: "line-chart-toast-channel-traffic",
    chartType: "line-chart",
    style: "Toast",
    title: "Monthly Temperature by City",
    createWidget: _LineChartToastChannelTraffic,
    thumbnailUrl: "/charts/line-chart-toast-channel-traffic.svg",
    files: _LineChartToastChannelTraffic_files,
    installCommand: "npx flitter-ui add line-chart --toast",
  },
  {
    slug: "pie-chart-ag-browser-share",
    chartType: "pie-chart",
    style: "AG",
    title: "Browser Market Share",
    createWidget: _PieChartAgBrowserShare,
    thumbnailUrl: "/charts/pie-chart-ag-browser-share.svg",
    files: _PieChartAgBrowserShare_files,
    installCommand: "npx flitter-ui add pie-chart --ag",
  },
  {
    slug: "pie-chart-toast-budget-allocation",
    chartType: "pie-chart",
    style: "Toast",
    title: "Enterprise Software Market",
    createWidget: _PieChartToastBudgetAllocation,
    thumbnailUrl: "/charts/pie-chart-toast-budget-allocation.svg",
    files: _PieChartToastBudgetAllocation_files,
    installCommand: "npx flitter-ui add pie-chart --toast",
  },
  {
    slug: "radar-chart-ag-skill-assessment",
    chartType: "radar-chart",
    style: "AG",
    title: "Espresso Flavor Profile",
    createWidget: _RadarChartAgSkillAssessment,
    thumbnailUrl: "/charts/radar-chart-ag-skill-assessment.svg",
    files: _RadarChartAgSkillAssessment_files,
    installCommand: "npx flitter-ui add radar-chart --ag",
  },
  {
    slug: "radar-chart-toast-team-comparison",
    chartType: "radar-chart",
    style: "Toast",
    title: "Pokémon Stats Battle",
    createWidget: _RadarChartToastTeamComparison,
    thumbnailUrl: "/charts/radar-chart-toast-team-comparison.svg",
    files: _RadarChartToastTeamComparison_files,
    installCommand: "npx flitter-ui add radar-chart --toast",
  },
  {
    slug: "sankey-chart-ag-energy-flow",
    chartType: "sankey-chart",
    style: "AG",
    title: "Clean Energy Distribution (GWh)",
    createWidget: _SankeyChartAgEnergyFlow,
    thumbnailUrl: "/charts/sankey-chart-ag-energy-flow.svg",
    files: _SankeyChartAgEnergyFlow_files,
    installCommand: "npx flitter-ui add sankey-chart --ag",
  },
  {
    slug: "sankey-chart-toast-customer-journey",
    chartType: "sankey-chart",
    style: "Toast",
    title: "From Discovery to Subscription",
    createWidget: _SankeyChartToastCustomerJourney,
    thumbnailUrl: "/charts/sankey-chart-toast-customer-journey.svg",
    files: _SankeyChartToastCustomerJourney_files,
    installCommand: "npx flitter-ui add sankey-chart --toast",
  },
  {
    slug: "scatter-chart-ag-revenue-growth",
    chartType: "scatter-chart",
    style: "AG",
    title: "Revenue vs Growth Rate",
    createWidget: _ScatterChartAgRevenueGrowth,
    thumbnailUrl: "/charts/scatter-chart-ag-revenue-growth.svg",
    files: _ScatterChartAgRevenueGrowth_files,
    installCommand: "npx flitter-ui add scatter-chart --ag",
  },
  {
    slug: "scatter-chart-toast-student-scores",
    chartType: "scatter-chart",
    style: "Toast",
    title: "Student Test Scores",
    createWidget: _ScatterChartToastStudentScores,
    thumbnailUrl: "/charts/scatter-chart-toast-student-scores.svg",
    files: _ScatterChartToastStudentScores_files,
    installCommand: "npx flitter-ui add scatter-chart --toast",
  },
  {
    slug: "stacked-area-chart-ag-monthly-expenses",
    chartType: "stacked-area-chart",
    style: "AG",
    title: "Monthly Household Expenses ($)",
    createWidget: _StackedAreaChartAgMonthlyExpenses,
    thumbnailUrl: "/charts/stacked-area-chart-ag-monthly-expenses.svg",
    files: _StackedAreaChartAgMonthlyExpenses_files,
    installCommand: "npx flitter-ui add stacked-area-chart --ag",
  },
  {
    slug: "stacked-area-chart-toast-traffic-sources",
    chartType: "stacked-area-chart",
    style: "Toast",
    title: "Website Traffic Sources (K visits)",
    createWidget: _StackedAreaChartToastTrafficSources,
    thumbnailUrl: "/charts/stacked-area-chart-toast-traffic-sources.svg",
    files: _StackedAreaChartToastTrafficSources_files,
    installCommand: "npx flitter-ui add stacked-area-chart --toast",
  },
  {
    slug: "stacked-bar-chart-ag-energy-mix",
    chartType: "stacked-bar-chart",
    style: "AG",
    title: "Monthly Financial Overview",
    createWidget: _StackedBarChartAgEnergyMix,
    thumbnailUrl: "/charts/stacked-bar-chart-ag-energy-mix.svg",
    files: _StackedBarChartAgEnergyMix_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --ag",
  },
  {
    slug: "stacked-bar-chart-toast-nivo-pattern",
    chartType: "stacked-bar-chart",
    style: "Toast",
    title: "Monthly Financial Breakdown",
    createWidget: _StackedBarChartToastNivoPattern,
    thumbnailUrl: "/charts/stacked-bar-chart-toast-nivo-pattern.svg",
    files: _StackedBarChartToastNivoPattern_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --toast",
  },
  {
    slug: "stacked-bar-chart-toast-regional-sales",
    chartType: "stacked-bar-chart",
    style: "Toast",
    title: "Monthly Revenue Breakdown",
    createWidget: _StackedBarChartToastRegionalSales,
    thumbnailUrl: "/charts/stacked-bar-chart-toast-regional-sales.svg",
    files: _StackedBarChartToastRegionalSales_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --toast",
  },
  {
    slug: "sunburst-chart-ag-org-structure",
    chartType: "sunburst-chart",
    style: "AG",
    title: "Company Organization",
    createWidget: _SunburstChartAgOrgStructure,
    thumbnailUrl: "/charts/sunburst-chart-ag-org-structure.svg",
    files: _SunburstChartAgOrgStructure_files,
    installCommand: "npx flitter-ui add sunburst-chart --ag",
  },
  {
    slug: "sunburst-chart-toast-world-population",
    chartType: "sunburst-chart",
    style: "Toast",
    title: "World Population by Region (millions)",
    createWidget: _SunburstChartToastWorldPopulation,
    thumbnailUrl: "/charts/sunburst-chart-toast-world-population.svg",
    files: _SunburstChartToastWorldPopulation_files,
    installCommand: "npx flitter-ui add sunburst-chart --toast",
  },
  {
    slug: "treemap-chart-ag-disk-space-usage",
    chartType: "treemap-chart",
    style: "AG",
    title: "Disk Space Usage",
    createWidget: _TreemapChartAgDiskSpaceUsage,
    thumbnailUrl: "/charts/treemap-chart-ag-disk-space-usage.svg",
    files: _TreemapChartAgDiskSpaceUsage_files,
    installCommand: "npx flitter-ui add treemap-chart --ag",
  },
  {
    slug: "treemap-chart-toast-global-revenue-breakdown",
    chartType: "treemap-chart",
    style: "Toast",
    title: "Global Streaming Revenue (2025)",
    createWidget: _TreemapChartToastGlobalRevenueBreakdown,
    thumbnailUrl: "/charts/treemap-chart-toast-global-revenue-breakdown.svg",
    files: _TreemapChartToastGlobalRevenueBreakdown_files,
    installCommand: "npx flitter-ui add treemap-chart --toast",
  },
  {
    slug: "waterfall-chart-ag-operating-profit",
    chartType: "waterfall-chart",
    style: "AG",
    title: "Revenue to Operating Profit ($k)",
    createWidget: _WaterfallChartAgOperatingProfit,
    thumbnailUrl: "/charts/waterfall-chart-ag-operating-profit.svg",
    files: _WaterfallChartAgOperatingProfit_files,
    installCommand: "npx flitter-ui add waterfall-chart --ag",
  },
  {
    slug: "waterfall-chart-toast-project-budget",
    chartType: "waterfall-chart",
    style: "Toast",
    title: "Project Budget Remaining ($k)",
    createWidget: _WaterfallChartToastProjectBudget,
    thumbnailUrl: "/charts/waterfall-chart-toast-project-budget.svg",
    files: _WaterfallChartToastProjectBudget_files,
    installCommand: "npx flitter-ui add waterfall-chart --toast",
  },
];

export const galleryCategories = [
  { id: "area-chart", label: "Area" },
  { id: "bar-chart", label: "Bar" },
  { id: "box-plot-chart", label: "Box Plot" },
  { id: "bubble-chart", label: "Bubble" },
  { id: "bullet-chart", label: "Bullet" },
  { id: "candlestick-chart", label: "Candlestick" },
  { id: "donut-chart", label: "Donut" },
  { id: "funnel-chart", label: "Funnel" },
  { id: "heatmap-chart", label: "Heatmap" },
  { id: "histogram-chart", label: "Histogram" },
  { id: "line-chart", label: "Line" },
  { id: "pie-chart", label: "Pie" },
  { id: "radar-chart", label: "Radar" },
  { id: "sankey-chart", label: "Sankey" },
  { id: "scatter-chart", label: "Scatter" },
  { id: "stacked-area-chart", label: "Stacked Area" },
  { id: "stacked-bar-chart", label: "Stacked Bar" },
  { id: "sunburst-chart", label: "Sunburst" },
  { id: "treemap-chart", label: "Treemap" },
  { id: "waterfall-chart", label: "Waterfall" },
];

export const todoCategories = [
];
