// Auto-generated by scripts/generate-gallery.mjs
// Do not edit manually. Run: npm run gen:gallery

import _AreaChartAgProfitLoss from "./entries/area-chart/ag/profit-loss";
import _AreaChartToastAppDownloads from "./entries/area-chart/toast/app-downloads";
import _BarChartAgCityRent from "./entries/bar-chart/ag/city-rent";
import _BarChartToastDepartmentRevenue from "./entries/bar-chart/toast/department-revenue";
import _BarChartToastHorizontalPill from "./entries/bar-chart/toast/horizontal-pill";
import _BubbleChartAgGdpLifeExpectancy from "./entries/bubble-chart/ag/gdp-life-expectancy";
import _BubbleChartToastProductMargin from "./entries/bubble-chart/toast/product-margin";
import _DonutChartAgPaymentMethods from "./entries/donut-chart/ag/payment-methods";
import _DonutChartToastProjectStatus from "./entries/donut-chart/toast/project-status";
import _HeatmapChartAgHourlyTraffic from "./entries/heatmap-chart/ag/hourly-traffic";
import _HeatmapChartToastMonthlyProductSales from "./entries/heatmap-chart/toast/monthly-product-sales";
import _LineChartAgMonthlyActiveUsers from "./entries/line-chart/ag/monthly-active-users";
import _LineChartToastChannelTraffic from "./entries/line-chart/toast/channel-traffic";
import _PieChartAgBrowserShare from "./entries/pie-chart/ag/browser-share";
import _PieChartToastBudgetAllocation from "./entries/pie-chart/toast/budget-allocation";
import _RadarChartAgSkillAssessment from "./entries/radar-chart/ag/skill-assessment";
import _RadarChartToastTeamComparison from "./entries/radar-chart/toast/team-comparison";
import _ScatterChartAgRevenueGrowth from "./entries/scatter-chart/ag/revenue-growth";
import _ScatterChartToastStudentScores from "./entries/scatter-chart/toast/student-scores";
import _StackedAreaChartAgMonthlyExpenses from "./entries/stacked-area-chart/ag/monthly-expenses";
import _StackedAreaChartToastTrafficSources from "./entries/stacked-area-chart/toast/traffic-sources";
import _StackedBarChartAgEnergyMix from "./entries/stacked-bar-chart/ag/energy-mix";
import _StackedBarChartToastNivoPattern from "./entries/stacked-bar-chart/toast/nivo-pattern";
import _StackedBarChartToastRegionalSales from "./entries/stacked-bar-chart/toast/regional-sales";
import _TreemapChartAgDiskSpaceUsage from "./entries/treemap-chart/ag/disk-space-usage";
import _TreemapChartToastGlobalRevenueBreakdown from "./entries/treemap-chart/toast/global-revenue-breakdown";

const _AreaChartAgProfitLoss_files = [
  { filename: "index.tsx", code: `import AreaChart from "@/components/flitter/charts/area-chart";

const chart = AreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Hardware", values: [-12.4, -8.7, -3.2, 4.5, 9.8, 15.2, 18.6, 14.3, 7.1, -2.5, -9.8, -14.1] },
      { legend: "Software", values: [5.3, 8.1, 12.7, 18.4, 22.0, 25.6, 28.9, 26.2, 19.5, 11.8, 6.4, 3.1] },
      { legend: "Services", values: [-4.8, -6.2, -1.5, 3.7, 8.4, 11.0, 13.5, 9.8, 2.3, -3.6, -7.9, -10.2] },
    ],
  },
  config: {
    title: { text: "Monthly Profit & Loss by Division", visible: true, alignment: "center" },
    subtitle: { text: "Revenue minus costs ($M) — 2024", visible: true },
    area: { spline: false, strokeWidth: 2, opacity: 0.25 },
  },
});` },
];

const _AreaChartToastAppDownloads_files = [
  { filename: "index.tsx", code: `import ToastAreaChart from "@/components/flitter/charts/toast-area-chart";

const chart = ToastAreaChart({
  data: {
    labels: ["plane", "helicopter", "boat", "train", "subway", "bus", "car", "moto", "bicycle", "horse", "skateboard", "others"],
    datasets: [
      { legend: "Norway", values: [600, 1000, 800, 1000, 500, 850, 600, 675, 720, 890, 700, 950] },
      { legend: "Germany", values: [565, 850, 734, 863, 268, 571, 396, 588, 442, 726, 640, 732] },
      { legend: "US", values: [435, 559, 482, 580, 167, 308, 255, 557, 437, 438, 543, 554] },
    ],
  },
  config: {
    title: { text: "Transportation Usage by Country", visible: true, alignment: "center" },
    area: { spline: true, strokeWidth: 2, opacity: 0.3 },
  },
});` },
];

const _BarChartAgCityRent_files = [
  { filename: "index.tsx", code: `import BarChart from "@/components/flitter/charts/bar-chart";

const chart = BarChart({
  data: {
    labels: [
      "Tokyo",
      "Paris",
      "London",
      "New York",
      "Seoul",
      "Berlin",
      "Sydney",
      "Toronto",
      "Dubai",
    ],
    datasets: [
      {
        legend: "Orders",
        values: [92, 78, 85, 70, 88, 45, 63, 51, 34],
      },
    ],
  },
  config: {
    title: { text: "Weekend Coffee Orders by City", visible: true },
    legend: { visible: false },
    bar: { cornerRadius: 2 },
  },
});` },
];

const _BarChartToastDepartmentRevenue_files = [
  { filename: "index.tsx", code: `import ToastBarChart from "@/components/flitter/charts/toast-bar-chart";

const chart = ToastBarChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
    datasets: [
      { legend: "Seoul", values: [65, 59, 80, 81, 56, 55, 40] },
      { legend: "Seattle", values: [28, 48, 40, 19, 86, 27, 90] },
      { legend: "Sydney", values: [35, 25, 30, 45, 35, 40, 25] },
    ],
  },
  config: {
    title: { text: "Monthly Visitors by City", visible: true },
    legend: { visible: true },
  },
});` },
];

const _BarChartToastHorizontalPill_files = [
  { filename: "index.tsx", code: `import ToastBarChart from "@/components/flitter/charts/toast-bar-chart";
import {
  Container,
  EdgeInsets,
  BoxDecoration,
  BorderRadius,
  Radius,
  Border,
  ZIndex,
  type Widget as FlitterWidget,
} from "flitter-core";
import type { BarChartContext } from "flitter-ui/chart";

const pillColors = ["#ef4444", "#10b981"];

function pillBar(
  { legend, value, isHovered }: { value: number; label: string; legend: string; index: number; isHovered: boolean },
  context: BarChartContext,
): FlitterWidget {
  const idx = context.legends.indexOf(legend);
  const baseColor = pillColors[idx % pillColors.length];
  const fillColor = baseColor + "44";
  const borderRadius = BorderRadius.all(Radius.circular(10));

  const decoration = isHovered
    ? new BoxDecoration({
        color: baseColor + "66",
        borderRadius,
        border: Border.all({ color: baseColor, width: 2 }),
      })
    : new BoxDecoration({
        color: fillColor,
        borderRadius,
        border: Border.all({ color: baseColor, width: 1.5 }),
      });

  return ZIndex({
    zIndex: isHovered ? 1 : 0,
    child: Container({
      margin: EdgeInsets.symmetric({ horizontal: 1 }),
      decoration,
    }),
  });
}

const chart = ToastBarChart({
  direction: "horizontal",
  data: {
    labels: ["Cloud", "Hardware", "Consulting", "Retail", "Media", "Logistics", "R&D", "Finance"],
    datasets: [
      { legend: "Loss", values: [-42, -18, -7, -3, -31, -12, -55, -8] },
      { legend: "Profit", values: [15, 6, 22, 26, 9, 38, 11, 64] },
    ],
  },
  custom: {
    bar: pillBar,
  },
  config: {
    colors: pillColors,
    title: { text: "Quarterly Profit / Loss by Division", visible: true },
    legend: { visible: true },
    bar: { cornerRadius: 10, gap: 1 },
  },
});` },
];

const _BubbleChartAgGdpLifeExpectancy_files = [
  { filename: "index.tsx", code: `import BubbleChart from "@/components/flitter/charts/bubble-chart";

const chart = BubbleChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 75, y: 82, value: 62, label: "China" },
          { x: 42, y: 74, value: 55, label: "India" },
          { x: 18, y: 68, value: 45, label: "Indonesia" },
          { x: 55, y: 78, value: 38, label: "Japan" },
          { x: 30, y: 71, value: 50, label: "Pakistan" },
          { x: 85, y: 84, value: 25, label: "S. Korea" },
          { x: 12, y: 65, value: 42, label: "Bangladesh" },
          { x: 48, y: 76, value: 35, label: "Thailand" },
          { x: 22, y: 70, value: 30, label: "Vietnam" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 52, y: 81, value: 48, label: "Germany" },
          { x: 45, y: 82, value: 40, label: "France" },
          { x: 60, y: 80, value: 35, label: "UK" },
          { x: 38, y: 83, value: 28, label: "Italy" },
          { x: 68, y: 81, value: 20, label: "Netherlands" },
          { x: 55, y: 79, value: 45, label: "Russia" },
          { x: 72, y: 82, value: 22, label: "Switzerland" },
          { x: 48, y: 80, value: 32, label: "Poland" },
          { x: 35, y: 78, value: 25, label: "Spain" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 65, y: 78, value: 60, label: "USA" },
          { x: 50, y: 81, value: 30, label: "Canada" },
          { x: 10, y: 72, value: 52, label: "Brazil" },
          { x: 15, y: 75, value: 35, label: "Mexico" },
          { x: 8, y: 74, value: 45, label: "Colombia" },
          { x: 20, y: 77, value: 18, label: "Chile" },
          { x: 12, y: 73, value: 40, label: "Argentina" },
          { x: 25, y: 76, value: 22, label: "Peru" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 6, y: 55, value: 58, label: "Nigeria" },
          { x: 8, y: 64, value: 42, label: "Ethiopia" },
          { x: 4, y: 62, value: 50, label: "Congo" },
          { x: 3, y: 58, value: 38, label: "Tanzania" },
          { x: 5, y: 72, value: 28, label: "S. Africa" },
          { x: 2, y: 60, value: 45, label: "Kenya" },
          { x: 7, y: 66, value: 22, label: "Uganda" },
          { x: 10, y: 68, value: 35, label: "Ghana" },
        ],
      },
    ],
  },
  config: {
    title: { text: "GDP per Capita vs Life Expectancy", visible: true },
    subtitle: {
      text: "Bubble size = population (millions) · by continent",
      visible: true,
    },
  },
});` },
];

const _BubbleChartToastProductMargin_files = [
  { filename: "index.tsx", code: `import ToastBubbleChart from "@/components/flitter/charts/toast-bubble-chart";

const chart = ToastBubbleChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 82, y: 45, value: 55, label: "China" },
          { x: 68, y: 58, value: 40, label: "India" },
          { x: 55, y: 35, value: 62, label: "Japan" },
          { x: 40, y: 68, value: 30, label: "S. Korea" },
          { x: 75, y: 52, value: 48, label: "Indonesia" },
          { x: 28, y: 42, value: 35, label: "Thailand" },
          { x: 62, y: 72, value: 25, label: "Vietnam" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 35, y: 78, value: 42, label: "Germany" },
          { x: 48, y: 65, value: 55, label: "France" },
          { x: 22, y: 82, value: 30, label: "UK" },
          { x: 58, y: 48, value: 38, label: "Italy" },
          { x: 42, y: 72, value: 20, label: "Spain" },
          { x: 15, y: 55, value: 45, label: "Poland" },
          { x: 52, y: 60, value: 28, label: "Netherlands" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 88, y: 32, value: 65, label: "USA" },
          { x: 72, y: 42, value: 50, label: "Canada" },
          { x: 45, y: 25, value: 58, label: "Brazil" },
          { x: 60, y: 38, value: 42, label: "Mexico" },
          { x: 32, y: 55, value: 35, label: "Argentina" },
          { x: 78, y: 28, value: 48, label: "Chile" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 50, y: 85, value: 20, label: "Australia" },
          { x: 65, y: 75, value: 32, label: "N. Zealand" },
          { x: 38, y: 62, value: 28, label: "Fiji" },
          { x: 72, y: 68, value: 18, label: "Papua N.G." },
          { x: 45, y: 80, value: 24, label: "Samoa" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Product Revenue vs Profit Margin", visible: true },
  },
});` },
];

const _DonutChartAgPaymentMethods_files = [
  { filename: "index.tsx", code: `import DonutChart from "@/components/flitter/charts/donut-chart";

const chart = DonutChart({
  data: {
    datasets: [
      { name: "Credit Card", value: 35 },
      { name: "Digital Wallet", value: 28 },
      { name: "Bank Transfer", value: 16 },
      { name: "Debit Card", value: 12 },
      { name: "Cash", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    radial: { visible: true },
    dataLabel: { visible: true },
    dataCenter: { visible: true },
    legend: { visible: false },
  },
});` },
];

const _DonutChartToastProjectStatus_files = [
  { filename: "index.tsx", code: `import ToastDonutChart from "@/components/flitter/charts/toast-donut-chart";

const chart = ToastDonutChart({
  data: {
    datasets: [
      { name: "AWS", value: 32 },
      { name: "Azure", value: 23 },
      { name: "Google Cloud", value: 11 },
      { name: "Alibaba", value: 5 },
      { name: "Oracle", value: 4 },
      { name: "Other", value: 25 },
    ],
  },
  config: {
    legend: { visible: false },
    radial: { visible: false },
  },
});` },
];

const _HeatmapChartAgHourlyTraffic_files = [
  { filename: "index.tsx", code: `import HeatmapChart from "@/components/flitter/charts/heatmap-chart";

const chart = HeatmapChart({
  data: {
    xLabels: [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ],
    yLabels: ["Seoul", "Seattle", "Sydney", "Moscow", "Jungfrau"],
    values: [
      [-3.5, -1.1, 4.0, 11.3, 17.2, 22.0, 25.5, 26.1, 21.3, 14.2, 6.1, -0.8],
      [5.4, 6.1, 8.0, 10.3, 13.5, 16.2, 19.4, 19.6, 16.5, 11.8, 7.5, 4.8],
      [25.8, 25.6, 24.0, 21.2, 17.5, 14.6, 13.5, 14.8, 17.4, 20.0, 22.4, 24.6],
      [-9.3, -7.5, -2.0, 6.2, 13.1, 17.5, 19.8, 17.6, 11.8, 5.3, -1.5, -6.8],
      [-8.1, -8.5, -5.8, -2.0, 2.8, 6.4, 8.9, 8.6, 5.8, 1.5, -3.4, -6.9],
    ],
  },
  config: {
    title: { text: "Average Monthly Temperature (\\u00B0C)", visible: true },
  },
});` },
];

const _HeatmapChartToastMonthlyProductSales_files = [
  { filename: "index.tsx", code: `import ToastHeatmapChart from "@/components/flitter/charts/toast-heatmap-chart";

const chart = ToastHeatmapChart({
  data: {
    xLabels: [
      "Jan", "Feb", "Mar", "Apr", "May", "Jun",
      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
    ],
    yLabels: [
      "Vanilla", "Chocolate", "Strawberry",
      "Mint Chip", "Cookie Dough", "Mango Sorbet",
    ],
    values: [
      [12, 11, 14, 18, 28, 38, 52, 50, 32, 20, 14, 13],
      [15, 14, 16, 20, 30, 40, 54, 51, 34, 22, 16, 17],
      [8, 7, 10, 15, 24, 34, 46, 44, 28, 16, 9, 8],
      [6, 5, 7, 10, 16, 22, 30, 28, 18, 11, 7, 6],
      [10, 9, 12, 16, 22, 30, 42, 40, 26, 17, 11, 12],
      [4, 3, 6, 12, 22, 36, 48, 46, 30, 14, 5, 3],
    ],
  },
  config: {
    title: { text: "Monthly Ice Cream Sales by Flavor ($K)", visible: true },
    heatmap: {
      colorRange: ["#FEE2E2", "#EF4444", "#7F1D1D"],
      segment: { gap: 0 },
    },
  },
});` },
];

const _LineChartAgMonthlyActiveUsers_files = [
  { filename: "index.tsx", code: `import LineChart from "@/components/flitter/charts/line-chart";

const chart = LineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Seoul", values: [-3.5, -1.1, 4.0, 11.3, 17.5, 21.5, 25.9, 27.2, 24.4, 13.9, 6.6, -0.6] },
      { legend: "Seattle", values: [3.8, 5.6, 7.0, 9.1, 12.4, 15.3, 17.5, 17.8, 15.0, 10.6, 6.6, 3.7] },
      { legend: "Sydney", values: [22.1, 22.0, 20.9, 18.3, 15.2, 12.8, 11.8, 13.0, 15.2, 17.6, 19.4, 21.2] },
    ],
  },
  config: {
    title: { text: "Average Monthly Temperature", visible: true },
    subtitle: { text: "Celsius degrees by city (2024)", visible: true },
  },
});` },
];

const _LineChartToastChannelTraffic_files = [
  { filename: "index.tsx", code: `import ToastLineChart from "@/components/flitter/charts/toast-line-chart";

const chart = ToastLineChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Moscow", values: [-9.1, -7.2, -1.3, 6.4, 13.2, 17.0, 19.2, 17.1, 11.3, 5.0, -1.8, -6.5] },
      { legend: "London", values: [4.9, 5.2, 7.3, 9.6, 12.8, 16.0, 18.4, 18.1, 15.2, 11.5, 7.6, 5.1] },
      { legend: "Tokyo", values: [5.4, 6.1, 9.4, 14.3, 18.7, 21.8, 25.7, 27.2, 23.5, 17.6, 12.4, 7.2] },
    ],
  },
  config: {
    title: { text: "Monthly Average Temperature (°C)", visible: true, alignment: "center" },
    line: { spline: true },
  },
});` },
];

const _PieChartAgBrowserShare_files = [
  { filename: "index.tsx", code: `import PieChart from "@/components/flitter/charts/pie-chart";

const chart = PieChart({
  data: {
    datasets: [
      { name: "Chrome", value: 65 },
      { name: "Safari", value: 18 },
      { name: "Firefox", value: 8 },
      { name: "Edge", value: 5 },
      { name: "Other", value: 4 },
    ],
  },
  config: {
    legend: { visible: false },
    radial: { visible: false },
    dataLabel: {
      visible: true,
      formatter: (args) =>
        args.percentage >= 5 ? \`\${args.name}\\n\${args.percentage.toFixed(0)}%\` : "",
    },
  },
});` },
];

const _PieChartToastBudgetAllocation_files = [
  { filename: "index.tsx", code: `import ToastPieChart from "@/components/flitter/charts/toast-pie-chart";

const chart = ToastPieChart({
  data: {
    datasets: [
      { name: "CRM", value: 22 },
      { name: "ERP", value: 19 },
      { name: "Security", value: 17 },
      { name: "Collaboration", value: 16 },
      { name: "Analytics", value: 14 },
      { name: "Other", value: 12 },
    ],
  },
  config: {
    title: { text: "Enterprise Software Market Share", visible: true },
    legend: { visible: true, position: "bottom" },
    radial: { visible: true },
    radialLabel: {
      formatter: (args) => args.name,
    },
    dataLabel: {
      visible: true,
      formatter: (args) => \`\${args.percentage.toFixed(1)}%\`,
    },
  },
});` },
];

const _RadarChartAgSkillAssessment_files = [
  { filename: "index.tsx", code: `import RadarChart from "@/components/flitter/charts/radar-chart";

const chart = RadarChart({
  data: {
    labels: [
      "Acidity",
      "Sweetness",
      "Body",
      "Bitterness",
      "Aroma",
      "Aftertaste",
    ],
    datasets: [
      { legend: "Ethiopian Yirgacheffe", values: [85, 72, 60, 35, 90, 78] },
    ],
  },
  config: {
    legend: { visible: false },
  },
});` },
];

const _RadarChartToastTeamComparison_files = [
  { filename: "index.tsx", code: `import ToastRadarChart from "@/components/flitter/charts/toast-radar-chart";

const chart = ToastRadarChart({
  data: {
    labels: [
      "Attack",
      "Defense",
      "Speed",
      "HP",
      "Sp.Atk",
      "Sp.Def",
    ],
    datasets: [
      { legend: "Pikachu", values: [55, 30, 95, 35, 50, 40] },
      { legend: "Bulbasaur", values: [49, 65, 45, 80, 65, 65] },
      { legend: "Charmander", values: [85, 43, 65, 39, 80, 35] },
    ],
  },
  config: {
    title: { text: "Pokémon Stats Battle", visible: true },
  },
});` },
];

const _ScatterChartAgRevenueGrowth_files = [
  { filename: "index.tsx", code: `import ScatterChart from "@/components/flitter/charts/scatter-chart";

const chart = ScatterChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 12, y: 28, label: "A1" }, { x: 18, y: 35, label: "A2" }, { x: 25, y: 42, label: "A3" },
          { x: 31, y: 48, label: "A4" }, { x: 38, y: 55, label: "A5" }, { x: 45, y: 61, label: "A6" },
          { x: 52, y: 67, label: "A7" }, { x: 58, y: 72, label: "A8" }, { x: 15, y: 32, label: "A9" },
          { x: 22, y: 39, label: "A10" }, { x: 35, y: 52, label: "A11" }, { x: 42, y: 58, label: "A12" },
          { x: 48, y: 63, label: "A13" }, { x: 55, y: 69, label: "A14" }, { x: 62, y: 74, label: "A15" },
          { x: 68, y: 78, label: "A16" }, { x: 75, y: 82, label: "A17" }, { x: 82, y: 86, label: "A18" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 8, y: 22, label: "E1" }, { x: 14, y: 30, label: "E2" }, { x: 20, y: 36, label: "E3" },
          { x: 27, y: 43, label: "E4" }, { x: 33, y: 49, label: "E5" }, { x: 40, y: 54, label: "E6" },
          { x: 46, y: 60, label: "E7" }, { x: 53, y: 65, label: "E8" }, { x: 60, y: 71, label: "E9" },
          { x: 66, y: 76, label: "E10" }, { x: 72, y: 80, label: "E11" }, { x: 10, y: 25, label: "E12" },
          { x: 24, y: 40, label: "E13" }, { x: 50, y: 62, label: "E14" }, { x: 78, y: 84, label: "E15" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 5, y: 15, label: "M1" }, { x: 11, y: 24, label: "M2" }, { x: 19, y: 33, label: "M3" },
          { x: 26, y: 41, label: "M4" }, { x: 34, y: 50, label: "M5" }, { x: 41, y: 57, label: "M6" },
          { x: 49, y: 64, label: "M7" }, { x: 56, y: 70, label: "M8" }, { x: 63, y: 75, label: "M9" },
          { x: 70, y: 81, label: "M10" }, { x: 77, y: 85, label: "M11" }, { x: 83, y: 88, label: "M12" },
          { x: 16, y: 29, label: "M13" }, { x: 37, y: 53, label: "M14" }, { x: 88, y: 90, label: "M15" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 3, y: 10, label: "F1" }, { x: 9, y: 18, label: "F2" }, { x: 17, y: 27, label: "F3" },
          { x: 23, y: 34, label: "F4" }, { x: 30, y: 44, label: "F5" }, { x: 36, y: 50, label: "F6" },
          { x: 44, y: 56, label: "F7" }, { x: 50, y: 62, label: "F8" }, { x: 57, y: 68, label: "F9" },
          { x: 64, y: 73, label: "F10" }, { x: 13, y: 21, label: "F11" }, { x: 42, y: 52, label: "F12" },
        ],
      },
    ],
  },
  config: {
    title: { text: "Revenue vs Annual Growth Rate", visible: true },
    subtitle: {
      text: "Regional performance by continent · $M vs %",
      visible: true,
    },
    scatter: {
      size: 7,
    },
  },
});` },
];

const _ScatterChartToastStudentScores_files = [
  { filename: "index.tsx", code: `import ToastScatterChart from "@/components/flitter/charts/toast-scatter-chart";

const chart = ToastScatterChart({
  data: {
    datasets: [
      {
        legend: "Asia",
        data: [
          { x: 72, y: 68, label: "A1" }, { x: 65, y: 78, label: "A2" }, { x: 80, y: 85, label: "A3" },
          { x: 85, y: 75, label: "A4" }, { x: 70, y: 82, label: "A5" }, { x: 77, y: 70, label: "A6" },
          { x: 63, y: 88, label: "A7" }, { x: 75, y: 60, label: "A8" }, { x: 82, y: 72, label: "A9" },
          { x: 68, y: 90, label: "A10" }, { x: 88, y: 80, label: "A11" }, { x: 58, y: 74, label: "A12" },
          { x: 92, y: 70, label: "A13" }, { x: 74, y: 92, label: "A14" }, { x: 60, y: 65, label: "A15" },
        ],
      },
      {
        legend: "Europe",
        data: [
          { x: 45, y: 52, label: "E1" }, { x: 38, y: 48, label: "E2" }, { x: 55, y: 60, label: "E3" },
          { x: 42, y: 55, label: "E4" }, { x: 50, y: 45, label: "E5" }, { x: 35, y: 42, label: "E6" },
          { x: 48, y: 58, label: "E7" }, { x: 52, y: 50, label: "E8" }, { x: 40, y: 62, label: "E9" },
          { x: 58, y: 40, label: "E10" }, { x: 33, y: 55, label: "E11" }, { x: 62, y: 35, label: "E12" },
          { x: 28, y: 60, label: "E13" }, { x: 46, y: 44, label: "E14" }, { x: 54, y: 68, label: "E15" },
        ],
      },
      {
        legend: "Americas",
        data: [
          { x: 75, y: 18, label: "M1" }, { x: 82, y: 25, label: "M2" }, { x: 68, y: 12, label: "M3" },
          { x: 88, y: 30, label: "M4" }, { x: 72, y: 22, label: "M5" }, { x: 80, y: 15, label: "M6" },
          { x: 65, y: 28, label: "M7" }, { x: 85, y: 20, label: "M8" }, { x: 78, y: 10, label: "M9" },
          { x: 60, y: 32, label: "M10" }, { x: 90, y: 8, label: "M11" }, { x: 95, y: 14, label: "M12" },
          { x: 55, y: 38, label: "M13" }, { x: 70, y: 5, label: "M14" }, { x: 84, y: 35, label: "M15" },
        ],
      },
      {
        legend: "Africa",
        data: [
          { x: 10, y: 75, label: "F1" }, { x: 18, y: 82, label: "F2" }, { x: 25, y: 68, label: "F3" },
          { x: 15, y: 85, label: "F4" }, { x: 8, y: 78, label: "F5" }, { x: 20, y: 70, label: "F6" },
          { x: 12, y: 88, label: "F7" }, { x: 22, y: 65, label: "F8" }, { x: 5, y: 80, label: "F9" },
          { x: 30, y: 72, label: "F10" }, { x: 3, y: 92, label: "F11" }, { x: 16, y: 60, label: "F12" },
          { x: 28, y: 90, label: "F13" }, { x: 7, y: 68, label: "F14" }, { x: 14, y: 95, label: "F15" },
        ],
      },
      {
        legend: "Oceania",
        data: [
          { x: 30, y: 35, label: "O1" }, { x: 22, y: 28, label: "O2" }, { x: 40, y: 45, label: "O3" },
          { x: 35, y: 30, label: "O4" }, { x: 28, y: 40, label: "O5" }, { x: 18, y: 22, label: "O6" },
          { x: 45, y: 50, label: "O7" }, { x: 32, y: 38, label: "O8" }, { x: 25, y: 48, label: "O9" },
          { x: 50, y: 55, label: "O10" }, { x: 15, y: 15, label: "O11" }, { x: 38, y: 25, label: "O12" },
          { x: 42, y: 58, label: "O13" }, { x: 20, y: 42, label: "O14" }, { x: 48, y: 32, label: "O15" },
        ],
      },
    ],
  },
  config: {
    title: {
      text: "Math vs Science Scores by Region",
      visible: true,
    },
    scatter: {
      size: 8,
      fill: false,
      strokeWidth: 2,
    },
  },
});` },
];

const _StackedAreaChartAgMonthlyExpenses_files = [
  { filename: "index.tsx", code: `import StackedAreaChart from "@/components/flitter/charts/stacked-area-chart";

const chart = StackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct"],
    datasets: [
      { legend: "Housing", values: [1200, 1200, 1250, 1250, 1300, 1300, 1350, 1350, 1400, 1400] },
      { legend: "Food & Dining", values: [480, 520, 450, 510, 560, 620, 580, 640, 550, 590] },
      { legend: "Transport", values: [320, 280, 310, 350, 390, 420, 450, 380, 340, 360] },
      { legend: "Utilities", values: [180, 200, 170, 150, 130, 160, 210, 240, 190, 170] },
    ],
  },
  config: {
    title: { text: "Monthly Household Expenses ($)", visible: true },
    area: { opacity: 0.65, spline: true },
  },
});` },
];

const _StackedAreaChartToastTrafficSources_files = [
  { filename: "index.tsx", code: `import ToastStackedAreaChart from "@/components/flitter/charts/toast-stacked-area-chart";

const chart = ToastStackedAreaChart({
  data: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep"],
    datasets: [
      { legend: "Organic", values: [40, 50, 60, 55, 70, 80, 95, 110, 125] },
      { legend: "Paid", values: [30, 35, 40, 45, 50, 55, 52, 58, 62] },
      { legend: "Referral", values: [20, 25, 20, 30, 25, 35, 32, 28, 38] },
    ],
  },
  config: {
    title: { text: "Website Traffic Sources (K visits)", visible: true, alignment: "center" },
    area: { opacity: 0.6, strokeWidth: 2, spline: true },
  },
});` },
];

const _StackedBarChartAgEnergyMix_files = [
  { filename: "index.tsx", code: `import StackedBarChart from "@/components/flitter/charts/stacked-bar-chart";

const chart = StackedBarChart({
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Budget", values: [5000, 3000, 5000, 7000, 6000, 4000, 1000] },
      { legend: "Income", values: [8000, 4000, 7000, 2000, 6000, 3000, 5000] },
      { legend: "Expenses", values: [4000, 3000, 5000, 4000, 3000, 4000, 3000] },
      { legend: "Debt", values: [6000, 3000, 3000, 2000, 5000, 4000, 2000] },
    ],
  },
  config: {
    title: { text: "Monthly Financial Overview", visible: true },
    legend: { visible: true, position: "right" },
  },
});` },
];

const _StackedBarChartToastNivoPattern_files = [
  { filename: "index.tsx", code: `import ToastStackedBarChart from "@/components/flitter/charts/toast-stacked-bar-chart";
import {
  Container,
  EdgeInsets,
  Stack,
  Alignment,
  CustomPaint,
  Size,
  Path,
  Rect,
  Offset,
  Text,
  TextStyle,
  ZIndex,
  Row,
  SizedBox,
  MainAxisSize,
  Padding,
  BoxDecoration,
  Opacity,
  type Widget as FlitterWidget,
} from "flitter-core";
import type { BarChartContext } from "flitter-ui/chart";

const backgroundColors = ["#e8c1a0", "#f47560", "#f1e15b", "#e8a838", "#61cdbb"];
const patternColors = ["#c49c81", "#d4573f", "#c9bd3e", "#c08a25", "#38bcb2"];

type LegendPatternType = "dots" | "stripes" | "crosshatch" | "diagonal-stripes" | "grid";
const legendPatterns: LegendPatternType[] = ["dots", "stripes", "crosshatch", "diagonal-stripes", "grid"];

function drawDotsPattern(path: Path, width: number, height: number) {
  for (let y = 4; y < height; y += 10) {
    for (let x = 4 + ((y % 20) / 2); x < width; x += 10) {
      path.addOval(Rect.fromCircle({ center: new Offset({ x, y }), radius: 2.5 }));
    }
  }
}

function drawStripesPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 12) {
    path.moveTo({ x: width, y });
    path.lineTo({ x: 0, y: y + width });
  }
}

function drawCrosshatchPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 14) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y: y + width });
    path.moveTo({ x: width, y });
    path.lineTo({ x: 0, y: y + width });
  }
}

function drawDiagonalStripesPattern(path: Path, width: number, height: number) {
  const max = Math.max(width, height);
  for (let y = -max; y < max; y += 10) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y: y + width });
  }
}

function drawGridPattern(path: Path, width: number, height: number) {
  for (let x = 0; x < width; x += 12) {
    path.moveTo({ x, y: 0 });
    path.lineTo({ x, y: height });
  }
  for (let y = 0; y < height; y += 12) {
    path.moveTo({ x: 0, y });
    path.lineTo({ x: width, y });
  }
}

function PatternBar(
  { legend, value, label, index, isHovered }: { value: number; label: string; legend: string; index: number; isHovered: boolean },
  context: BarChartContext,
): FlitterWidget {
  const idx = context.legends.indexOf(legend);
  const bgColor = backgroundColors[idx % backgroundColors.length];
  const patternColor = patternColors[idx % patternColors.length];
  const patternType = legendPatterns[idx % legendPatterns.length];

  return ZIndex({
    zIndex: isHovered ? 1 : 0,
    child: Container({
      width: Infinity,
      height: Infinity,
      margin: EdgeInsets.symmetric({ horizontal: 0 }),
      color: bgColor,
      child: Stack({
        alignment: Alignment.center,
        clipped: true,
        children: [
          CustomPaint({
            size: Size.maximum(),
            painter: {
              svg: {
                createDefaultSvgEl(svgContext: any) {
                  return { bar: svgContext.createSvgEl("path") };
                },
                paint({ bar }: any, size: any) {
                  const path = new Path();
                  const { width, height } = size;

                  if (patternType === "dots") {
                    bar.setAttribute("fill", patternColor);
                    drawDotsPattern(path, width, height);
                  } else if (patternType === "stripes") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "4");
                    bar.setAttribute("fill", "none");
                    drawStripesPattern(path, width, height);
                  } else if (patternType === "crosshatch") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "2");
                    bar.setAttribute("fill", "none");
                    drawCrosshatchPattern(path, width, height);
                  } else if (patternType === "diagonal-stripes") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "3");
                    bar.setAttribute("fill", "none");
                    drawDiagonalStripesPattern(path, width, height);
                  } else if (patternType === "grid") {
                    bar.setAttribute("stroke", patternColor);
                    bar.setAttribute("stroke-width", "1.5");
                    bar.setAttribute("fill", "none");
                    drawGridPattern(path, width, height);
                  }
                  bar.setAttribute("d", path.getD());
                },
              },
              canvas: {
                paint(context: any, size: any) {
                  const { width, height } = size;
                  const ctx = context as CanvasRenderingContext2D;

                  if (patternType === "dots") {
                    ctx.fillStyle = patternColor;
                    for (let y = 4; y < height; y += 10) {
                      for (let x = 4 + ((y % 20) / 2); x < width; x += 10) {
                        ctx.beginPath();
                        ctx.arc(x, y, 2.5, 0, Math.PI * 2);
                        ctx.fill();
                      }
                    }
                  } else if (patternType === "stripes") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 4;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 12) {
                      ctx.beginPath();
                      ctx.moveTo(width, y);
                      ctx.lineTo(0, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "crosshatch") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 2;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 14) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y + width);
                      ctx.stroke();
                      ctx.beginPath();
                      ctx.moveTo(width, y);
                      ctx.lineTo(0, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "diagonal-stripes") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 3;
                    const max = Math.max(width, height);
                    for (let y = -max; y < max; y += 10) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y + width);
                      ctx.stroke();
                    }
                  } else if (patternType === "grid") {
                    ctx.strokeStyle = patternColor;
                    ctx.lineWidth = 1.5;
                    for (let x = 0; x < width; x += 12) {
                      ctx.beginPath();
                      ctx.moveTo(x, 0);
                      ctx.lineTo(x, height);
                      ctx.stroke();
                    }
                    for (let y = 0; y < height; y += 12) {
                      ctx.beginPath();
                      ctx.moveTo(0, y);
                      ctx.lineTo(width, y);
                      ctx.stroke();
                    }
                  }
                },
              },
            },
          }),
          Text(value > 1500 ? \`\${value}\` : "", {
            style: new TextStyle({ fontSize: 11, color: "#555555", fontWeight: "bold" }),
          }),
        ],
      }),
    }),
  });
}

function PatternLegend(
  { name, index, isVisible }: { name: string; index: number; isVisible?: boolean },
  context: { config: any; isSeriesVisible?(legend: string): boolean },
): FlitterWidget {
  const bgColor = backgroundColors[index % backgroundColors.length];
  const visible = isVisible ?? context.isSeriesVisible?.(name) ?? true;

  const markerSize = 28;

  const marker = Container({
    width: markerSize,
    height: markerSize,
    color: bgColor,
  });

  const content = Padding({
    padding: EdgeInsets.symmetric({ horizontal: 8 }),
    child: Row({
      mainAxisSize: MainAxisSize.min,
      children: [
        marker,
        SizedBox({ width: 6 }),
        Text(name, {
          style: new TextStyle({
            fontSize: 12,
            color: "#333333",
          }),
        }),
      ],
    }),
  });

  return visible
    ? content
    : Opacity({
        opacity: 0.4,
        child: content,
      });
}

const chart = ToastStackedBarChart({
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Budget", values: [5000, 3000, 5000, 7000, 6000, 4000, 1000] },
      { legend: "Income", values: [8000, 4000, 7000, 2000, 6000, 3000, 5000] },
      { legend: "Expenses", values: [4000, 3000, 5000, 4000, 3000, 4000, 3000] },
      { legend: "Debt", values: [6000, 3000, 3000, 2000, 5000, 4000, 2000] },
    ],
  },
  custom: {
    bar: PatternBar,
    legend: PatternLegend,
  },
  config: {
    title: { text: "Monthly Financial Breakdown", visible: true },
    legend: {
      visible: true,
      position: "right-bottom",
    },
    bar: {
      gap: 0,
    },
  },
});` },
];

const _StackedBarChartToastRegionalSales_files = [
  { filename: "index.tsx", code: `import ToastStackedBarChart from "@/components/flitter/charts/toast-stacked-bar-chart";

const chart = ToastStackedBarChart({
  direction: "horizontal",
  data: {
    labels: ["June", "July", "Aug", "Sep", "Oct", "Nov", "Dec"],
    datasets: [
      { legend: "Revenue", values: [8000, 4000, 7000, -2000, 6000, -3000, 5000] },
      { legend: "Costs", values: [-4000, -3000, -5000, -4000, 3000, 4000, -3000] },
      { legend: "Net", values: [3000, -2000, 4000, 2000, -5000, 4000, -2000] },
    ],
  },
  config: {
    title: { text: "Monthly Revenue Breakdown", visible: true },
  },
});` },
];

const _TreemapChartAgDiskSpaceUsage_files = [
  { filename: "index.tsx", code: `import TreemapChart from "@/components/flitter/charts/treemap-chart";

const chart = TreemapChart({
  data: {
    datasets: [
      {
        legend: "Media",
        children: [
          { label: "Photos", secondaryLabel: "30 GB", value: 30 },
          { label: "Videos", secondaryLabel: "45 GB", value: 45 },
          { label: "Music", secondaryLabel: "12 GB", value: 12 },
        ],
      },
      {
        legend: "Work",
        children: [
          { label: "Documents", secondaryLabel: "18 GB", value: 18 },
          { label: "Projects", secondaryLabel: "25 GB", value: 25 },
        ],
      },
      {
        legend: "System",
        children: [
          { label: "Applications", secondaryLabel: "22 GB", value: 22 },
          { label: "OS & Cache", secondaryLabel: "35 GB", value: 35 },
        ],
      },
      {
        legend: "Other",
        value: 8,
        secondaryLabel: "8 GB",
      },
    ],
  },
  config: {
    title: { text: "Disk Space Usage (195 GB)", visible: true },
  },
});` },
];

const _TreemapChartToastGlobalRevenueBreakdown_files = [
  { filename: "index.tsx", code: `import ToastTreemapChart from "@/components/flitter/charts/toast-treemap-chart";

const chart = ToastTreemapChart({
  data: {
    datasets: [
      {
        legend: "Video",
        children: [
          { label: "Netflix", secondaryLabel: "$38.3B", value: 383 },
          { label: "Disney+", secondaryLabel: "$22.1B", value: 221 },
          { label: "YouTube Premium", secondaryLabel: "$15.7B", value: 157 },
        ],
      },
      {
        legend: "Music",
        children: [
          { label: "Spotify", secondaryLabel: "$18.4B", value: 184 },
          { label: "Apple Music", secondaryLabel: "$9.6B", value: 96 },
        ],
      },
      {
        legend: "Gaming",
        children: [
          { label: "Xbox Game Pass", secondaryLabel: "$12.2B", value: 122 },
          { label: "PS Plus", secondaryLabel: "$8.5B", value: 85 },
        ],
      },
      {
        legend: "Other",
        value: 42,
        secondaryLabel: "$4.2B",
      },
    ],
  },
  config: {
    title: { text: "Global Streaming Revenue by Platform (2025)", visible: true },
  },
});` },
];

export type GalleryEntryGenerated = {
  slug: string;
  chartType: string;
  style: "Toast" | "AG";
  title: string;
  Component: React.ComponentType;
  thumbnailUrl: string;
  files: { filename: string; code: string }[];
  installCommand: string;
};

export const galleryEntries: GalleryEntryGenerated[] = [
  {
    slug: "area-chart-ag-profit-loss",
    chartType: "area-chart",
    style: "AG",
    title: "Quarterly Profit & Loss by Division",
    Component: _AreaChartAgProfitLoss,
    thumbnailUrl: "/charts/area-chart-ag-profit-loss.svg",
    files: _AreaChartAgProfitLoss_files,
    installCommand: "npx flitter-ui add area-chart --ag",
  },
  {
    slug: "area-chart-toast-app-downloads",
    chartType: "area-chart",
    style: "Toast",
    title: "Transportation Usage by Country",
    Component: _AreaChartToastAppDownloads,
    thumbnailUrl: "/charts/area-chart-toast-app-downloads.svg",
    files: _AreaChartToastAppDownloads_files,
    installCommand: "npx flitter-ui add area-chart --toast",
  },
  {
    slug: "bar-chart-ag-city-rent",
    chartType: "bar-chart",
    style: "AG",
    title: "Weekend Coffee Orders by City",
    Component: _BarChartAgCityRent,
    thumbnailUrl: "/charts/bar-chart-ag-city-rent.svg",
    files: _BarChartAgCityRent_files,
    installCommand: "npx flitter-ui add bar-chart --ag",
  },
  {
    slug: "bar-chart-toast-department-revenue",
    chartType: "bar-chart",
    style: "Toast",
    title: "Monthly Visitors by City",
    Component: _BarChartToastDepartmentRevenue,
    thumbnailUrl: "/charts/bar-chart-toast-department-revenue.svg",
    files: _BarChartToastDepartmentRevenue_files,
    installCommand: "npx flitter-ui add bar-chart --toast",
  },
  {
    slug: "bar-chart-toast-horizontal-pill",
    chartType: "bar-chart",
    style: "Toast",
    title: "Quarterly Profit / Loss by Division",
    Component: _BarChartToastHorizontalPill,
    thumbnailUrl: "/charts/bar-chart-toast-horizontal-pill.svg",
    files: _BarChartToastHorizontalPill_files,
    installCommand: "npx flitter-ui add bar-chart --toast",
  },
  {
    slug: "bubble-chart-ag-gdp-life-expectancy",
    chartType: "bubble-chart",
    style: "AG",
    title: "GDP vs Life Expectancy",
    Component: _BubbleChartAgGdpLifeExpectancy,
    thumbnailUrl: "/charts/bubble-chart-ag-gdp-life-expectancy.svg",
    files: _BubbleChartAgGdpLifeExpectancy_files,
    installCommand: "npx flitter-ui add bubble-chart --ag",
  },
  {
    slug: "bubble-chart-toast-product-margin",
    chartType: "bubble-chart",
    style: "Toast",
    title: "Product Revenue vs Margin",
    Component: _BubbleChartToastProductMargin,
    thumbnailUrl: "/charts/bubble-chart-toast-product-margin.svg",
    files: _BubbleChartToastProductMargin_files,
    installCommand: "npx flitter-ui add bubble-chart --toast",
  },
  {
    slug: "donut-chart-ag-payment-methods",
    chartType: "donut-chart",
    style: "AG",
    title: "Payment Methods",
    Component: _DonutChartAgPaymentMethods,
    thumbnailUrl: "/charts/donut-chart-ag-payment-methods.svg",
    files: _DonutChartAgPaymentMethods_files,
    installCommand: "npx flitter-ui add donut-chart --ag",
  },
  {
    slug: "donut-chart-toast-project-status",
    chartType: "donut-chart",
    style: "Toast",
    title: "Cloud Infrastructure Spend",
    Component: _DonutChartToastProjectStatus,
    thumbnailUrl: "/charts/donut-chart-toast-project-status.svg",
    files: _DonutChartToastProjectStatus_files,
    installCommand: "npx flitter-ui add donut-chart --toast",
  },
  {
    slug: "heatmap-chart-ag-hourly-traffic",
    chartType: "heatmap-chart",
    style: "AG",
    title: "City Temperatures by Month",
    Component: _HeatmapChartAgHourlyTraffic,
    thumbnailUrl: "/charts/heatmap-chart-ag-hourly-traffic.svg",
    files: _HeatmapChartAgHourlyTraffic_files,
    installCommand: "npx flitter-ui add heatmap-chart --ag",
  },
  {
    slug: "heatmap-chart-toast-monthly-product-sales",
    chartType: "heatmap-chart",
    style: "Toast",
    title: "Ice Cream Sales by Flavor ($K)",
    Component: _HeatmapChartToastMonthlyProductSales,
    thumbnailUrl: "/charts/heatmap-chart-toast-monthly-product-sales.svg",
    files: _HeatmapChartToastMonthlyProductSales_files,
    installCommand: "npx flitter-ui add heatmap-chart --toast",
  },
  {
    slug: "line-chart-ag-monthly-active-users",
    chartType: "line-chart",
    style: "AG",
    title: "Average Monthly Temperature by City",
    Component: _LineChartAgMonthlyActiveUsers,
    thumbnailUrl: "/charts/line-chart-ag-monthly-active-users.svg",
    files: _LineChartAgMonthlyActiveUsers_files,
    installCommand: "npx flitter-ui add line-chart --ag",
  },
  {
    slug: "line-chart-toast-channel-traffic",
    chartType: "line-chart",
    style: "Toast",
    title: "Monthly Temperature by City",
    Component: _LineChartToastChannelTraffic,
    thumbnailUrl: "/charts/line-chart-toast-channel-traffic.svg",
    files: _LineChartToastChannelTraffic_files,
    installCommand: "npx flitter-ui add line-chart --toast",
  },
  {
    slug: "pie-chart-ag-browser-share",
    chartType: "pie-chart",
    style: "AG",
    title: "Browser Market Share",
    Component: _PieChartAgBrowserShare,
    thumbnailUrl: "/charts/pie-chart-ag-browser-share.svg",
    files: _PieChartAgBrowserShare_files,
    installCommand: "npx flitter-ui add pie-chart --ag",
  },
  {
    slug: "pie-chart-toast-budget-allocation",
    chartType: "pie-chart",
    style: "Toast",
    title: "Enterprise Software Market",
    Component: _PieChartToastBudgetAllocation,
    thumbnailUrl: "/charts/pie-chart-toast-budget-allocation.svg",
    files: _PieChartToastBudgetAllocation_files,
    installCommand: "npx flitter-ui add pie-chart --toast",
  },
  {
    slug: "radar-chart-ag-skill-assessment",
    chartType: "radar-chart",
    style: "AG",
    title: "Espresso Flavor Profile",
    Component: _RadarChartAgSkillAssessment,
    thumbnailUrl: "/charts/radar-chart-ag-skill-assessment.svg",
    files: _RadarChartAgSkillAssessment_files,
    installCommand: "npx flitter-ui add radar-chart --ag",
  },
  {
    slug: "radar-chart-toast-team-comparison",
    chartType: "radar-chart",
    style: "Toast",
    title: "Pokémon Stats Battle",
    Component: _RadarChartToastTeamComparison,
    thumbnailUrl: "/charts/radar-chart-toast-team-comparison.svg",
    files: _RadarChartToastTeamComparison_files,
    installCommand: "npx flitter-ui add radar-chart --toast",
  },
  {
    slug: "scatter-chart-ag-revenue-growth",
    chartType: "scatter-chart",
    style: "AG",
    title: "Revenue vs Growth Rate",
    Component: _ScatterChartAgRevenueGrowth,
    thumbnailUrl: "/charts/scatter-chart-ag-revenue-growth.svg",
    files: _ScatterChartAgRevenueGrowth_files,
    installCommand: "npx flitter-ui add scatter-chart --ag",
  },
  {
    slug: "scatter-chart-toast-student-scores",
    chartType: "scatter-chart",
    style: "Toast",
    title: "Student Test Scores",
    Component: _ScatterChartToastStudentScores,
    thumbnailUrl: "/charts/scatter-chart-toast-student-scores.svg",
    files: _ScatterChartToastStudentScores_files,
    installCommand: "npx flitter-ui add scatter-chart --toast",
  },
  {
    slug: "stacked-area-chart-ag-monthly-expenses",
    chartType: "stacked-area-chart",
    style: "AG",
    title: "Monthly Household Expenses ($)",
    Component: _StackedAreaChartAgMonthlyExpenses,
    thumbnailUrl: "/charts/stacked-area-chart-ag-monthly-expenses.svg",
    files: _StackedAreaChartAgMonthlyExpenses_files,
    installCommand: "npx flitter-ui add stacked-area-chart --ag",
  },
  {
    slug: "stacked-area-chart-toast-traffic-sources",
    chartType: "stacked-area-chart",
    style: "Toast",
    title: "Website Traffic Sources (K visits)",
    Component: _StackedAreaChartToastTrafficSources,
    thumbnailUrl: "/charts/stacked-area-chart-toast-traffic-sources.svg",
    files: _StackedAreaChartToastTrafficSources_files,
    installCommand: "npx flitter-ui add stacked-area-chart --toast",
  },
  {
    slug: "stacked-bar-chart-ag-energy-mix",
    chartType: "stacked-bar-chart",
    style: "AG",
    title: "Monthly Financial Overview",
    Component: _StackedBarChartAgEnergyMix,
    thumbnailUrl: "/charts/stacked-bar-chart-ag-energy-mix.svg",
    files: _StackedBarChartAgEnergyMix_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --ag",
  },
  {
    slug: "stacked-bar-chart-toast-nivo-pattern",
    chartType: "stacked-bar-chart",
    style: "Toast",
    title: "Monthly Financial Breakdown",
    Component: _StackedBarChartToastNivoPattern,
    thumbnailUrl: "/charts/stacked-bar-chart-toast-nivo-pattern.svg",
    files: _StackedBarChartToastNivoPattern_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --toast",
  },
  {
    slug: "stacked-bar-chart-toast-regional-sales",
    chartType: "stacked-bar-chart",
    style: "Toast",
    title: "Monthly Revenue Breakdown",
    Component: _StackedBarChartToastRegionalSales,
    thumbnailUrl: "/charts/stacked-bar-chart-toast-regional-sales.svg",
    files: _StackedBarChartToastRegionalSales_files,
    installCommand: "npx flitter-ui add stacked-bar-chart --toast",
  },
  {
    slug: "treemap-chart-ag-disk-space-usage",
    chartType: "treemap-chart",
    style: "AG",
    title: "Disk Space Usage",
    Component: _TreemapChartAgDiskSpaceUsage,
    thumbnailUrl: "/charts/treemap-chart-ag-disk-space-usage.svg",
    files: _TreemapChartAgDiskSpaceUsage_files,
    installCommand: "npx flitter-ui add treemap-chart --ag",
  },
  {
    slug: "treemap-chart-toast-global-revenue-breakdown",
    chartType: "treemap-chart",
    style: "Toast",
    title: "Global Streaming Revenue (2025)",
    Component: _TreemapChartToastGlobalRevenueBreakdown,
    thumbnailUrl: "/charts/treemap-chart-toast-global-revenue-breakdown.svg",
    files: _TreemapChartToastGlobalRevenueBreakdown_files,
    installCommand: "npx flitter-ui add treemap-chart --toast",
  },
];

export const galleryCategories = [
  { id: "area-chart", label: "Area" },
  { id: "bar-chart", label: "Bar" },
  { id: "bubble-chart", label: "Bubble" },
  { id: "donut-chart", label: "Donut" },
  { id: "heatmap-chart", label: "Heatmap" },
  { id: "line-chart", label: "Line" },
  { id: "pie-chart", label: "Pie" },
  { id: "radar-chart", label: "Radar" },
  { id: "scatter-chart", label: "Scatter" },
  { id: "stacked-area-chart", label: "Stacked Area" },
  { id: "stacked-bar-chart", label: "Stacked Bar" },
  { id: "treemap-chart", label: "Treemap" },
];

export const todoCategories = [
  "box-plot-chart",
  "bullet-chart",
  "candlestick-chart",
  "funnel-chart",
  "histogram-chart",
  "sankey-chart",
  "waterfall-chart",
];
